do $$ declare did uuid; pid uuid; actor uuid; wid uuid:=gen_random_uuid(); cmd jsonb; result jsonb; graph jsonb; jid uuid; old_game jsonb;
begin
 if current_setting('graphcore.animation_test_transaction',true) is distinct from 'on' then raise exception 'Rollback-only test'; end if;
 if has_function_privilege('authenticated','public.animation_studio_finish_edit(uuid,text,bigint,jsonb)','execute') then raise exception 'Worker write permission leak'; end if;
 select d.id,d.project_id,m.user_id into strict did,pid,actor from public.project_drafts d join public.projects p on p.id=d.project_id join public.workspace_memberships m on m.workspace_id=p.workspace_id where m.role='owner' limit 1;
 select to_jsonb(w) into old_game from public.game_workspaces w where draft_id=did;
 graph:='{"version":3,"nodes":[],"name":"Flexible rollback fixture"}';
 cmd:=jsonb_build_object('projectId',pid,'draftId',did,'workspaceId',wid,'idempotencyKey',gen_random_uuid(),'expectedRevision',0,'action','save','graph',graph);
 result:=public.animation_studio_command(actor,cmd,jsonb_build_object('graph',graph));
 if public.animation_studio_command(actor,cmd)<>result then raise exception 'Replay mismatch'; end if;
 cmd:=cmd||jsonb_build_object('action','plan','expectedRevision',1,'idempotencyKey',gen_random_uuid(),'prompt','Create a wave then bow','nodeIds','[]'::jsonb);
 result:=public.animation_studio_command(actor,cmd,'{"credits":0}');jid:=(result->'jobIds'->>0)::uuid;
 update public.game_jobs set status='running',lease_owner='flex-test',lease_until=now()+interval '1 minute',fence=1 where id=jid;
 if public.animation_studio_finish_edit(jid,'flex-test',0,jsonb_build_object('graph',graph,'scopeExpansion','[]'::jsonb)) then raise exception 'Stale fence accepted'; end if;
 if not public.animation_studio_finish_edit(jid,'flex-test',1,jsonb_build_object('graph',graph||'{"name":"Wave and bow"}','scopeExpansion','[]'::jsonb,'summary','Added two motions')) then raise exception 'Edit failed'; end if;
 if (select revision from public.animation_studio_workspaces where id=wid)<>2 then raise exception 'Edit did not apply atomically'; end if;
 if public.animation_studio_finish_edit(jid,'flex-test',1,jsonb_build_object('graph',graph)) then raise exception 'Repeated finish accepted'; end if;
 cmd:=cmd||jsonb_build_object('expectedRevision',2,'idempotencyKey',gen_random_uuid());result:=public.animation_studio_command(actor,cmd,'{"credits":0}');jid:=(result->'jobIds'->>0)::uuid;
 perform public.animation_studio_command(actor,cmd||jsonb_build_object('action','restore','revision',1,'idempotencyKey',gen_random_uuid()),jsonb_build_object('graph',graph));
 update public.game_jobs set status='running',lease_owner='flex-test',lease_until=now()+interval '1 minute',fence=1 where id=jid;
 perform public.animation_studio_finish_edit(jid,'flex-test',1,jsonb_build_object('graph',graph,'scopeExpansion','[]'::jsonb));
 if (select phase from public.game_jobs where id=jid)<>'edit.conflict' then raise exception 'Stale edit overwrote revision'; end if;
 if (select revision from public.animation_studio_workspaces where id=wid)<>3 then raise exception 'Stale edit changed revision'; end if;
 cmd:=cmd||jsonb_build_object('expectedRevision',3,'idempotencyKey',gen_random_uuid());result:=public.animation_studio_command(actor,cmd,'{"credits":0}');jid:=(result->'jobIds'->>0)::uuid;
 update public.game_jobs set status='running',lease_owner='flex-test',lease_until=now()+interval '1 minute',fence=1 where id=jid;
 perform public.animation_studio_finish_edit(jid,'flex-test',1,jsonb_build_object('graph',graph,'scopeExpansion','["shared style"]'::jsonb));
 if (select phase from public.game_jobs where id=jid)<>'edit.scope_review' then raise exception 'Expanded edit applied without review'; end if;
 if (select to_jsonb(w) from public.game_workspaces w where draft_id=did) is distinct from old_game then raise exception 'Standalone edits changed gameplay'; end if;
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);perform set_config('request.jwt.claims','{"role":"authenticated"}',true);set local role authenticated;
 if exists(select 1 from public.animation_studio_revisions where workspace_id=wid) then raise exception 'History read leaked'; end if;
 reset role;
end $$;
