do $$ declare did uuid; pid uuid; actor uuid; wid uuid:=gen_random_uuid(); cmd jsonb; result jsonb; graph jsonb; before_game jsonb; payload jsonb; before_jobs integer; job_ids jsonb;
begin
 if current_setting('graphcore.animation_test_transaction',true) is distinct from 'on' then raise exception 'Rollback-only test'; end if;
 if has_function_privilege('authenticated','public.animation_studio_command(uuid,jsonb,jsonb)','execute') or has_table_privilege('authenticated','public.animation_studio_workspaces','insert') then raise exception 'Studio write permission leak'; end if;
 select d.id,d.project_id,m.user_id into strict did,pid,actor from public.project_drafts d join public.projects p on p.id=d.project_id join public.workspace_memberships m on m.workspace_id=p.workspace_id where m.role='owner' limit 1;
 select to_jsonb(w) into before_game from public.game_workspaces w where draft_id=did;
 graph:=jsonb_build_object('version',2,'nodes',jsonb_build_array(jsonb_build_object('id','upright.idle','contractHash',repeat('c',64))),'name','Rollback verification');
 cmd:=jsonb_build_object('projectId',pid,'draftId',did,'workspaceId',wid,'idempotencyKey',gen_random_uuid(),'expectedRevision',0,'action','save','graph',graph);
 result:=public.animation_studio_command(actor,cmd,jsonb_build_object('graph',graph));
 if (result->>'revision')::integer<>1 then raise exception 'Save did not create revision'; end if;
 if public.animation_studio_command(actor,cmd)<>result then raise exception 'Replay mismatch'; end if;
 if (select to_jsonb(w) from public.game_workspaces w where draft_id=did) is distinct from before_game then raise exception 'Animation save changed a game'; end if;
 begin perform public.animation_studio_command(actor,cmd||jsonb_build_object('idempotencyKey',gen_random_uuid()),jsonb_build_object('graph',graph));raise exception 'Stale revision accepted'; exception when serialization_failure then null; end;
 begin perform public.animation_studio_command(gen_random_uuid(),cmd);raise exception 'Foreign owner admitted'; exception when insufficient_privilege then null; end;
 if (select count(*) from public.animation_studio_revisions where workspace_id=wid)<>1 then raise exception 'Replay created duplicate revisions'; end if;
 insert into public.game_animation_setup_budgets(id,total_cents,admission_cents,enabled) values('studio-rollback-test',3000,2500,true);
 execute replace(pg_get_functiondef('public.animation_studio_command(uuid,jsonb,jsonb)'::regprocedure),'kimodo-initial-2026-09','studio-rollback-test');
 cmd:=cmd-'graph'||jsonb_build_object('action','generate','expectedRevision',1,'idempotencyKey',gen_random_uuid(),'maxReservationCents',100);
 payload:=jsonb_build_object('requests',jsonb_build_array(jsonb_build_object('nodeId','upright.idle','recipe',jsonb_build_object('state','idle','motionContract',repeat('c',64)),'rig',jsonb_build_object('revision',repeat('b',64)),'provider',jsonb_build_object('reservationCents',100,'modelRevision','test','processingVersion','animation-1.1.0'))));
 select count(*) into before_jobs from public.game_jobs;
 begin perform public.animation_studio_command(actor,cmd||jsonb_build_object('maxReservationCents',0),payload);raise exception 'Maximum reservation ignored';exception when others then if sqlerrm<>'Reservation exceeds selected maximum' then raise;end if;end;
 if (select count(*) from public.game_jobs)<>before_jobs then raise exception 'Failed admission leaked jobs';end if;
 result:=public.animation_studio_command(actor,cmd,payload);job_ids:=result->'jobIds';
 if jsonb_array_length(job_ids)<>1 or public.animation_studio_command(actor,cmd)<>result then raise exception 'Generation replay duplicated work';end if;
 perform public.animation_studio_command(actor,cmd||jsonb_build_object('action','cancel','jobId',job_ids->>0,'idempotencyKey',gen_random_uuid()));
 if not exists(select 1 from public.game_jobs where id=(job_ids->>0)::uuid and status='cancelled' and fence=1) then raise exception 'Cancellation not fenced';end if;
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 perform set_config('request.jwt.claims','{"role":"authenticated"}',true);
 set local role authenticated;
 if exists(select 1 from public.animation_studio_workspaces where id=wid) then raise exception 'Foreign library read leak'; end if;
 reset role;
end $$;
