-- GraphCore uses authenticated workspaces and RLS-protected authoring data.
-- Seed data is intentionally omitted here because the initial flow expects a signed-in
-- user to create a workspace and project through the application or SQL scripts.
