app = "graphcore-game-preview"
primary_region = "lhr"
[build]
  dockerfile = "workers/game/preview.Dockerfile"
[build.args]
  VITE_GAME_RELEASE_URL = "https://znwdatidqdkzidempvkt.supabase.co/functions/v1/get-game-release"
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
