import test from 'node:test';
import assert from 'node:assert/strict';
import {newDesign} from './cityBuildingV3.ts';
import {resolveSculpt,type SculptVolume} from './citySculpt.ts';
import {freshStudio,studioFloorCount} from './cityStudio.ts';
import {upgradeStudioInterior} from './cityStudioInteriors.ts';
import {resetStudioDoors,removeStudioDoors,stepStudioDoors,toggleStudioDoor} from './cityStudioDoorState.ts';
import {StudioWalkingCollision,studioDeckHeight} from './cityStudioCollision.ts';
import {WalkingWorld,advanceFoot,createFootState} from './cityExploration.ts';
import {DriveWorld} from './cityDriveWorld.ts';
import type {StudioRecipe} from './cityStudioTypes.ts';

const volume=(id='main',patch:Partial<SculptVolume>={}):SculptVolume=>({id,kind:'rectangle',operation:'add',x:0,z:0,width:10,depth:12,startFloor:0,spanFloors:2,...patch});
const base=():StudioRecipe=>({version:5,volumes:[volume()],attachments:[],plotSize:24,studio:freshStudio()});
const resolve=(r:StudioRecipe)=>resolveSculpt(r,{...newDesign('interior-test'),groundHeight:3,floors:studioFloorCount(r),middleFloors:studioFloorCount(r)-1,crown:'none',roof:'flat'}).studio!;

test('interior upgrade is explicit and retains version-five appearance intent',()=>{const old=base(),next=upgradeStudioInterior(old);assert.equal(old.version,5);assert.equal(next.version,6);assert.deepEqual(next.volumes,old.volumes);assert.deepEqual(next.studio,old.studio);assert.equal(resolve(old).portals,undefined);assert.ok(resolve(next).interiorLevels?.length===2);});

test('partitions create two detected rooms and a real door aperture',()=>{const r=upgradeStudioInterior(base());assert.equal(r.version,6);if(r.version!==6)return;r.interior.partitions.push({id:'divider',floor:0,a:[-5,0],b:[5,0]});r.interior.doors.push({id:'inner-door',partitionId:'divider',u:.5,style:'panelled',hinge:'left'});const out=resolve(r);assert.deepEqual(out.inactive,[]);assert.equal(out.interiorLevels?.[0].rooms.length,2);assert.ok(out.portals?.some(p=>p.id==='inner-door'));assert.ok(!out.blockers.some(b=>b.id==='divider'));assert.ok(out.blockers.some(b=>b.id==='divider/left'));});

test('entrance leaf blocks the doorway when closed and opens for walking',()=>{const r=upgradeStudioInterior(base()),out=resolve(r),portal=out.portals!.find(p=>p.id.startsWith('exterior/'))!;const collision=new StudioWalkingCollision();resetStudioDoors('test',[portal]);collision.set({id:'test',x:0,z:0,rotation:0,scale:1,result:{...out,portals:[portal]}});const nx=Math.sin(portal.rotation),nz=Math.cos(portal.rotation),x=portal.x,z=portal.z,y=portal.y+.2;assert.ok(collision.sweep(x+nx,y,z+nz,-nx*2,-nz*2,.3).t<1);assert.equal(collision.nearestDoor(x+nx,y,z+nz)?.doorId,portal.id);assert.equal(toggleStudioDoor('test',portal.id),true);stepStudioDoors(1);assert.equal(collision.sweep(x+nx,y,z+nz,-nx*2,-nz*2,.3).t,1);removeStudioDoors('test');});

test('a fitted stair owns its upper slab void and exposes a landing',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.stairs.push({id:'inside-stair',floor:0,x:0,z:-4,rotation:0,layout:'straight',flip:false});const out=resolve(r);assert.deepEqual(out.inactive,[]);assert.ok(out.decks.some(d=>d.id==='inside-stair/ramp0'));assert.ok(out.decks.some(d=>d.id==='inside-stair/upper'));assert.equal(out.decks.some(d=>d.id.startsWith('interior/1/')&&studioDeckHeight(d,0,-2)!==null),false);assert.ok(out.decks.some(d=>d.id.startsWith('interior/1/')&&studioDeckHeight(d,3,-2)!==null));const world=new StudioWalkingCollision();world.set({id:'test',x:0,z:0,rotation:0,scale:1,result:out});assert.ok(world.ground(3,-2,4)>world.ground(0,-2,1));});

test('a removed destination keeps its stair inactive without cutting unrelated floors',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.stairs.push({id:'inside-stair',floor:0,x:0,z:-4,rotation:0,layout:'auto',flip:false});r.volumes=[volume('main',{spanFloors:1})];const out=resolve(r);assert.ok(out.inactive.some(item=>item.id==='inside-stair'&&/occupied floors/.test(item.reason)));assert.equal(out.interiorLevels?.length,1);});

test('overlapping shafts preserve the second stair intent but do not cut a second opening',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.stairs.push({id:'first',floor:0,x:0,z:-4,rotation:0,layout:'straight',flip:false},{id:'second',floor:0,x:.3,z:-4,rotation:0,layout:'straight',flip:false});const out=resolve(r);assert.ok(out.decks.some(d=>d.id==='first/upper'));assert.ok(!out.decks.some(d=>d.id==='second/upper'));assert.match(out.inactive.find(item=>item.id==='second')?.reason??'',/already occupies/);});

test('a wall that crosses the middle of an existing shaft is inactive',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.stairs.push({id:'inside-stair',floor:0,x:0,z:-4,rotation:0,layout:'straight',flip:false});r.interior.partitions.push({id:'crossing-wall',floor:1,a:[-4,-1],b:[4,-1]});const out=resolve(r);assert.ok(out.inactive.some(item=>item.id==='crossing-wall'||item.id==='inside-stair'));});

test('every occupied upper level begins covered and only an explicit open-floor choice removes its slab',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;let out=resolve(r);assert.ok(out.interiorLevels?.[1].slab.length);assert.ok(out.decks.some(deck=>deck.id.startsWith('interior/1/')));r.interior.openFloors=[1];out=resolve(r);assert.equal(out.interiorLevels?.[1].slab.length,0);assert.ok(!out.decks.some(deck=>deck.id.startsWith('interior/1/')));assert.ok(out.interiorLevels?.[0].slab.length);const world=new StudioWalkingCollision();world.set({id:'hall',x:0,z:0,rotation:0,scale:1,result:out});assert.ok(world.ground(0,0,4)<1);r.interior.openFloors=[];assert.ok(resolve(r).interiorLevels?.[1].slab.length);});

test('opening an upper floor inactivates its stair and walls until the surface is restored',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.openFloors=[1];r.interior.stairs.push({id:'stair-to-hall',floor:0,x:0,z:-4,rotation:0,layout:'straight',flip:false});r.interior.partitions.push({id:'upper-wall',floor:1,a:[-5,0],b:[5,0]});r.interior.doors.push({id:'upper-door',partitionId:'upper-wall',u:.5,style:'panelled',hinge:'left'});const out=resolve(r);assert.ok(out.inactive.some(item=>item.id==='stair-to-hall'));assert.ok(out.inactive.some(item=>item.id==='upper-wall'));assert.ok(out.inactive.some(item=>item.id==='upper-door'));assert.ok(!out.portals?.some(door=>door.id==='upper-door'));});

test('separate volumes at the same storey retain both floor slabs and authored façade floors',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.volumes=[volume('west',{x:-4,width:3,depth:8}),volume('east',{x:4,width:3,depth:8})];const out=resolve(r);assert.ok(out.interiorLevels?.[1].slab.length);assert.equal(out.decks.filter(deck=>deck.id.startsWith('interior/1/')).length,2);assert.ok(out.bays.some(b=>b.anchor.shapeId==='west'&&b.anchor.floor===1));assert.ok(out.bays.some(b=>b.anchor.shapeId==='east'&&b.anchor.floor===1));});

test('a character follows the prepared stair ramp to the upper slab',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.stairs.push({id:'walk-stair',floor:0,x:0,z:-4,rotation:0,layout:'straight',flip:false});const out=resolve(r),walk=new WalkingWorld(new DriveWorld(300));walk.studio.set({id:'walk',x:0,z:0,rotation:0,scale:1,result:out});const foot=createFootState(0,-4);foot.y=out.decks.find(d=>d.id==='walk-stair/ramp0')!.y;for(let i=0;i<360;i++)advanceFoot(foot,{forward:true,reverse:false,left:false,right:false,walk:true},0,1/60,walk);assert.ok(foot.z>0,'the route reaches the upper landing');assert.ok(foot.y>2.7,`expected upper floor, reached ${foot.y}`);});

test('street entrance, partition door and stair form one walkable route',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.partitions.push({id:'lobby-wall',floor:0,a:[-5,3],b:[5,3]});r.interior.doors.push({id:'lobby-door',partitionId:'lobby-wall',u:.5,style:'panelled',hinge:'left'});r.interior.stairs.push({id:'route-stair',floor:0,x:0,z:-4,rotation:0,layout:'straight',flip:false});const out=resolve(r);assert.deepEqual(out.inactive,[]);const entrance=out.portals!.find(p=>p.id.startsWith('exterior/'))!,inner=out.portals!.find(p=>p.id==='lobby-door')!,walk=new WalkingWorld(new DriveWorld(300));resetStudioDoors('route',out.portals!);walk.studio.set({id:'route',x:0,z:0,rotation:0,scale:1,result:out});const nx=Math.sin(entrance.rotation),nz=Math.cos(entrance.rotation),foot=createFootState(entrance.x+nx*1.4,entrance.z+nz*1.4);const input={forward:true,reverse:false,left:false,right:false,walk:true};const toward=(x:number,z:number,frames:number)=>{for(let i=0;i<frames;i++){const heading=Math.atan2(x-foot.x,z-foot.z);advanceFoot(foot,input,heading,1/60,walk);if(Math.hypot(x-foot.x,z-foot.z)<.24)break;}};
 toward(entrance.x-nx,entrance.z-nz,120);assert.ok(Math.hypot(foot.x-entrance.x,foot.z-entrance.z)>.25,'closed street door blocks entry');assert.equal(toggleStudioDoor('route',entrance.id),true);stepStudioDoors(1);toward(entrance.x-nx,entrance.z-nz,120);assert.ok(Math.hypot(foot.x-(entrance.x-nx),foot.z-(entrance.z-nz))<.5,'entered the building');toward(inner.x,inner.z+1,120);toward(inner.x,inner.z-1,120);assert.ok(foot.z>inner.z-.5,'closed room door blocks route');assert.equal(toggleStudioDoor('route',inner.id),true);stepStudioDoors(1);toward(inner.x,inner.z-1,120);assert.ok(foot.z<inner.z-.5,'crossed the room door');toward(0,-4,200);toward(0,1.6,240);assert.ok(foot.y>2.7,`the character should reach the upper storey (${foot.y})`);removeStudioDoors('route');});

test('one upper room can open to below while its neighbour keeps a finished walkable floor',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.partitions.push({id:'upper-divider',floor:1,a:[-5,0],b:[5,0]});const initial=resolve(r),rooms=initial.interiorLevels![1].rooms;assert.equal(rooms.length,2);const north=rooms.find(room=>room.z>0)!,south=rooms.find(room=>room.z<0)!;r.interior.roomFinishes=[{id:'hall',floor:1,x:north.x,z:north.z,openToBelow:true},{id:'bedroom',floor:1,x:south.x,z:south.z,floorFinish:'tile',wallColor:'#c9b7a5'}];const out=resolve(r),level=out.interiorLevels![1],walk=new StudioWalkingCollision();assert.deepEqual(out.inactive,[]);assert.equal(level.rooms.find(room=>room.id==='hall')?.openToBelow,true);assert.equal(level.rooms.find(room=>room.id==='bedroom')?.floorFinish,'tile');assert.ok(level.roomSurfaces.some(surface=>surface.id==='bedroom'&&surface.vertices.length));assert.ok(level.blocks.some(block=>block.color==='#c9b7a5'));walk.set({id:'room',x:0,z:0,rotation:0,scale:1,result:out});assert.ok(walk.ground(north.x,north.z,4)<1);assert.ok(walk.ground(south.x,south.z,4)>2.7);});

test('furniture observes room, stair, doorway and overlap clearance',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.stairs.push({id:'stairs',floor:0,x:0,z:-4,rotation:0,layout:'straight',flip:false});r.interior.furniture=[{id:'table',floor:0,kind:'table',x:3,z:0,rotation:0},{id:'overlap',floor:0,kind:'chair',x:3,z:0,rotation:0},{id:'on-stair',floor:0,kind:'chair',x:0,z:-2,rotation:0},{id:'outside',floor:0,kind:'sofa',x:8,z:0,rotation:0}];const out=resolve(r);assert.ok(out.interiorLevels![0].furniture.some(item=>item.id==='table'));assert.ok(out.blockers.some(item=>item.id==='table'));assert.match(out.inactive.find(item=>item.id==='overlap')?.reason??'',/clear/);assert.match(out.inactive.find(item=>item.id==='on-stair')?.reason??'',/clear/);assert.match(out.inactive.find(item=>item.id==='outside')?.reason??'',/covered room/);});

test('room finish keeps its original partition boundary instead of spreading after a merge',()=>{const r=upgradeStudioInterior(base());if(r.version!==6)return;r.interior.partitions.push({id:'split',floor:0,a:[-5,0],b:[5,0]});const room=resolve(r).interiorLevels![0].rooms.find(room=>room.z>0)!;assert.deepEqual(room.boundaryIds,['split']);r.interior.roomFinishes=[{id:'north-paint',floor:0,x:room.x,z:room.z,boundaryIds:room.boundaryIds,floorFinish:'tile'}];assert.equal(resolve(r).interiorLevels![0].rooms.find(room=>room.id==='north-paint')?.floorFinish,'tile');r.interior.partitions=[];const merged=resolve(r);assert.ok(merged.inactive.some(item=>item.id==='north-paint'));assert.ok(merged.interiorLevels![0].rooms.every(room=>room.floorFinish==='timber'));r.interior.partitions.push({id:'split',floor:0,a:[-5,0],b:[5,0]});assert.equal(resolve(r).interiorLevels![0].rooms.find(room=>room.id==='north-paint')?.floorFinish,'tile');});
