import test from 'node:test';
import assert from 'node:assert/strict';
import {DriveWorld,pavementHeight} from './cityDriveWorld.ts';
import {createDriveState} from './cityDriving.ts';
import {WalkingWorld,advanceFoot,createFootState,findCarExit,canEnterCar,recoverFoot,PARKED_CAR,orbitFootCamera,zoomFootCamera,FOOT_CAMERA} from './cityExploration.ts';
const idle={forward:false,reverse:false,left:false,right:false,walk:false};
const step=1/120;
function setup(heading=0){const world=new DriveWorld(300),walk=new WalkingWorld(world),car=createDriveState(0,33,heading);walk.park(car);return {world,walk,car};}
test('exit and reenter both doors at arbitrary headings without touching parked car',()=>{for(let i=0;i<24;i++){const {walk,car}=setup(i*Math.PI/12),p=findCarExit(car,walk);assert.ok(p);assert.ok(walk.clear(p.x,p.z));assert.ok(canEnterCar(p,car,walk));p.grounded=false;assert.equal(canEnterCar(p,car,walk),false);}});
test('moving rejection, alternate door, rear exit and blocked exit',()=>{const {world,walk,car}=setup();car.vz=1;assert.equal(findCarExit(car,walk),null);car.vz=0;world.sync([{id:'right',minX:1.2,maxX:10,minZ:30,maxZ:36}]);assert.ok(findCarExit(car,walk)!.x<0);world.sync([{id:'sides',minX:-10,maxX:10,minZ:33,maxZ:40}]);assert.ok(findCarExit(car,walk)!.z<31);world.sync([{id:'all',minX:-10,maxX:10,minZ:20,maxZ:40}]);assert.equal(findCarExit(car,walk),null);});
test('entry cannot cross a plot even when close to a door',()=>{const {world,walk,car}=setup();const p=createFootState(2.5,33.3);world.sync([{id:'barrier',minX:1.8,maxX:2,minZ:30,maxZ:36}]);assert.equal(canEnterCar(p,car,walk),false);});
test('OBB sweeps stop at measured car sides and round corners at every heading',()=>{for(let i=0;i<32;i++){const h=i*Math.PI/16,{walk,car}=setup(h),cs=Math.cos(h),sn=Math.sin(h);const hit=walk.sweep(car.x+cs*10,car.z-sn*10,-cs*20,sn*20,.34);assert.ok(Math.abs(hit.t-(10-PARKED_CAR.halfWidth-.34)/20)<1e-6);assert.ok(Math.abs(hit.nx-cs)<1e-6);assert.ok(walk.world.sweep(car.x+cs*10,car.z-sn*10,-cs*20,sn*20,.34).t===1);}});
test('walk run and jump deterministic at 30/60/120Hz, buffered jump and wave cancellation',()=>{const states=[30,60,120].map(fps=>{const {walk}=setup();const s=createFootState(5,33);let acc=0,maxY=0;for(let frame=0;frame<fps*3;frame++){if(frame===fps){s.jumpBuffer=.12;s.wave=2;}acc+=1/fps;while(acc>=step-1e-10){advanceFoot(s,{...idle,forward:true,walk:false},0,step,walk);maxY=Math.max(maxY,s.y);acc-=step;}}assert.ok(maxY>.77&&maxY<1.01);assert.ok(s.grounded);assert.equal(s.wave,0);assert.ok(s.speed>5.49);return s;});for(const s of states)assert.ok(Math.hypot(s.x-states[0].x,s.z-states[0].z)<1e-6);});
test('sustained sliding, jump, and large deltas never enter protected plots',()=>{const {walk,world}=setup();world.sync([{id:'plot',minX:10,maxX:30,minZ:0,maxZ:100}]);const s=createFootState(9,20);for(let i=0;i<4000;i++){if(i%150===0)s.jumpBuffer=.12;advanceFoot(s,{...idle,forward:true,walk:false},Math.PI/4,step,walk);assert.ok(walk.clear(s.x,s.z));assert.ok(Number.isFinite(s.y));}const before=s.z;advanceFoot(s,{...idle,forward:true},0,50,walk);assert.ok(s.z-before<.25);});
test('pavement follows ground continuously and recovery avoids parked car and updated plots',()=>{const {walk,world}=setup();const s=createFootState(5,45);for(let i=0;i<120;i++)advanceFoot(s,{...idle,forward:true},Math.PI/2,step,walk);assert.ok(s.y>0);assert.equal(s.y,pavementHeight(s.x,s.z));const recovered=recoverFoot(walk,{x:0,z:33,heading:0});assert.ok(recovered&&walk.clear(recovered.x,recovered.z));world.sync([{id:'updated',minX:-10,maxX:10,minZ:20,maxZ:50}]);const next=recoverFoot(walk,{x:0,z:33,heading:0});assert.ok(next&&walk.clear(next.x,next.z));});
test('no phantom movement against car; emote stays grounded and stops on movement',()=>{const {walk}=setup();const s=createFootState(3,33);for(let i=0;i<300;i++)advanceFoot(s,{...idle,forward:true},-Math.PI/2,step,walk);assert.ok(s.speed<.01);assert.ok(walk.clear(s.x,s.z));s.wave=2;advanceFoot(s,idle,0,step,walk);assert.ok(s.wave>0);advanceFoot(s,{...idle,left:true},0,step,walk);assert.equal(s.wave,0);});

test('camera respects car sides but can look over its roof',()=>{const {walk}=setup();assert.ok(walk.sweepCamera(3,1,33,-6,0,0,.3).t<1);assert.equal(walk.sweepCamera(3,3,33,-6,0,0,.3).t,1);assert.ok(walk.sweep(3,33,-6,0,.34).t<1);});
test('jump buffering at landing and coyote time do not permit repeated air jumps',()=>{const {walk}=setup();const s=createFootState(4,33);s.grounded=false;s.y=.015;s.vy=-1;s.jumpBuffer=.12;s.coyote=0;advanceFoot(s,idle,0,step,walk);advanceFoot(s,idle,0,step,walk);advanceFoot(s,idle,0,step,walk);assert.ok(!s.grounded&&s.vy>4);s.jumpBuffer=.12;const vy=s.vy;advanceFoot(s,idle,0,step,walk);assert.ok(s.vy<vy);const edge=createFootState(4,33);edge.grounded=false;edge.y=.1;edge.coyote=.05;edge.jumpBuffer=.1;advanceFoot(edge,idle,0,step,walk);assert.ok(edge.vy>4);});

test('descending camera boom cannot enter the parked roof',()=>{const {walk}=setup();assert.ok(walk.sweepCamera(3,3,33,-3,-2,0,.3).t<1);});

test('running is default, Shift walking stays slower, diagonal motion is normalized and camera-relative',()=>{
 const speeds=[false,true].map(walk=>{const w=new WalkingWorld(new DriveWorld(500)),s=createFootState(0,100);for(let i=0;i<240;i++)advanceFoot(s,{...idle,forward:true,walk},Math.PI/2,step,w);assert.ok(s.x>0);assert.ok(Math.abs(s.z-100)<1e-5);return s.speed;});assert.ok(Math.abs(speeds[0]-5.5)<.01);assert.ok(Math.abs(speeds[1]-2.2)<.01);
 const w=new WalkingWorld(new DriveWorld(500)),s=createFootState(0,100);for(let i=0;i<240;i++)advanceFoot(s,{...idle,forward:true,left:true},0,step,w);assert.ok(Math.abs(s.speed-5.5)<.01);
});
test('orbit has unrestricted yaw with bounded pitch and reversible bounded zoom',()=>{
 const c={heading:0,pitch:.35,distance:5.2};orbitFootCamera(c,1500,1000);assert.ok(c.heading< -Math.PI*2);assert.equal(c.pitch,FOOT_CAMERA.maxPitch);orbitFootCamera(c,0,-1000);assert.equal(c.pitch,FOOT_CAMERA.minPitch);zoomFootCamera(c,200);zoomFootCamera(c,-200);assert.ok(Math.abs(c.distance-5.2)<1e-10);for(let i=0;i<20;i++)zoomFootCamera(c,-1000);assert.equal(c.distance,FOOT_CAMERA.minDistance);for(let i=0;i<20;i++)zoomFootCamera(c,1000);assert.equal(c.distance,FOOT_CAMERA.maxDistance);
});
