import test from 'node:test';
import assert from 'node:assert/strict';
import {createLandWorld,LocalLandRepository,initialLandDraft,landEntrance,landPosition,fitLandDesign,landPlants,studioStairPlantClearance,landProperty,landPrice,type LandStorage} from './cityLand.ts';
import {freshStudio} from './cityStudio.ts';
import {emptyCityProfile,type CityProperty} from './city.ts';
import {COMPOSITIONS,applyComposition} from './cityBuildingV3.ts';
import {DriveWorld,syncCityDriveWorld} from './cityDriveWorld.ts';
import {WalkingWorld,FOOT_PROFILE} from './cityExploration.ts';
const property:CityProperty={id:'occupied',slug:'occupied',x:1,z:1,rank:1,landValue:1000,tier:0,saves:0,claims:0,profile:emptyCityProfile()};
function setup(size:24|48=48){const initial=createLandWorld([property],400,size),store=new Map<string,string>();const storage:LandStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>{store.set(k,v);}};return {initial,store,storage,repo:new LocalLandRepository(storage,initial)};}
test('stable vacant allocation excludes occupied land and central facilities at both scales',()=>{
 for(const size of [24,48] as const){const {initial}=setup(size);assert.ok(!initial.plots.some(p=>p.x===1&&p.z===1));assert.equal(new Set(initial.plots.map(p=>p.id)).size,initial.plots.length);for(const p of initial.plots){assert.equal(p.size,size);assert.ok(p.x&&p.z);const {x,z}=landPosition(p);assert.ok(!(x-size/2<75&&x+size/2> -75&&z-size/2< -454&&z+size/2> -566));}}
});
test('purchase is idempotent and persisted; stale and duplicate ownership rejected',async()=>{const {repo,initial,storage}=setup();const p=initial.plots[0];const [a,b]=await Promise.all([repo.purchase(p.id,0,'receipt'),repo.purchase(p.id,0,'receipt')]);assert.deepEqual(a,b);assert.equal(a.revision,1);assert.equal(a.priceCents,500);assert.equal(a.currency,'USD');await assert.rejects(repo.purchase(p.id,0,'another'));const loaded=await new LocalLandRepository(storage,initial).list();assert.equal(loaded.plots[0].purchaseId,'receipt');});
test('draft and finished are independent and revision checked; reset restores seed world',async()=>{const {repo,initial}=setup();let p=await repo.purchase(initial.plots[0].id,0,'receipt');const draft=initialLandDraft(p);p=await repo.finish(p.id,p.revision,draft);const next={...draft,name:'New draft'};p=await repo.saveDraft(p.id,p.revision,next);assert.equal(p.finished?.name,'My place');assert.equal(p.draft?.name,'New draft');await assert.rejects(repo.saveDraft(p.id,p.revision-1,draft));const reset=await repo.reset();assert.equal(reset.plots[0].owner,null);assert.equal(reset.plots[0].vegetationSeed,initial.plots[0].vegetationSeed);});
test('failed storage never returns purchase success or silently changes ownership',async()=>{const {repo,initial,storage}=setup();await repo.list();const failing=new LocalLandRepository({...storage,setItem:()=>{throw new Error('quota');}},initial);await assert.rejects(failing.purchase(initial.plots[0].id,0,'receipt'),/quota/);assert.equal((await repo.list()).plots[0].owner,null);});
test('saved allocation wins over a changed demo snapshot',async()=>{const {repo,initial,storage}=setup();await repo.list();const changed=createLandWorld([{...property,x:5,z:5}],400,48);const loaded=await new LocalLandRepository(storage,changed).list();assert.deepEqual(loaded.occupied,initial.occupied);});
test('all entrances are outside protected plot boundaries and reachable along the street',()=>{for(const size of [24,48] as const){const {initial}=setup(size);const axis=(p:number)=>p===0?0:size===48?Math.sign(p)*(33+(Math.abs(p)-1)*66):Math.sign(p)*(21+((Math.abs(p)-1)%2)*24+Math.floor((Math.abs(p)-1)/2)*66);const world=new DriveWorld(1000);syncCityDriveWorld(world,[...initial.occupied,...initial.plots],axis,size,true,true);const walk=new WalkingWorld(world);for(const p of initial.plots){const e=landEntrance(p);assert.ok(walk.clear(e.x,e.z),p.id);assert.equal(walk.sweep(e.x-Math.sin(e.heading),e.z-Math.cos(e.heading),Math.sin(e.heading),Math.cos(e.heading),FOOT_PROFILE.radius).t,1);}}});
test('presets and handle extremes stay bounded with coherent floor stacks',()=>{const p=setup().initial.plots[0],d=initialLandDraft(p);for(let i=0;i<COMPOSITIONS.length;i++)for(const v of [-100,100]){const n=fitLandDesign({...applyComposition(d.design,i),width:v,depth:v,middleFloors:v},p.rotation);assert.ok(n.width>=8&&n.width<=18,COMPOSITIONS[i].name);assert.ok(n.depth>=8&&n.depth<=18);assert.ok(n.floors>=1&&n.floors<=8);assert.equal(n.rotation,p.rotation);assert.equal(n.finish,'procedural');assert.deepEqual(landProperty(p,{...d,design:n}).profile.buildingDesign,n);}});
test('vegetation is deterministic, reserved paths stay clear, and footprint suppression restores',()=>{const p=setup().initial.plots[0],d=initialLandDraft(p);d.nature={style:'wooded',density:8,seed:55};d.design.width=8;d.design.depth=8;const small=landPlants(p,d);assert.deepEqual(small,landPlants(p,d));d.design.width=18;d.design.depth=18;assert.ok(landPlants(p,d).length<=small.length);d.design.width=8;d.design.depth=8;assert.deepEqual(landPlants(p,d),small);assert.ok(small.every(p=>!(Math.abs(p.x)<3&&p.z>0)));});
test('procedural vegetation leaves the connected exterior stair corridor clear',()=>{const p=setup().initial.plots[0],d=initialLandDraft(p),studio=freshStudio();studio.assemblies.push({id:'stair',kind:'stair',anchors:[{shapeId:'main',side:'north',u:.5,floor:0}],look:'simple',destination:1});d.builderMode='sculpt';d.sculpt={version:5,plotSize:24,volumes:[{id:'main',kind:'rectangle',operation:'add',x:0,z:0,width:10,depth:8,startFloor:0,spanFloors:2}],attachments:[],studio};d.nature={style:'wooded',density:8,seed:55};assert.equal(studioStairPlantClearance(d,0,5),true);assert.equal(studioStairPlantClearance(d,0,9),false);assert.ok(landPlants(p,d).every(plant=>!studioStairPlantClearance(d,plant.x,plant.z)));});
test('two repositories cannot purchase the same available plot; currency is data-driven',async()=>{const {initial,storage,repo}=setup(),other=new LocalLandRepository(storage,initial),p=initial.plots[0];const results=await Promise.allSettled([repo.purchase(p.id,0,'one'),other.purchase(p.id,0,'two')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(landPrice(p),'$5');assert.equal(landPrice({...p,priceCents:1250}),'$12.50');});
