import type {SculptVolume, SculptWallAnchor} from './citySculpt.ts';
import type {BuildingVariation,StudioStamp} from './cityVariationTypes.ts';

export type StudioFamily = 'warm-brick' | 'pastel-stucco' | 'pale-limestone';
export type StudioChannel = 'wall' | 'trim' | 'frame' | 'door';
export type StudioRoof = 'flat' | 'terrace' | 'pitched' | 'mansard' | 'hip' | 'shed' | 'half-hip' | 'gambrel' | 'pyramid' | 'cone';
export type StudioRoofSettings={boundary?:'none'|'parapet'|'rail';rise?:number;overhang?:number;ridge?:'x'|'z';flip?:boolean;shoulder?:number;crown?:number;connection?:'auto'|'abut'|'separate';finish?:'slate'|'terracotta'|'metal';color?:string};
export type StudioRoofFace={partId:string;polygon:[number,number][][];plane:[number,number,number];base:number;underside?:number};
export type StudioRoofEdge={partId:string;kind:'eave'|'rake'|'ridge'|'valley'|'abutment'|'step';a:[number,number,number];b:[number,number,number]};
export type StudioRoofPatch={partId:string;vertices:number[];wallVertices?:number[];wallColor?:string;wallTexture?:string;finish?:StudioRoofSettings['finish'];color?:string};
export type StudioFinish = {color?: string; texture?: string};
export type StudioAnchor = SculptWallAnchor & {floor: number};
export type StudioSurface = {id: string; anchor: StudioAnchor; scope: 'spot' | 'wall'; channel: StudioChannel; finish: StudioFinish};
export type StudioOpening = {id: string; anchor: StudioAnchor; module: string; span?:number};
export type StudioRoofDetail = {id:string;partId:string;module:string;u:number;v:number;rotation:number};
export type StudioAssemblyKind = 'balcony' | 'cornice' | 'canopy' | 'stair' | 'pilaster' | 'ornament' | 'planter' | 'light';
export type StudioAssembly = {id: string; kind: StudioAssemblyKind; anchors: StudioAnchor[]; look: 'simple' | 'ornate'; variant?:'nyc'; module?:string; destination?: number; flip?: boolean; exit?: StudioAnchor; exitKind?:'door'|'balcony'|'terrace'; layout?:'auto'|'straight'|'switchback'};
export type StudioPartStyle = {family?: StudioFamily; rhythm?: 'sparse' | 'regular' | 'glazing'; window?: string; roof?: StudioRoof; roofSettings?:StudioRoofSettings; finishes?: Partial<Record<StudioChannel, StudioFinish>>};
export type StudioIntent = {catalogue: 'synarc-kit-2'|'synarc-kit-3'|'synarc-kit-4'|'synarc-kit-5'; variation?:BuildingVariation;stamps?:StudioStamp[]; roofRevision?:'roof-envelope-2'; assemblyRevision?:'connected-access-1'; defaults: StudioPartStyle; parts: Record<string, StudioPartStyle>; surfaces: StudioSurface[]; openings: StudioOpening[]; assemblies: StudioAssembly[];roofDetails?:StudioRoofDetail[]};
export type StudioPartition={id:string;floor:number;a:[number,number];b:[number,number]};
export type StudioInteriorDoor={id:string;partitionId:string;u:number;style:'panelled'|'glazed';hinge:'left'|'right'};
export type StudioInteriorStair={id:string;floor:number;x:number;z:number;rotation:number;layout:'auto'|'straight'|'switchback';flip:boolean};
export type StudioRoomFinish={id:string;floor:number;x:number;z:number;boundaryIds?:string[];floorFinish?:'timber'|'tile'|'stone';wallColor?:string;openToBelow?:boolean};
export type StudioFurnitureKind=keyof typeof import('./cityStudioFurniture.ts').STUDIO_FURNITURE;
export type StudioFurniture={id:string;floor:number;kind:StudioFurnitureKind;x:number;z:number;rotation:number};
export type StudioInteriorIntent={partitions:StudioPartition[];doors:StudioInteriorDoor[];stairs:StudioInteriorStair[];openFloors?:number[];roomFinishes?:StudioRoomFinish[];furniture?:StudioFurniture[];floorFinish:'timber'|'tile'|'stone';wallColor:string};
export type StudioRecipeBase={volumes:SculptVolume[];attachments:import('./citySculpt.ts').SculptAttachment[];plotSize?:24|48;tileAnchors?:import('./citySculpt.ts').SculptTileAnchor[];studio:StudioIntent};
export type StudioRecipe=({version:5}&StudioRecipeBase)|({version:6;interior:StudioInteriorIntent}&StudioRecipeBase);
export type StudioBay = {anchorSpan:number; id: string; anchor: StudioAnchor; x: number; z: number; y: number; width: number; height: number; rotation: number; module: string; family: StudioFamily; finishes: Partial<Record<StudioChannel, StudioFinish>>; entrance: boolean};
export type StudioPiece = {id: string; propertyId?:string; module: string; x: number; y: number; z: number; rotation: number; scale: [number, number, number]; family: StudioFamily; finishes?: Partial<Record<StudioChannel, StudioFinish>>};
export type StudioBox = {id: string; x: number; y: number; z: number; width: number; height: number; depth: number; rotation: number};
export type StudioDeck = {id: string; x: number; z: number; y: number; width: number; depth: number; rotation: number; rise?: number; underside?:number; plane?:[number,number,number]; polygon?: [number,number][][]};
export type StudioPortal={id:string;floor:number;x:number;y:number;z:number;width:number;height:number;rotation:number;hinge:'left'|'right';style:'panelled'|'glazed'};
export type StudioInteriorBlock=StudioBox&{floor:number;kind:'wall'|'frame'|'guard'|'stair';color?:string};
export type StudioRoom={id:string;x:number;z:number;area:number;polygon:[number,number][][];boundaryIds:string[];floorFinish:'timber'|'tile'|'stone';wallColor:string;openToBelow:boolean};
export type StudioInteriorLevel={floor:number;slab:number[];underside:number[];blocks:StudioInteriorBlock[];rooms:StudioRoom[];roomSurfaces:{id:string;finish:StudioRoom['floorFinish'];vertices:number[]}[];furniture:StudioFurniture[]};
export type StudioResolved = {roofFaces?:StudioRoofFace[];roofEdges?:StudioRoofEdge[];roofPatches?:StudioRoofPatch[];bays: StudioBay[]; pieces: StudioPiece[]; blockers: StudioBox[]; decks: StudioDeck[]; inactive: {id: string; reason: string}[]; accessRoutes?:{id:string;exit:StudioAnchor;layout:'straight'|'switchback';kind:'door'|'balcony'|'terrace'}[]; interiorLevels?:StudioInteriorLevel[];portals?:StudioPortal[];roof: number[]; roofNotes: string[]};
export const studioEnabled = () => typeof window !== 'undefined' && ['1'].includes(new URLSearchParams(window.location.search).get('cityStudio')??'');
