import { projectSnapshotSchema, type ProjectSnapshot } from './graphcore'

export const demoProjectSnapshot: ProjectSnapshot = projectSnapshotSchema.parse({
  workspace: {
    id: 'workspace-demo',
    name: 'Moonglass Studio',
    slug: 'moonglass-studio',
    role: 'owner',
  },
  project: {
    id: 'project-demo',
    name: 'Ashen Path',
    slug: 'ashen-path',
    summary: 'Narrative RPG system with shadow-token progression and graph-authored encounters.',
    visibility: 'private',
  },
  draft: {
    id: 'draft-main',
    name: 'Main Draft',
    version: 7,
    isPrimary: true,
    updatedAt: '2026-04-08T11:35:00.000Z',
  },
  definitions: [
    {
      id: 'def-item-lantern',
      key: 'item.lantern',
      kind: 'item',
      name: 'Wayfinder Lantern',
      summary: 'Core utility item used to unlock dark routes and scripted checks.',
      status: 'active',
      tags: ['equipment'],
      schemaVersion: 1,
      metadata: { rarity: 'uncommon' },
      llmHints: { authoringNotes: 'Utility progression item.' },
      assetRefs: [{ assetKey: 'image.lantern', usage: 'icon', required: false }],
      definitionData: { stackable: false },
      components: [
        {
          type: 'inventory',
          config: {
            startingItems: [],
            capacityFormula: null,
          },
        },
      ],
    },
    {
      id: 'def-item-shadow',
      key: 'token.shadow.gate_01',
      kind: 'item',
      name: 'Shadow Gate Token',
      summary: 'Hidden token used to mark the first gate of progression.',
      status: 'active',
      tags: ['shadow_token', 'hidden'],
      schemaVersion: 1,
      metadata: { visibility: 'system' },
      llmHints: { authoringNotes: 'Used by conditions, never shown to player.' },
      assetRefs: [],
      definitionData: { stackable: false, systemItem: true },
      components: [
        {
          type: 'progression',
          config: {
            tokenKeys: ['token.shadow.gate_01'],
            unlocks: ['location.moonwell'],
          },
        },
      ],
    },
    {
      id: 'def-stat-repute',
      key: 'stat.reputation',
      kind: 'stat',
      name: 'Reputation',
      summary: 'Tracks how the settlement responds to the player.',
      status: 'active',
      tags: ['social'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: { display: 'meter' },
      components: [
        {
          type: 'stat_block',
          config: {
            stats: [{ statKey: 'stat.reputation', base: 0, min: -50, max: 100 }],
          },
        },
      ],
    },
    {
      id: 'def-quest-bridge',
      key: 'quest.bridge_of_embers',
      kind: 'quest',
      name: 'Bridge of Embers',
      summary: 'Secure passage through the bridge and earn trust with the watch.',
      status: 'active',
      tags: ['main_quest'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: {},
      components: [
        {
          type: 'quest_state',
          config: {
            initialState: 'available',
            completionTokenKey: 'token.shadow.gate_01',
          },
        },
      ],
    },
    {
      id: 'def-char-watch',
      key: 'character.warden_sera',
      kind: 'character',
      name: 'Warden Sera',
      summary: 'Frontier captain who controls access to the bridge route.',
      status: 'active',
      tags: ['npc'],
      schemaVersion: 1,
      metadata: {},
      llmHints: { tone: 'severe but fair' },
      assetRefs: [
        { assetKey: 'image.sera', usage: 'portrait', required: false },
        { assetKey: 'audio.sera_voice', usage: 'voice', required: false },
      ],
      definitionData: {},
      components: [
        {
          type: 'dialogue_actor',
          config: {
            portraitAssetKey: 'image.sera',
            voiceAssetKey: 'audio.sera_voice',
            persona: 'Measured, suspicious, rewards proof over promises.',
          },
        },
      ],
    },
    {
      id: 'def-loc-moonwell',
      key: 'location.moonwell',
      kind: 'location',
      name: 'Moonwell Crossing',
      summary: 'A checkpoint location unlocked through shadow-token progression.',
      status: 'active',
      tags: ['hub'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: {},
      components: [
        {
          type: 'location_state',
          config: {
            region: 'frontier',
            isUnlockedByDefault: false,
          },
        },
      ],
    },
    {
      id: 'def-market-camp',
      key: 'market.bridge_camp',
      kind: 'market',
      name: 'Bridge Camp Exchange',
      summary: 'Supplies market available once the camp opens.',
      status: 'active',
      tags: ['vendor'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: {},
      components: [
        {
          type: 'pricing',
          config: {
            currencyItemKey: 'item.lantern',
            priceFormula: 'lookup:market.bridge_camp.base_price',
            stockRules: {
              restockIntervalMinutes: 60,
              maxStock: 8,
            },
          },
        },
      ],
    },
  ],
  graphs: [
    {
      id: 'graph-bridge',
      key: 'graph.bridge_intro',
      name: 'Bridge Intro',
      graphType: 'narrative_flow',
      summary: 'Opening dialogue with split path based on lantern possession.',
      entryNodeKey: 'start.bridge_intro',
      metadata: {},
      llmHints: { idealPrompt: 'Create a branching intro scene with trust gating.' },
      nodes: [
        {
          id: 'node-start',
          key: 'start.bridge_intro',
          type: 'start',
          title: 'Start',
          position: { x: 0, y: 120 },
          body: {
            text: null,
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: null,
          effects: [],
          ports: [{ id: 'out', label: 'Out', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-text-arrival',
          key: 'text.arrival',
          type: 'text',
          title: 'Arrival',
          position: { x: 260, y: 120 },
          body: {
            text: 'Warden Sera lowers her spear as the bridge groans in the mist.',
            imageAssetKey: 'image.sera',
            audioAssetKey: 'audio.scene.bridge_intro',
            choices: [],
          },
          condition: null,
          effects: [],
          ports: [{ id: 'out', label: 'Continue', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-condition-lantern',
          key: 'condition.has_lantern',
          type: 'condition',
          title: 'Check Lantern',
          position: { x: 540, y: 120 },
          body: {
            text: 'Does the player carry the lantern?',
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: { type: 'hasItem', itemKey: 'item.lantern', minQuantity: 1 },
          effects: [],
          ports: [
            { id: 'true', label: 'True', direction: 'output' },
            { id: 'false', label: 'False', direction: 'output' },
          ],
          metadata: {},
        },
        {
          id: 'node-choice-sera',
          key: 'choice.sera_offer',
          type: 'choice',
          title: 'Sera Offer',
          position: { x: 840, y: 24 },
          body: {
            text: 'Sera offers guarded passage if you accept her terms.',
            imageAssetKey: 'image.sera',
            audioAssetKey: null,
            choices: [
              { id: 'accept', label: 'Accept the escort.' },
              { id: 'decline', label: 'Decline and wait.' },
            ],
          },
          condition: null,
          effects: [{ type: 'setQuestState', questKey: 'quest.bridge_of_embers', state: 'active' }],
          ports: [{ id: 'out', label: 'Out', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-effect-token',
          key: 'effect.unlock_crossing',
          type: 'effect',
          title: 'Unlock Crossing',
          position: { x: 1140, y: 24 },
          body: {
            text: 'Grant the first progression token and unlock Moonwell.',
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: null,
          effects: [
            { type: 'grantToken', tokenKey: 'token.shadow.gate_01' },
            { type: 'unlockLocation', locationKey: 'location.moonwell' },
            { type: 'enqueueNarrative', graphKey: 'graph.bridge_intro' },
          ],
          ports: [{ id: 'out', label: 'Out', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-text-denied',
          key: 'text.denied',
          type: 'text',
          title: 'Denied Entry',
          position: { x: 840, y: 240 },
          body: {
            text: 'Without the lantern, the watch turns you back to the camp.',
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: null,
          effects: [{ type: 'addStat', statKey: 'stat.reputation', value: { type: 'literal', value: -2 } }],
          ports: [{ id: 'out', label: 'Out', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-end',
          key: 'end.bridge_intro',
          type: 'end',
          title: 'End',
          position: { x: 1420, y: 120 },
          body: {
            text: null,
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: null,
          effects: [],
          ports: [],
          metadata: {},
        },
      ],
      edges: [
        {
          id: 'edge-1',
          key: 'edge.start_to_arrival',
          source: { nodeKey: 'start.bridge_intro', portId: 'out' },
          target: { nodeKey: 'text.arrival', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-2',
          key: 'edge.arrival_to_check',
          source: { nodeKey: 'text.arrival', portId: 'out' },
          target: { nodeKey: 'condition.has_lantern', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-3',
          key: 'edge.check_true',
          source: { nodeKey: 'condition.has_lantern', portId: 'true' },
          target: { nodeKey: 'choice.sera_offer', portId: null },
          label: 'Lantern ready',
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-4',
          key: 'edge.check_false',
          source: { nodeKey: 'condition.has_lantern', portId: 'false' },
          target: { nodeKey: 'text.denied', portId: null },
          label: 'No lantern',
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-5',
          key: 'edge.choice_to_effect',
          source: { nodeKey: 'choice.sera_offer', portId: 'out' },
          target: { nodeKey: 'effect.unlock_crossing', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-6',
          key: 'edge.effect_to_end',
          source: { nodeKey: 'effect.unlock_crossing', portId: 'out' },
          target: { nodeKey: 'end.bridge_intro', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-7',
          key: 'edge.denied_to_end',
          source: { nodeKey: 'text.denied', portId: 'out' },
          target: { nodeKey: 'end.bridge_intro', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
      ],
    },
  ],
  assets: [
    {
      id: 'asset-lantern',
      key: 'image.lantern',
      name: 'Lantern Icon',
      kind: 'image',
      mimeType: 'image/png',
      storagePath: 'project-assets/demo/lantern.png',
      metadata: {},
      llmHints: {},
    },
    {
      id: 'asset-sera',
      key: 'image.sera',
      name: 'Sera Portrait',
      kind: 'image',
      mimeType: 'image/png',
      storagePath: 'project-assets/demo/sera.png',
      metadata: {},
      llmHints: {},
    },
    {
      id: 'asset-sera-voice',
      key: 'audio.sera_voice',
      name: 'Sera Voice',
      kind: 'audio',
      mimeType: 'audio/mpeg',
      storagePath: 'project-assets/demo/sera.mp3',
      metadata: { provider: 'elevenlabs' },
      llmHints: {},
    },
    {
      id: 'asset-scene-audio',
      key: 'audio.scene.bridge_intro',
      name: 'Bridge Scene Intro',
      kind: 'audio',
      mimeType: 'audio/mpeg',
      storagePath: 'project-assets/demo/bridge-intro.mp3',
      metadata: { provider: 'elevenlabs' },
      llmHints: {},
    },
  ],
  patchSets: [
    {
      id: 'patch-1',
      summary: 'Prompt proposes a market branch for the bridge camp.',
      prompt: 'Add a post-bridge market branch that sells ration packs once the gate token is granted.',
      status: 'proposed',
      operations: [
        {
          op: 'create_definition',
          kind: 'market',
          key: 'market.bridge_rations',
        },
        {
          op: 'create_node',
          graphKey: 'graph.bridge_intro',
          nodeKey: 'market.rations_offer',
        },
      ],
      diagnostics: ['Waiting for author review.'],
    },
  ],
  releases: [
    {
      id: 'release-1',
      version: '0.3.0',
      label: 'Bridge intro vertical slice',
      createdAt: '2026-04-07T18:10:00.000Z',
    },
  ],
})
