import { projectSnapshotSchema, type ProjectSnapshot } from './graphcore'
import { createDefaultGameSpec } from './presetCatalog'

export const demoProjectSnapshot: ProjectSnapshot = projectSnapshotSchema.parse({
  workspace: {
    id: 'workspace-demo',
    name: 'Moonglass Studio',
    slug: 'moonglass-studio',
    role: 'owner',
  },
  project: {
    id: 'project-demo',
    name: 'Ashen Path',
    slug: 'ashen-path',
    summary: 'Narrative RPG system with shadow-token progression, item archetypes, and graph-authored encounters.',
    visibility: 'private',
  },
  draft: {
    id: 'draft-main',
    name: 'Main Draft',
    version: 8,
    isPrimary: true,
    updatedAt: '2026-04-08T14:20:00.000Z',
    metadata: {
      gameSpec: createDefaultGameSpec(['pack.rpg_core']),
    },
  },
  gameSpec: createDefaultGameSpec(['pack.rpg_core']),
  archetypes: [
    {
      id: 'arch-consumable',
      key: 'item.consumable',
      name: 'Consumable',
      summary: 'Single-use item with immediate gameplay effects.',
      appliesToKind: 'item',
      iconAssetKey: 'image.potion_minor',
      metadata: { category: 'inventory' },
      llmHints: { promptStyle: 'Support healing, mana, buffs, and timed utility items.' },
      fields: [
        {
          id: 'field-consumable-description',
          key: 'description',
          label: 'Description',
          fieldType: 'long_text',
          description: 'Player-facing description in inventory and tooltips.',
          required: true,
          defaultValue: '',
          constraints: {},
          sortOrder: 0,
        },
        {
          id: 'field-consumable-heal',
          key: 'heal_amount',
          label: 'Heal Amount',
          fieldType: 'number',
          description: 'Amount of health restored on use.',
          required: false,
          defaultValue: 0,
          constraints: { min: 0, step: 1 },
          sortOrder: 1,
        },
        {
          id: 'field-consumable-cooldown',
          key: 'cooldown_seconds',
          label: 'Cooldown',
          fieldType: 'number',
          description: 'Seconds before the item can be reused.',
          required: false,
          defaultValue: 0,
          constraints: { min: 0, step: 1 },
          sortOrder: 2,
        },
        {
          id: 'field-consumable-rarity',
          key: 'rarity',
          label: 'Rarity',
          fieldType: 'enum',
          description: 'Loot tier and item coloration.',
          required: true,
          defaultValue: 'common',
          constraints: { options: ['common', 'uncommon', 'rare', 'epic'] },
          sortOrder: 3,
        },
      ],
    },
    {
      id: 'arch-utility',
      key: 'item.utility',
      name: 'Utility Item',
      summary: 'Reusable item that changes traversal or encounter options.',
      appliesToKind: 'item',
      iconAssetKey: 'image.lantern',
      metadata: {},
      llmHints: { promptStyle: 'Utility items often gate branches or dialogue checks.' },
      fields: [
        {
          id: 'field-utility-description',
          key: 'description',
          label: 'Description',
          fieldType: 'long_text',
          description: 'Short utility item description.',
          required: true,
          defaultValue: '',
          constraints: {},
          sortOrder: 0,
        },
        {
          id: 'field-utility-uses',
          key: 'max_uses',
          label: 'Max Uses',
          fieldType: 'number',
          description: 'Use count before the item breaks or depletes.',
          required: false,
          defaultValue: 0,
          constraints: { min: 0, step: 1 },
          sortOrder: 1,
        },
        {
          id: 'field-utility-equip',
          key: 'equip_slot',
          label: 'Equip Slot',
          fieldType: 'enum',
          description: 'Optional slot for equipment handling.',
          required: false,
          defaultValue: 'utility',
          constraints: { options: ['utility', 'hand', 'belt', 'trinket'] },
          sortOrder: 2,
        },
      ],
    },
    {
      id: 'arch-token',
      key: 'item.progression_token',
      name: 'Progression Token',
      summary: 'Hidden or system-facing item used by narrative and unlock conditions.',
      appliesToKind: 'item',
      iconAssetKey: 'image.shadow_token',
      metadata: { hiddenByDefault: true },
      llmHints: { promptStyle: 'Use for flags, unlocks, or shadow progression.' },
      fields: [
        {
          id: 'field-token-description',
          key: 'description',
          label: 'Description',
          fieldType: 'long_text',
          description: 'Internal description for designers.',
          required: true,
          defaultValue: '',
          constraints: {},
          sortOrder: 0,
        },
        {
          id: 'field-token-hidden',
          key: 'is_hidden',
          label: 'Hidden',
          fieldType: 'boolean',
          description: 'Whether the token is exposed to players.',
          required: true,
          defaultValue: true,
          constraints: {},
          sortOrder: 1,
        },
        {
          id: 'field-token-unlock',
          key: 'unlocks_location',
          label: 'Unlocks Location',
          fieldType: 'definition_ref',
          description: 'Optional location or system node unlocked by this token.',
          required: false,
          defaultValue: null,
          constraints: { allowedKinds: ['location'] },
          sortOrder: 2,
        },
      ],
    },
    {
      id: 'arch-currency',
      key: 'item.currency',
      name: 'Currency',
      summary: 'Economy token used for trades and vendors.',
      appliesToKind: 'item',
      iconAssetKey: null,
      metadata: { category: 'currency' },
      llmHints: {},
      fields: [
        {
          id: 'field-currency-description',
          key: 'description',
          label: 'Description',
          fieldType: 'long_text',
          description: 'Short player-facing description.',
          required: true,
          defaultValue: '',
          constraints: {},
          sortOrder: 0,
        },
        {
          id: 'field-currency-symbol',
          key: 'symbol',
          label: 'Symbol',
          fieldType: 'text',
          description: 'Displayed short symbol.',
          required: false,
          defaultValue: '',
          constraints: {},
          sortOrder: 1,
        },
      ],
    },
    {
      id: 'arch-character-questgiver',
      key: 'character.npc_questgiver',
      name: 'Quest Giver NPC',
      summary: 'Narrative NPC that anchors quest and dialogue flows.',
      appliesToKind: 'character',
      iconAssetKey: 'image.sera',
      metadata: { controlledBy: 'ai' },
      llmHints: {},
      fields: [
        {
          id: 'field-character-role',
          key: 'role',
          label: 'Role',
          fieldType: 'text',
          description: 'Primary role label.',
          required: false,
          defaultValue: 'questgiver',
          constraints: {},
          sortOrder: 0,
        },
      ],
    },
    {
      id: 'arch-ability-spell',
      key: 'ability.active_spell',
      name: 'Active Spell',
      summary: 'Triggered magical ability with optional resource cost.',
      appliesToKind: 'ability',
      iconAssetKey: null,
      metadata: {},
      llmHints: {},
      fields: [
        {
          id: 'field-ability-description',
          key: 'description',
          label: 'Description',
          fieldType: 'long_text',
          description: 'Short ability description.',
          required: true,
          defaultValue: '',
          constraints: {},
          sortOrder: 0,
        },
        {
          id: 'field-ability-element',
          key: 'element',
          label: 'Element',
          fieldType: 'enum',
          description: 'Damage or spell element.',
          required: false,
          defaultValue: 'fire',
          constraints: { options: ['fire', 'ice', 'lightning', 'shadow', 'holy'] },
          sortOrder: 1,
        },
      ],
    },
  ],
  definitions: [
    {
      id: 'def-currency-gold',
      key: 'currency.gold',
      kind: 'item',
      name: 'Gold',
      summary: 'Default market currency.',
      status: 'active',
      iconAssetKey: null,
      archetypeKey: 'item.currency',
      tags: ['currency'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: { stackable: true },
      fieldValues: [
        { fieldKey: 'description', value: 'Stamped frontier coinage used in trade.' },
        { fieldKey: 'symbol', value: 'G' },
      ],
      customFields: [],
      components: [],
    },
    {
      id: 'def-item-lantern',
      key: 'item.lantern',
      kind: 'item',
      name: 'Wayfinder Lantern',
      summary: 'Core utility item used to unlock dark routes and scripted checks.',
      status: 'active',
      iconAssetKey: 'image.lantern',
      archetypeKey: 'item.utility',
      tags: ['equipment'],
      schemaVersion: 1,
      metadata: { rarity: 'uncommon' },
      llmHints: { authoringNotes: 'Utility progression item.' },
      assetRefs: [{ assetKey: 'image.lantern', usage: 'icon', required: false }],
      definitionData: { stackable: false },
      fieldValues: [
        { fieldKey: 'description', value: 'A warded lantern that reveals hidden routes and lets the watch trust your passage.' },
        { fieldKey: 'max_uses', value: 0 },
        { fieldKey: 'equip_slot', value: 'hand' },
      ],
      customFields: [],
      components: [
        {
          type: 'inventory',
          config: {
            startingItems: [],
            capacityFormula: null,
          },
        },
      ],
    },
    {
      id: 'def-item-potion',
      key: 'item.potion_minor_healing',
      kind: 'item',
      name: 'Minor Healing Potion',
      summary: 'A basic restorative for short encounters and camp preparation.',
      status: 'active',
      iconAssetKey: 'image.potion_minor',
      archetypeKey: 'item.consumable',
      tags: ['consumable', 'restorative'],
      schemaVersion: 1,
      metadata: {},
      llmHints: { authoringNotes: 'Use as the default healing item in early progression.' },
      assetRefs: [{ assetKey: 'image.potion_minor', usage: 'icon', required: false }],
      definitionData: { stackable: true },
      fieldValues: [
        { fieldKey: 'description', value: 'Restores a measured amount of health without adding a cooldown tax.' },
        { fieldKey: 'heal_amount', value: 25 },
        { fieldKey: 'cooldown_seconds', value: 0 },
        { fieldKey: 'rarity', value: 'common' },
        { fieldKey: 'price_gold', value: 12 },
      ],
      customFields: [
        {
          id: 'field-potion-price',
          key: 'price_gold',
          label: 'Price (Gold)',
          fieldType: 'number',
          description: 'Local market price override for this potion.',
          required: false,
          defaultValue: 10,
          constraints: { min: 0, step: 1 },
          sortOrder: 100,
        },
      ],
      components: [],
    },
    {
      id: 'def-item-shadow',
      key: 'token.shadow.gate_01',
      kind: 'item',
      name: 'Shadow Gate Token',
      summary: 'Hidden token used to mark the first gate of progression.',
      status: 'active',
      iconAssetKey: 'image.shadow_token',
      archetypeKey: 'item.progression_token',
      tags: ['shadow_token', 'hidden'],
      schemaVersion: 1,
      metadata: { visibility: 'system' },
      llmHints: { authoringNotes: 'Used by conditions, never shown to player.' },
      assetRefs: [{ assetKey: 'image.shadow_token', usage: 'icon', required: false }],
      definitionData: { stackable: false, systemItem: true },
      fieldValues: [
        { fieldKey: 'description', value: 'First hidden progression marker for the Moonwell route.' },
        { fieldKey: 'is_hidden', value: true },
        { fieldKey: 'unlocks_location', value: 'location.moonwell' },
      ],
      customFields: [],
      components: [
        {
          type: 'progression',
          config: {
            tokenKeys: ['token.shadow.gate_01'],
            unlocks: ['location.moonwell'],
          },
        },
      ],
    },
    {
      id: 'def-stat-repute',
      key: 'stat.reputation',
      kind: 'stat',
      name: 'Reputation',
      summary: 'Tracks how the settlement responds to the player.',
      status: 'active',
      iconAssetKey: null,
      archetypeKey: null,
      tags: ['social'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: { display: 'meter' },
      fieldValues: [],
      customFields: [],
      components: [
        {
          type: 'stat_block',
          config: {
            stats: [{ statKey: 'stat.reputation', base: 0, min: -50, max: 100 }],
          },
        },
      ],
    },
    {
      id: 'def-quest-bridge',
      key: 'quest.bridge_of_embers',
      kind: 'quest',
      name: 'Bridge of Embers',
      summary: 'Secure passage through the bridge and earn trust with the watch.',
      status: 'active',
      iconAssetKey: null,
      archetypeKey: null,
      tags: ['main_quest'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: {},
      fieldValues: [],
      customFields: [],
      components: [
        {
          type: 'quest_state',
          config: {
            initialState: 'available',
            completionTokenKey: 'token.shadow.gate_01',
          },
        },
      ],
    },
    {
      id: 'def-ability-fireball',
      key: 'ability.fireball',
      kind: 'ability',
      name: 'Fireball',
      summary: 'Starter offensive spell for caster characters.',
      status: 'active',
      iconAssetKey: null,
      archetypeKey: 'ability.active_spell',
      tags: ['starter_spell'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: {},
      fieldValues: [
        { fieldKey: 'description', value: 'Hurl a fast fire projectile at an enemy.' },
        { fieldKey: 'element', value: 'fire' },
      ],
      customFields: [],
      components: [
        {
          type: 'ability_profile',
          config: {
            targetMode: 'enemy',
            cooldownSeconds: 6,
            castTimeSeconds: 0.4,
            resourceCostItemKey: null,
            resourceCostQuantity: 0,
            effectOps: [],
          },
        },
      ],
    },
    {
      id: 'def-char-watch',
      key: 'character.warden_sera',
      kind: 'character',
      name: 'Warden Sera',
      summary: 'Frontier captain who controls access to the bridge route.',
      status: 'active',
      iconAssetKey: 'image.sera',
      archetypeKey: 'character.npc_questgiver',
      tags: ['npc'],
      schemaVersion: 1,
      metadata: { controlledBy: 'ai' },
      llmHints: { tone: 'severe but fair' },
      assetRefs: [
        { assetKey: 'image.sera', usage: 'portrait', required: false },
        { assetKey: 'audio.sera_voice', usage: 'voice', required: false },
      ],
      definitionData: {},
      fieldValues: [],
      customFields: [],
      components: [
        {
          type: 'inventory',
          config: {
            startingItems: [],
            capacityFormula: null,
          },
        },
        {
          type: 'ability_loadout',
          config: {
            entries: [
              {
                abilityKey: 'ability.fireball',
                slotKey: 'warning_spell',
                inputBinding: null,
                cooldownGroup: 'dialogue_threat',
                unlockTokenKey: null,
              },
            ],
          },
        },
        {
          type: 'dialogue_actor',
          config: {
            portraitAssetKey: 'image.sera',
            voiceAssetKey: 'audio.sera_voice',
            persona: 'Measured, suspicious, rewards proof over promises.',
          },
        },
        {
          type: 'render_3d_binding',
          config: {
            primaryMeshAssetKey: null,
            previewImageAssetKey: 'image.sera',
            generationPrompt: 'Armored frontier warden with a practical silhouette, layered cloak, and grounded heroic proportions.',
            generationStyle: 'stylized realism',
          },
        },
      ],
    },
    {
      id: 'def-loc-moonwell',
      key: 'location.moonwell',
      kind: 'location',
      name: 'Moonwell Crossing',
      summary: 'A checkpoint location unlocked through shadow-token progression.',
      status: 'active',
      iconAssetKey: null,
      archetypeKey: null,
      tags: ['hub'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: {},
      fieldValues: [],
      customFields: [],
      components: [
        {
          type: 'location_state',
          config: {
            region: 'frontier',
            isUnlockedByDefault: false,
            linkedGraphKeys: ['graph.bridge_intro'],
            linkedMarketKeys: ['market.bridge_camp'],
            unlockTokenKey: 'token.shadow.gate_01',
          },
        },
      ],
    },
    {
      id: 'def-market-camp',
      key: 'market.bridge_camp',
      kind: 'market',
      name: 'Bridge Camp Exchange',
      summary: 'Supplies market available once the camp opens.',
      status: 'active',
      iconAssetKey: null,
      archetypeKey: null,
      tags: ['vendor'],
      schemaVersion: 1,
      metadata: {},
      llmHints: {},
      assetRefs: [],
      definitionData: {},
      fieldValues: [],
      customFields: [],
      components: [
        {
          type: 'market_inventory',
          config: {
            trades: [
              {
                id: 'trade-minor-healing',
                offerItemKey: 'item.potion_minor_healing',
                offerQuantity: 1,
                costItemKey: 'currency.gold',
                costQuantity: 12,
                unlockTokenKey: null,
              },
            ],
          },
        },
      ],
    },
  ],
  graphs: [
    {
      id: 'graph-bridge',
      key: 'graph.bridge_intro',
      name: 'Bridge Intro',
      graphType: 'narrative_flow',
      summary: 'Opening dialogue with split path based on lantern possession.',
      entryNodeKey: 'start.bridge_intro',
      metadata: {},
      llmHints: { idealPrompt: 'Create a branching intro scene with trust gating.' },
      nodes: [
        {
          id: 'node-start',
          key: 'start.bridge_intro',
          type: 'start',
          title: 'Start',
          position: { x: 0, y: 120 },
          body: {
            text: null,
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: null,
          effects: [],
          ports: [{ id: 'out', label: 'Out', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-text-arrival',
          key: 'text.arrival',
          type: 'text',
          title: 'Arrival',
          position: { x: 260, y: 120 },
          body: {
            text: 'Warden Sera lowers her spear as the bridge groans in the mist.',
            imageAssetKey: 'image.sera',
            audioAssetKey: 'audio.scene.bridge_intro',
            choices: [],
          },
          condition: null,
          effects: [],
          ports: [{ id: 'out', label: 'Continue', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-condition-lantern',
          key: 'condition.has_lantern',
          type: 'condition',
          title: 'Check Lantern',
          position: { x: 540, y: 120 },
          body: {
            text: 'Does the player carry the lantern?',
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: { type: 'hasItem', itemKey: 'item.lantern', minQuantity: 1 },
          effects: [],
          ports: [
            { id: 'true', label: 'True', direction: 'output' },
            { id: 'false', label: 'False', direction: 'output' },
          ],
          metadata: {},
        },
        {
          id: 'node-choice-sera',
          key: 'choice.sera_offer',
          type: 'choice',
          title: 'Sera Offer',
          position: { x: 840, y: 24 },
          body: {
            text: 'Sera offers guarded passage if you accept her terms.',
            imageAssetKey: 'image.sera',
            audioAssetKey: null,
            choices: [
              { id: 'accept', label: 'Accept the escort.' },
              { id: 'decline', label: 'Decline and wait.' },
            ],
          },
          condition: null,
          effects: [{ type: 'setQuestState', questKey: 'quest.bridge_of_embers', state: 'active' }],
          ports: [{ id: 'out', label: 'Out', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-effect-token',
          key: 'effect.unlock_crossing',
          type: 'effect',
          title: 'Unlock Crossing',
          position: { x: 1140, y: 24 },
          body: {
            text: 'Grant the first progression token and unlock Moonwell.',
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: null,
          effects: [
            { type: 'grantToken', tokenKey: 'token.shadow.gate_01' },
            { type: 'unlockLocation', locationKey: 'location.moonwell' },
            { type: 'enqueueNarrative', graphKey: 'graph.bridge_intro' },
          ],
          ports: [{ id: 'out', label: 'Out', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-text-denied',
          key: 'text.denied',
          type: 'text',
          title: 'Denied Entry',
          position: { x: 840, y: 240 },
          body: {
            text: 'Without the lantern, the watch turns you back to the camp.',
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: null,
          effects: [{ type: 'addStat', statKey: 'stat.reputation', value: { type: 'literal', value: -2 } }],
          ports: [{ id: 'out', label: 'Out', direction: 'output' }],
          metadata: {},
        },
        {
          id: 'node-end',
          key: 'end.bridge_intro',
          type: 'end',
          title: 'End',
          position: { x: 1420, y: 120 },
          body: {
            text: null,
            imageAssetKey: null,
            audioAssetKey: null,
            choices: [],
          },
          condition: null,
          effects: [],
          ports: [],
          metadata: {},
        },
      ],
      edges: [
        {
          id: 'edge-1',
          key: 'edge.start_to_arrival',
          source: { nodeKey: 'start.bridge_intro', portId: 'out' },
          target: { nodeKey: 'text.arrival', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-2',
          key: 'edge.arrival_to_check',
          source: { nodeKey: 'text.arrival', portId: 'out' },
          target: { nodeKey: 'condition.has_lantern', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-3',
          key: 'edge.check_true',
          source: { nodeKey: 'condition.has_lantern', portId: 'true' },
          target: { nodeKey: 'choice.sera_offer', portId: null },
          label: 'Lantern ready',
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-4',
          key: 'edge.check_false',
          source: { nodeKey: 'condition.has_lantern', portId: 'false' },
          target: { nodeKey: 'text.denied', portId: null },
          label: 'No lantern',
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-5',
          key: 'edge.choice_to_effect',
          source: { nodeKey: 'choice.sera_offer', portId: 'out' },
          target: { nodeKey: 'effect.unlock_crossing', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-6',
          key: 'edge.effect_to_end',
          source: { nodeKey: 'effect.unlock_crossing', portId: 'out' },
          target: { nodeKey: 'end.bridge_intro', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
        {
          id: 'edge-7',
          key: 'edge.denied_to_end',
          source: { nodeKey: 'text.denied', portId: 'out' },
          target: { nodeKey: 'end.bridge_intro', portId: null },
          label: null,
          condition: null,
          metadata: {},
        },
      ],
    },
  ],
  assets: [
    {
      id: 'asset-lantern',
      key: 'image.lantern',
      name: 'Lantern Icon',
      kind: 'image',
      mimeType: 'image/png',
      storagePath: 'project-assets/demo/lantern.png',
      metadata: { previewUrl: 'https://images.unsplash.com/photo-1515548217836-7c2f2e2b4f90?auto=format&fit=crop&w=160&q=80' },
      llmHints: {},
    },
    {
      id: 'asset-potion',
      key: 'image.potion_minor',
      name: 'Minor Potion Icon',
      kind: 'image',
      mimeType: 'image/png',
      storagePath: 'project-assets/demo/potion-minor.png',
      metadata: { previewUrl: 'https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=160&q=80' },
      llmHints: {},
    },
    {
      id: 'asset-shadow-token',
      key: 'image.shadow_token',
      name: 'Shadow Token Sigil',
      kind: 'image',
      mimeType: 'image/png',
      storagePath: 'project-assets/demo/shadow-token.png',
      metadata: { previewUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=160&q=80' },
      llmHints: {},
    },
    {
      id: 'asset-sera',
      key: 'image.sera',
      name: 'Sera Portrait',
      kind: 'image',
      mimeType: 'image/png',
      storagePath: 'project-assets/demo/sera.png',
      metadata: { previewUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80' },
      llmHints: {},
    },
    {
      id: 'asset-sera-voice',
      key: 'audio.sera_voice',
      name: 'Sera Voice',
      kind: 'audio',
      mimeType: 'audio/mpeg',
      storagePath: 'project-assets/demo/sera.mp3',
      metadata: { provider: 'elevenlabs' },
      llmHints: {},
    },
    {
      id: 'asset-scene-audio',
      key: 'audio.scene.bridge_intro',
      name: 'Bridge Scene Intro',
      kind: 'audio',
      mimeType: 'audio/mpeg',
      storagePath: 'project-assets/demo/bridge-intro.mp3',
      metadata: { provider: 'elevenlabs' },
      llmHints: {},
    },
  ],
  patchSets: [
    {
      id: 'patch-1',
      summary: 'Prompt proposes a stronger healing consumable archetype variant.',
      prompt: 'Add a stronger healing potion item that restores 60 health and costs more gold.',
      status: 'proposed',
      operations: [
        {
          op: 'create_definition',
          kind: 'item',
          key: 'item.potion_major_healing',
        },
        {
          op: 'set_archetype',
          key: 'item.potion_major_healing',
          archetypeKey: 'item.consumable',
        },
        {
          op: 'set_field_value',
          key: 'item.potion_major_healing',
          fieldKey: 'heal_amount',
          value: 60,
        },
      ],
      diagnostics: ['Waiting for author review.'],
    },
  ],
  releases: [
    {
      id: 'release-1',
      version: '0.4.0',
      label: 'Items and archetypes vertical slice',
      createdAt: '2026-04-08T13:10:00.000Z',
    },
  ],
})
