import type { GameSpec } from './graphcore'
import { PRESET_CATALOG_VERSION, createDefaultGameSpec, expandPackPresetIds } from './presetCatalog'

export type GameArchetype = {
  id: string
  label: string
  description: string
  promptHint: string
  defaultPackIds: string[]
  theme: Partial<GameSpec['theme']>
  systems: Partial<GameSpec['systems']>
  contentScope: Partial<GameSpec['contentScope']>
  starterGraphs?: string[]
}

const gameArchetypes: GameArchetype[] = [
  { id: 'rpg', label: 'RPG', description: 'Quest-driven progression, roster growth, vendors, and hub spaces.', promptHint: 'Party, progression, gear, questing.', defaultPackIds: ['pack.rpg_core'], theme: { genre: 'fantasy_rpg', tone: 'heroic', playerFantasy: 'adventurer', namingStyle: 'classic_fantasy' }, systems: { progressionStyle: 'branching', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'slots', economyStyle: 'gold' }, contentScope: { items: 'heavy', characters: 'heavy', abilities: 'medium', locations: 'medium', markets: 'light', quests: 'medium', graphs: 'medium' }, starterGraphs: ['graph.starting_hub_loop', 'graph.quest_offer'] },
  { id: 'action_rpg', label: 'Action RPG', description: 'Realtime combat, loot, hubs, and fast enemy archetypes.', promptHint: 'Builds, combat verbs, enemies, loot.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'fantasy_rpg', tone: 'heroic', playerFantasy: 'hunter', namingStyle: 'classic_fantasy' }, systems: { progressionStyle: 'branching', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'slots', economyStyle: 'gold' }, contentScope: { items: 'heavy', characters: 'heavy', abilities: 'heavy', locations: 'medium', markets: 'light', quests: 'light', graphs: 'light' }, starterGraphs: ['graph.basic_combat_encounter'] },
  { id: 'jrpg', label: 'JRPG', description: 'Party-forward progression with towns, dungeons, and authored story beats.', promptHint: 'Party roles, towns, dungeons, authored arcs.', defaultPackIds: ['pack.rpg_core'], theme: { genre: 'fantasy_rpg', tone: 'heroic', playerFantasy: 'chosen_hero', namingStyle: 'mythic_dense' }, systems: { progressionStyle: 'linear', combatStyle: 'turn_based', inputStyle: 'party_commands', inventoryStyle: 'slots', economyStyle: 'gold' }, contentScope: { items: 'medium', characters: 'heavy', abilities: 'medium', locations: 'medium', markets: 'light', quests: 'medium', graphs: 'heavy' } },
  { id: 'tactical_rpg', label: 'Tactical RPG', description: 'Squad encounters, abilities, and mission graphs.', promptHint: 'Squad tactics, missions, encounter structure.', defaultPackIds: ['pack.rpg_core'], theme: { genre: 'fantasy_rpg', tone: 'grounded', playerFantasy: 'commander', namingStyle: 'classic_fantasy' }, systems: { progressionStyle: 'branching', combatStyle: 'turn_based', inputStyle: 'party_commands', inventoryStyle: 'slots', economyStyle: 'gold' }, contentScope: { items: 'medium', characters: 'heavy', abilities: 'heavy', locations: 'light', markets: 'none', quests: 'medium', graphs: 'medium' } },
  { id: 'roguelite', label: 'Rogue-lite', description: 'Repeatable runs, meta progression, and compact content loops.', promptHint: 'Runs, meta upgrades, combat verbs, unlocks.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'fantasy_rpg', tone: 'grim', playerFantasy: 'survivor', namingStyle: 'minimalist' }, systems: { progressionStyle: 'hub_and_spoke', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'stacked', economyStyle: 'energy' }, contentScope: { items: 'medium', characters: 'medium', abilities: 'heavy', locations: 'light', markets: 'none', quests: 'none', graphs: 'light' } },
  { id: 'roguelike', label: 'Rogue-like', description: 'Hard reset runs, minimal economy, and system-heavy encounter loops.', promptHint: 'Run structure, permadeath, system encounters.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'fantasy_rpg', tone: 'grim', playerFantasy: 'wanderer', namingStyle: 'minimalist' }, systems: { progressionStyle: 'open', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'stacked', economyStyle: 'none' }, contentScope: { items: 'medium', characters: 'medium', abilities: 'medium', locations: 'light', markets: 'none', quests: 'none', graphs: 'light' } },
  { id: 'survival', label: 'Survival', description: 'Resource pressure, shelters, regions, and unlock tokens.', promptHint: 'Scarcity, shelter, crafting, regions.', defaultPackIds: ['pack.survival'], theme: { genre: 'survival_adventure', tone: 'grounded', playerFantasy: 'survivor', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'open', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'weight', economyStyle: 'barter' }, contentScope: { items: 'heavy', characters: 'light', abilities: 'light', locations: 'heavy', markets: 'light', quests: 'light', graphs: 'medium' } },
  { id: 'survival_craft', label: 'Survival Craft', description: 'Crafting-heavy survival with regions, vendors, and resource loops.', promptHint: 'Gather, craft, build, unlock regions.', defaultPackIds: ['pack.survival'], theme: { genre: 'survival_adventure', tone: 'grounded', playerFantasy: 'builder', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'open', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'weight', economyStyle: 'barter' }, contentScope: { items: 'heavy', characters: 'light', abilities: 'light', locations: 'heavy', markets: 'medium', quests: 'light', graphs: 'medium' } },
  { id: 'rts', label: 'RTS', description: 'Unit production, command structure, and systemic encounter graphs.', promptHint: 'Factions, units, tech, objectives.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'sci_fi_action', tone: 'grounded', playerFantasy: 'commander', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'branching', combatStyle: 'real_time', inputStyle: 'party_commands', inventoryStyle: 'none', economyStyle: 'energy' }, contentScope: { items: 'light', characters: 'medium', abilities: 'medium', locations: 'medium', markets: 'none', quests: 'light', graphs: 'medium' } },
  { id: 'grand_strategy', label: 'Grand Strategy', description: 'Faction progression, map regions, and macro systems.', promptHint: 'Factions, diplomacy, resources, regions.', defaultPackIds: ['pack.survival'], theme: { genre: 'historical_strategy', tone: 'grounded', playerFantasy: 'ruler', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'open', combatStyle: 'hybrid', inputStyle: 'party_commands', inventoryStyle: 'none', economyStyle: 'gold' }, contentScope: { items: 'light', characters: 'light', abilities: 'light', locations: 'heavy', markets: 'medium', quests: 'none', graphs: 'medium' } },
  { id: '4x', label: '4X', description: 'Explore, expand, exploit, exterminate with region and economy layers.', promptHint: 'Empires, expansion, tech, regions.', defaultPackIds: ['pack.survival'], theme: { genre: 'sci_fi_strategy', tone: 'heroic', playerFantasy: 'empire_builder', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'open', combatStyle: 'hybrid', inputStyle: 'party_commands', inventoryStyle: 'none', economyStyle: 'energy' }, contentScope: { items: 'light', characters: 'light', abilities: 'light', locations: 'heavy', markets: 'medium', quests: 'none', graphs: 'medium' } },
  { id: 'city_builder', label: 'City Builder', description: 'Economic loops, location layers, and population-facing systems.', promptHint: 'Districts, trade, growth, unlocks.', defaultPackIds: ['pack.survival'], theme: { genre: 'management_sim', tone: 'grounded', playerFantasy: 'planner', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'branching', combatStyle: 'none', inputStyle: 'party_commands', inventoryStyle: 'none', economyStyle: 'gold' }, contentScope: { items: 'medium', characters: 'none', abilities: 'none', locations: 'heavy', markets: 'heavy', quests: 'none', graphs: 'light' } },
  { id: 'colony_sim', label: 'Colony Sim', description: 'Characters, needs, locations, and layered resource loops.', promptHint: 'Settlers, tasks, needs, supply chains.', defaultPackIds: ['pack.survival'], theme: { genre: 'management_sim', tone: 'grounded', playerFantasy: 'overseer', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'branching', combatStyle: 'hybrid', inputStyle: 'party_commands', inventoryStyle: 'none', economyStyle: 'barter' }, contentScope: { items: 'heavy', characters: 'medium', abilities: 'light', locations: 'heavy', markets: 'medium', quests: 'none', graphs: 'light' } },
  { id: 'management_sim', label: 'Management Sim', description: 'Process-driven systems with clear inventories, workers, and markets.', promptHint: 'Operations, workers, trade, progression.', defaultPackIds: ['pack.survival'], theme: { genre: 'management_sim', tone: 'clean', playerFantasy: 'operator', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'linear', combatStyle: 'none', inputStyle: 'party_commands', inventoryStyle: 'stacked', economyStyle: 'gold' }, contentScope: { items: 'heavy', characters: 'light', abilities: 'none', locations: 'medium', markets: 'heavy', quests: 'none', graphs: 'light' } },
  { id: 'farming_sim', label: 'Farming Sim', description: 'Peaceful loops around items, locations, markets, and NPCs.', promptHint: 'Crops, vendors, village, gentle progression.', defaultPackIds: ['pack.narrative_adventure'], theme: { genre: 'life_sim', tone: 'gentle', playerFantasy: 'caretaker', namingStyle: 'classic_fantasy' }, systems: { progressionStyle: 'hub_and_spoke', combatStyle: 'none', inputStyle: 'direct_control', inventoryStyle: 'stacked', economyStyle: 'gold' }, contentScope: { items: 'heavy', characters: 'medium', abilities: 'none', locations: 'medium', markets: 'heavy', quests: 'light', graphs: 'light' } },
  { id: 'life_sim', label: 'Life Sim', description: 'NPCs, schedules, soft goals, and location-rich authored spaces.', promptHint: 'People, places, social loops, inventory.', defaultPackIds: ['pack.narrative_adventure'], theme: { genre: 'life_sim', tone: 'gentle', playerFantasy: 'local_resident', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'open', combatStyle: 'none', inputStyle: 'direct_control', inventoryStyle: 'stacked', economyStyle: 'gold' }, contentScope: { items: 'medium', characters: 'heavy', abilities: 'none', locations: 'heavy', markets: 'medium', quests: 'light', graphs: 'medium' } },
  { id: 'narrative_adventure', label: 'Narrative Adventure', description: 'Story-forward graphs, locations, NPCs, and light item gating.', promptHint: 'Scenes, conversations, quest beats, branches.', defaultPackIds: ['pack.narrative_adventure'], theme: { genre: 'narrative_mystery', tone: 'mysterious', playerFantasy: 'investigator', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'linear', combatStyle: 'none', inputStyle: 'dialogue_choice', inventoryStyle: 'slots', economyStyle: 'none' }, contentScope: { items: 'light', characters: 'heavy', abilities: 'none', locations: 'medium', markets: 'none', quests: 'medium', graphs: 'heavy' } },
  { id: 'visual_novel', label: 'Visual Novel', description: 'Branching scenes, characters, and narrative state.', promptHint: 'Routes, cast, choices, flags.', defaultPackIds: ['pack.narrative_adventure'], theme: { genre: 'narrative_mystery', tone: 'mysterious', playerFantasy: 'protagonist', namingStyle: 'minimalist' }, systems: { progressionStyle: 'branching', combatStyle: 'none', inputStyle: 'dialogue_choice', inventoryStyle: 'none', economyStyle: 'none' }, contentScope: { items: 'none', characters: 'heavy', abilities: 'none', locations: 'light', markets: 'none', quests: 'light', graphs: 'heavy' } },
  { id: 'detective_mystery', label: 'Detective / Mystery', description: 'Evidence items, suspects, locations, and clue graphs.', promptHint: 'Case structure, suspects, clues, reveals.', defaultPackIds: ['pack.narrative_adventure'], theme: { genre: 'narrative_mystery', tone: 'mysterious', playerFantasy: 'detective', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'branching', combatStyle: 'none', inputStyle: 'dialogue_choice', inventoryStyle: 'slots', economyStyle: 'none' }, contentScope: { items: 'medium', characters: 'heavy', abilities: 'none', locations: 'medium', markets: 'none', quests: 'medium', graphs: 'heavy' } },
  { id: 'immersive_sim', label: 'Immersive Sim', description: 'Systemic verbs, characters, routes, and layered spaces.', promptHint: 'Systemic abilities, routes, factions, spaces.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'sci_fi_action', tone: 'grounded', playerFantasy: 'operative', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'branching', combatStyle: 'hybrid', inputStyle: 'direct_control', inventoryStyle: 'slots', economyStyle: 'gold' }, contentScope: { items: 'medium', characters: 'medium', abilities: 'heavy', locations: 'heavy', markets: 'light', quests: 'light', graphs: 'medium' } },
  { id: 'dungeon_crawler', label: 'Dungeon Crawler', description: 'Combat, loot, traversal, and encounter chains.', promptHint: 'Rooms, monsters, loot, progression.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'fantasy_rpg', tone: 'grim', playerFantasy: 'delver', namingStyle: 'classic_fantasy' }, systems: { progressionStyle: 'linear', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'slots', economyStyle: 'gold' }, contentScope: { items: 'heavy', characters: 'medium', abilities: 'heavy', locations: 'medium', markets: 'light', quests: 'light', graphs: 'medium' } },
  { id: 'extraction', label: 'Extraction', description: 'High-risk runs, scarce items, and route-oriented spaces.', promptHint: 'Loadouts, loot, exits, hostile zones.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'sci_fi_action', tone: 'grim', playerFantasy: 'raider', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'hub_and_spoke', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'weight', economyStyle: 'gold' }, contentScope: { items: 'heavy', characters: 'medium', abilities: 'medium', locations: 'medium', markets: 'light', quests: 'none', graphs: 'light' } },
  { id: 'metroidvania', label: 'Metroidvania', description: 'Ability gating, regions, and tightly linked progression graphs.', promptHint: 'Traversal abilities, region gates, backtracking.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'fantasy_rpg', tone: 'mysterious', playerFantasy: 'explorer', namingStyle: 'mythic_dense' }, systems: { progressionStyle: 'branching', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'slots', economyStyle: 'none' }, contentScope: { items: 'medium', characters: 'medium', abilities: 'heavy', locations: 'heavy', markets: 'none', quests: 'light', graphs: 'medium' } },
  { id: 'platformer', label: 'Platformer', description: 'Movement-focused progression with light systems and ability gates.', promptHint: 'Movement verbs, pickups, route gates.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'arcade_action', tone: 'heroic', playerFantasy: 'runner', namingStyle: 'minimalist' }, systems: { progressionStyle: 'linear', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'none', economyStyle: 'none' }, contentScope: { items: 'light', characters: 'light', abilities: 'medium', locations: 'medium', markets: 'none', quests: 'none', graphs: 'light' } },
  { id: 'shooter', label: 'Shooter', description: 'Weapons, enemies, encounters, and direct-control pacing.', promptHint: 'Weapons, enemies, encounter flows, arenas.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'sci_fi_action', tone: 'grounded', playerFantasy: 'soldier', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'linear', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'slots', economyStyle: 'energy' }, contentScope: { items: 'medium', characters: 'medium', abilities: 'medium', locations: 'light', markets: 'none', quests: 'none', graphs: 'light' } },
  { id: 'twin_stick_shooter', label: 'Twin-Stick Shooter', description: 'Arcade combat loops with abilities and compact progression.', promptHint: 'Combat verbs, waves, upgrades, arenas.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'arcade_action', tone: 'heroic', playerFantasy: 'ace_pilot', namingStyle: 'minimalist' }, systems: { progressionStyle: 'hub_and_spoke', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'none', economyStyle: 'energy' }, contentScope: { items: 'light', characters: 'light', abilities: 'heavy', locations: 'light', markets: 'none', quests: 'none', graphs: 'light' } },
  { id: 'auto_battler', label: 'Auto-Battler', description: 'Roster, synergies, currencies, and economy-led upgrades.', promptHint: 'Units, synergies, tiers, economy.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'strategy_battler', tone: 'heroic', playerFantasy: 'strategist', namingStyle: 'clean_modern' }, systems: { progressionStyle: 'branching', combatStyle: 'none', inputStyle: 'party_commands', inventoryStyle: 'none', economyStyle: 'gold' }, contentScope: { items: 'light', characters: 'heavy', abilities: 'medium', locations: 'none', markets: 'medium', quests: 'none', graphs: 'light' } },
  { id: 'card_battler_deckbuilder', label: 'Card Battler / Deckbuilder', description: 'Cards, encounters, routes, and upgrade economies.', promptHint: 'Cards, encounters, shops, route choice.', defaultPackIds: ['pack.action_rpg'], theme: { genre: 'strategy_battler', tone: 'mysterious', playerFantasy: 'duelist', namingStyle: 'mythic_dense' }, systems: { progressionStyle: 'branching', combatStyle: 'turn_based', inputStyle: 'party_commands', inventoryStyle: 'none', economyStyle: 'gold' }, contentScope: { items: 'medium', characters: 'light', abilities: 'heavy', locations: 'light', markets: 'light', quests: 'none', graphs: 'medium' } },
  { id: 'mmo_lite_social_rpg', label: 'MMO-lite / Social RPG', description: 'Shared hubs, progression, classes, and lightweight group content.', promptHint: 'Classes, social hubs, vendors, group loops.', defaultPackIds: ['pack.rpg_core'], theme: { genre: 'fantasy_rpg', tone: 'heroic', playerFantasy: 'adventurer', namingStyle: 'classic_fantasy' }, systems: { progressionStyle: 'open', combatStyle: 'real_time', inputStyle: 'direct_control', inventoryStyle: 'slots', economyStyle: 'gold' }, contentScope: { items: 'heavy', characters: 'heavy', abilities: 'medium', locations: 'heavy', markets: 'medium', quests: 'medium', graphs: 'medium' } },
]

export const GAME_ARCHETYPES = gameArchetypes
export const gameArchetypeMap = new Map(gameArchetypes.map((entry) => [entry.id, entry]))

function titleFromConcept(conceptPrompt: string, fallbackLabel: string) {
  const trimmed = conceptPrompt.trim()
  if (!trimmed) return fallbackLabel
  const sentence = trimmed.split(/[.!?\n]/)[0]?.trim() ?? trimmed
  return sentence.slice(0, 72)
}

export function createGameSpecFromArchetype(gameArchetypeId: string, conceptPrompt = ''): GameSpec {
  const archetype = gameArchetypeMap.get(gameArchetypeId) ?? gameArchetypes[0]
  const base = createDefaultGameSpec(archetype.defaultPackIds)
  const expanded = expandPackPresetIds(archetype.defaultPackIds)

  return {
    ...base,
    presetCatalogVersion: PRESET_CATALOG_VERSION,
    title: titleFromConcept(conceptPrompt, archetype.label),
    theme: {
      ...base.theme,
      ...archetype.theme,
      worldPremise: conceptPrompt.trim() || base.theme.worldPremise,
    },
    systems: {
      ...base.systems,
      ...archetype.systems,
    },
    contentScope: {
      ...base.contentScope,
      ...archetype.contentScope,
    },
    selectedPresetIds: {
      packs: archetype.defaultPackIds,
      archetypes: expanded.archetypePresetIds,
      definitions: expanded.definitionPresetIds,
      graphs: archetype.starterGraphs ?? expanded.graphPresetIds,
    },
    bootstrapTargets: {
      starterArchetypePresetIds: expanded.archetypePresetIds,
      starterDefinitionPresetIds: expanded.definitionPresetIds,
      starterGraphPresetIds: archetype.starterGraphs ?? expanded.graphPresetIds,
    },
    overrides: {
      gameArchetypeId: archetype.id,
      gameArchetypeLabel: archetype.label,
      gameConceptPrompt: conceptPrompt,
    },
  }
}
