import type { OutputWorkflowNode, OutputWorkflowRunScope } from './outputWorkflow.ts'
import {
  createWorkflowNodeManifest,
  createWorkflowNodeManifestRegistry,
  getWorkflowNodeManifest as getRegisteredWorkflowNodeManifest,
  registerWorkflowNodeManifest as registerManifestInRegistry,
  workflowNodeManifestToContract,
  type WorkflowNodeContractView,
  type WorkflowNodeManifest,
} from './outputWorkflowManifests.ts'

export type OutputWorkflowNodeContract = WorkflowNodeContractView

const cinematicSequenceContracts = [
  {
    purpose: 'sequence_animatic_scene_graph_assignment',
    label: 'Scene Graph Assignment',
    requiredInputs: ['screenplay', 'asset_pack', 'context'],
    producedOutputs: ['text', 'scenePackage', 'scene_package', 'scenePackages', 'scene_packages', 'sceneGraphDraft', 'scene_graph_draft', 'dialogueRows', 'dialogue_rows'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Assigning scene graph',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_package',
    label: 'Build Scene Packages',
    requiredInputs: ['screenplay', 'asset_pack', 'context'],
    producedOutputs: ['text', 'scenePackage', 'scene_package', 'scenePackages', 'scene_packages', 'sceneGraphDraft', 'scene_graph_draft', 'dialogueRows', 'dialogue_rows'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Parsing tagged screenplay scenes',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_plan_fanout',
    label: 'Queue Scene Shot Plans',
    requiredInputs: ['scene_package'],
    producedOutputs: ['text', 'dynamicGraphExpanded', 'graphExpanded', 'sceneCount'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Queueing scene shot planners',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_register',
    label: 'Register Scenes',
    requiredInputs: ['scene_package'],
    producedOutputs: ['text', 'scenes', 'sceneCount', 'scene_count'],
    artifactRoles: ['sequence_animatic_scene_index'],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Registering scenes',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_input',
    label: 'Scene Input',
    requiredInputs: [],
    producedOutputs: ['text', 'scenePackage', 'scene_package', 'screenplayDraft', 'screenplay_draft', 'screenplay', 'assetPack', 'asset_pack', 'context', 'guidance', 'sceneId', 'sceneIndex'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing scene shot plan input',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_shot_plan',
    label: 'Scene Shot Plan',
    requiredInputs: ['scene_package', 'screenplay', 'asset_pack', 'context'],
    producedOutputs: ['text', 'scenePlan', 'scene_plan', 'sceneShotPlan', 'scene_shot_plan', 'shotContinuityPlan', 'shot_continuity_plan', 'directorPlan', 'director_plan'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Building scene shots and continuity',
    providerBacked: true,
    manualOnly: false,
    streamingPolicy: {
      mode: 'jsonl',
      partialArtifactRoles: ['sequence_animatic_scene_plan'],
      resumeTokenRequired: false,
      progressLabels: {
        streaming: 'Streaming scene shot plan',
        finalizing: 'Finalizing scene shot plan',
        completed: 'Scene shot plan ready',
      },
    },
  },
  {
    purpose: 'sequence_animatic_scene_plan_merge',
    label: 'Merge Scene Shot Plans',
    requiredInputs: ['scene_plan'],
    producedOutputs: ['text', 'directorPlan', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan', 'shot_plan', 'continuityGraphV2', 'continuity_graph_v2', 'shotBindings', 'shot_bindings'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Merging scene shot plans',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_manifest',
    label: 'Build Animatic Manifest',
    requiredInputs: ['director_plan'],
    producedOutputs: ['text', 'manifest', 'sequenceAnimaticManifest', 'shot_plan', 'animaticReferenceCatalog', 'animatic_reference_catalog', 'selectedVisualReferenceKeys', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Building animatic manifest',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_manifest_artifact',
    label: 'Register Animatic Manifest',
    requiredInputs: ['input'],
    producedOutputs: ['artifact', 'manifest'],
    artifactRoles: ['sequence_animatic_manifest'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Registering animatic manifest',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_director_plan',
    label: 'Shot Continuity Plan',
    requiredInputs: ['screenplay', 'asset_pack', 'context'],
    producedOutputs: ['text', 'directorPlan', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan', 'shot_plan', 'continuityGraphV2', 'continuity_graph_v2', 'shotBindings', 'shot_bindings'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Building shots, refs, and continuity',
    providerBacked: true,
    manualOnly: false,
    streamingPolicy: {
      mode: 'jsonl',
      partialArtifactRoles: ['sequence_animatic_director_plan'],
      resumeTokenRequired: false,
      progressLabels: {
        streaming: 'Streaming shot continuity plan',
        finalizing: 'Finalizing shot continuity plan',
        completed: 'Shot continuity plan ready',
      },
    },
  },
  {
    purpose: 'sequence_animatic_director_plan_artifact',
    label: 'Register Shot Continuity Plan',
    requiredInputs: ['director_plan'],
    producedOutputs: ['artifact', 'directorPlan', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan'],
    artifactRoles: ['sequence_animatic_director_plan'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving shot continuity plan',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_plan',
    label: 'Coverage Plan',
    requiredInputs: ['director_plan'],
    producedOutputs: ['text', 'coveragePlan', 'coverage_plan', 'coverageSetups', 'coverage_setups', 'coverageSetupByShotId', 'coverage_setup_by_shot_id', 'directorPlan', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning coverage',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_orchestrator',
    label: 'Queue Animatic Blocks',
    requiredInputs: ['director_plan'],
    producedOutputs: ['orchestration', 'childRequests', 'startedRunIds'],
    artifactRoles: [],
    previewRoles: ['orchestration'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Queueing storyboard blocks',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_input',
    label: 'Continuity Batch Input',
    requiredInputs: [],
    producedOutputs: ['text', 'batch', 'target_nodes', 'asset_pack', 'referenceAssetKeys'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing continuity reference batch',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_prompt',
    label: 'Continuity Batch Prompt',
    requiredInputs: ['batch', 'target_nodes', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'asset_pack', 'referenceAssetKeys'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Writing continuity reference prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_image',
    label: 'Continuity Batch Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey', 'storagePath'],
    artifactRoles: ['sequence_animatic_continuity_batch_image'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating continuity reference grid',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_extract',
    label: 'Extract Continuity Batch',
    requiredInputs: ['batch', 'target_nodes', 'image'],
    producedOutputs: ['assets', 'assetStateByNodeId', 'asset_state_by_node_id'],
    artifactRoles: ['sequence_animatic_continuity_asset'],
    previewRoles: ['assets'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Extracting continuity reference crops',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_artifact',
    label: 'Register Continuity Batch',
    requiredInputs: ['batch'],
    producedOutputs: ['artifact', 'assets', 'assetStateByNodeId', 'asset_state_by_node_id'],
    artifactRoles: ['sequence_animatic_continuity_asset_batch'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving continuity reference batch',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_block_input',
    label: 'Block Input',
    requiredInputs: [],
    producedOutputs: ['text', 'shot_plan', 'asset_pack', 'block'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing storyboard block',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_block_artifact',
    label: 'Register Block',
    requiredInputs: ['input'],
    producedOutputs: ['artifact', 'block', 'panels', 'videoPrompt'],
    artifactRoles: ['sequence_animatic_block_manifest'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving storyboard block manifest',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_input',
    label: 'Shot Input',
    requiredInputs: [],
    producedOutputs: ['shot', 'image', 'asset_pack', 'shot_plan'],
    artifactRoles: [],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot video input',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_input',
    label: 'Continuity Input',
    requiredInputs: [],
    producedOutputs: ['text', 'master_manifest', 'screenplay', 'shot_plan', 'shot_break_plan', 'asset_pack', 'animaticReferenceCatalog', 'animatic_reference_catalog', 'continuityPlannerContext', 'continuity_planner_context'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing continuity pack input',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_script_authoring',
    label: 'Cinematic Script',
    requiredInputs: ['asset_pack', 'context'],
    producedOutputs: ['text', 'directorScriptDoc', 'cinematicScriptDoc', 'scriptDoc', 'script', 'executionScriptDoc', 'shotCount', 'totalDurationSeconds', 'providerStatus'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Authoring cinematic script',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_sequence_plan',
    label: 'Sequence Plan',
    requiredInputs: ['asset_pack', 'context'],
    producedOutputs: ['text', 'sequencePlan', 'sequence_plan', 'blocks', 'providerStatus'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning cinematic sequence',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_block_script',
    label: 'Block Script',
    requiredInputs: ['sequence_plan', 'asset_pack'],
    producedOutputs: ['text', 'markdown', 'blockScript', 'block_script', 'script', 'blockNumber', 'durationSeconds', 'providerStatus'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Writing block script',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_storyboard_prompt',
    label: 'Storyboard Prompt',
    requiredInputs: ['shot_plan', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'providerPrompt'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing storyboard prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_storyboard_sheet',
    label: 'Storyboard Sheet',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['cinematic_v3_storyboard_sheet', 'cinematic_v2_storyboard_sheet'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating storyboard sheet',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_panel_extract',
    label: 'Extract Panels',
    requiredInputs: ['image', 'shot_plan'],
    producedOutputs: ['panels', 'artifacts'],
    artifactRoles: ['cinematic_v3_storyboard_panel', 'cinematic_v2_storyboard_panel', 'sequence_animatic_block_panel'],
    previewRoles: ['panels'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Extracting storyboard panels',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_storyboard_group_video_prompt',
    label: 'Video Prompt',
    requiredInputs: ['shot_plan', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'providerPrompt'],
    artifactRoles: ['sequence_animatic_block_manifest'],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Preparing video prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_storyboard_group_video',
    label: 'Video',
    requiredInputs: ['prompt', 'references'],
    producedOutputs: ['video', 'assetKey'],
    artifactRoles: ['cinematic_v3_storyboard_group_video', 'sequence_animatic_block_video'],
    previewRoles: ['video'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating video',
    providerBacked: true,
    manualOnly: true,
  },
  {
    purpose: 'sequence_animatic_shot_video_prompt',
    label: 'Shot Video Prompt',
    requiredInputs: ['shot', 'asset_pack', 'references'],
    producedOutputs: ['text', 'prompt', 'providerPrompt'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot video prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_video',
    label: 'Shot Video',
    requiredInputs: ['prompt', 'references'],
    producedOutputs: ['video', 'assetKey'],
    artifactRoles: ['sequence_animatic_shot_video'],
    previewRoles: ['video'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating shot video',
    providerBacked: true,
    manualOnly: true,
  },
  {
    purpose: 'sequence_animatic_shared_asset_ref',
    label: 'Shared Asset Reference',
    requiredInputs: [],
    producedOutputs: ['reference', 'image', 'assetKey', 'artifact', 'status'],
    artifactRoles: ['sequence_animatic_coverage_anchor', 'sequence_animatic_shot_keyframe', 'sequence_animatic_continuity_asset', 'sequence_animatic_continuity_asset_batch', 'sequence_animatic_block_panel'],
    previewRoles: ['image', 'artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Resolving shared reference',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'workflow_ensure_child_workflow',
    label: 'Ensure Child Workflow',
    requiredInputs: [],
    producedOutputs: ['childRequestId', 'childWorkflowId', 'childRunId', 'status', 'readyArtifactRoles', 'readyArtifactKeys', 'waiting', 'resumable', 'metadata'],
    artifactRoles: [],
    previewRoles: ['metadata'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Ensuring child workflow',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'workflow_wait_child_workflow',
    label: 'Wait For Child Workflow',
    requiredInputs: ['childRequestId'],
    producedOutputs: ['childRequestId', 'childWorkflowId', 'childRunId', 'status', 'readyArtifactRoles', 'readyArtifactKeys', 'waiting', 'resumable', 'resumeAfterMs', 'diagnostics', 'metadata'],
    artifactRoles: [],
    previewRoles: ['metadata'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Waiting for child workflow',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'workflow_register_artifact_projection',
    label: 'Register Artifact Projection',
    requiredInputs: [],
    producedOutputs: ['workflowRuntime', 'childRequests', 'child_runs', 'readyArtifactKeys', 'readyArtifactRoles', 'waiting', 'metadata'],
    artifactRoles: [],
    previewRoles: ['metadata'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Updating workflow projection',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'workflow_fanout_children',
    label: 'Fan Out Child Workflows',
    requiredInputs: [],
    producedOutputs: ['children', 'childRequests', 'child_requests', 'childRunIds', 'child_run_ids', 'readyArtifactRoles', 'readyArtifactKeys', 'waiting', 'metadata'],
    artifactRoles: [],
    previewRoles: ['metadata'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Materializing child workflows',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'workflow_collect_child_artifacts',
    label: 'Collect Child Artifacts',
    requiredInputs: [],
    producedOutputs: ['artifacts', 'artifactKeys', 'artifact_keys', 'childRequests', 'child_requests', 'childRunIds', 'child_run_ids', 'readyArtifactRoles', 'readyArtifactKeys', 'missingArtifactRoles', 'missing_artifact_roles', 'workflowRuntime', 'metadata'],
    artifactRoles: [],
    previewRoles: ['metadata'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Collecting child artifacts',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_board_scope_input',
    label: 'Scene Board Scope',
    requiredInputs: [],
    producedOutputs: ['text', 'scope', 'sceneBoardCommand', 'scene_board_command', 'shotIds', 'shot_ids'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing Scene Board scope',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_board_required_ref_plan',
    label: 'Plan Required Refs',
    requiredInputs: ['scope'],
    producedOutputs: ['text', 'requiredRefs', 'required_refs', 'scope'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning required refs',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_board_set_ref_generation',
    label: 'Set Refs',
    requiredInputs: ['requiredRefs'],
    producedOutputs: ['text', 'setRefStatus', 'set_ref_status', 'childWorkflows', 'child_workflows', 'childRequests', 'child_requests'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Queueing set refs',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_board_scaffold_ref_generation',
    label: 'Zone Map / Spot Atlas',
    requiredInputs: ['upstreamStatus'],
    producedOutputs: ['text', 'scaffoldRefStatus', 'scaffold_ref_status', 'childWorkflows', 'child_workflows', 'childRequests', 'child_requests'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Queueing zone maps and spot atlases',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_board_spot_angle_coverage',
    label: 'Spot Angle Coverage',
    requiredInputs: ['upstreamStatus'],
    producedOutputs: ['text', 'spotAngleStatus', 'spot_angle_status', 'childWorkflows', 'child_workflows', 'childRequests', 'child_requests'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Queueing spot angle coverage',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_board_coverage_intent_batch',
    label: 'Coverage Directions',
    requiredInputs: ['scaffoldRefStatus'],
    producedOutputs: ['text', 'coverageIntentStatus', 'coverage_intent_status', 'childWorkflows', 'child_workflows', 'childRequests', 'child_requests'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Queueing coverage directions',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_board_zone_coverage_grid',
    label: 'Zone Coverage Grid',
    requiredInputs: ['coverageIntentStatus'],
    producedOutputs: ['text', 'zoneCoverageStatus', 'zone_coverage_status', 'childWorkflows', 'child_workflows', 'childRequests', 'child_requests'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Queueing zone coverage grids',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_board_coverage_cell_artifact',
    label: 'Register Board Prep',
    requiredInputs: ['workflowRuntime', 'scope'],
    producedOutputs: ['artifact', 'sceneBoardPrep', 'scene_board_prep', 'shotReferenceReadiness', 'shot_reference_readiness', 'sceneContinuityManifest', 'scene_continuity_manifest', 'workflowRuntime', 'workflow_runtime', 'childRequests', 'child_requests', 'readyArtifactKeys', 'ready_artifact_keys'],
    artifactRoles: ['sequence_animatic_scene_board_prep'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving Scene Board prep',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_intent_input',
    label: 'Coverage Direction Input',
    requiredInputs: [],
    producedOutputs: ['text', 'intentBatch', 'intent_batch', 'shots', 'assetPack', 'asset_pack', 'shotIds', 'shot_ids'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing coverage directions',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_intent_plan',
    label: 'Coverage Directions',
    requiredInputs: ['intent_batch', 'shots', 'asset_pack'],
    producedOutputs: ['text', 'coverageIntents', 'coverage_intents', 'coverageIntentBatch', 'coverage_intent_batch', 'intentBatch', 'intent_batch', 'shots', 'assetPack', 'asset_pack', 'prompt'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning coverage directions',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_intent_artifact',
    label: 'Register Coverage Directions',
    requiredInputs: ['intent_batch', 'coverage_intents'],
    producedOutputs: ['artifact', 'artifacts', 'artifactKey', 'coverageIntentByShotId', 'coverage_intent_by_shot_id', 'coverageIntents', 'coverage_intents', 'intentBatch', 'intent_batch', 'prompt'],
    artifactRoles: ['sequence_animatic_coverage_intent_batch'],
    previewRoles: ['artifact', 'text'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving coverage directions',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_reference_pack',
    label: 'Shot Reference Pack',
    requiredInputs: ['shot', 'asset_pack'],
    producedOutputs: ['text', 'shot', 'asset_pack', 'referenceAssetKeys', 'reference_asset_keys', 'referenceImages', 'reference_images', 'referenceManifest', 'reference_manifest', 'referencePlanHash', 'reference_plan_hash', 'missingReferences', 'missing_references', 'coverageAnchor', 'coverage_anchor', 'previousKeyframe', 'previous_keyframe', 'storyboardPanel', 'storyboard_panel', 'references', 'image', 'keyframe'],
    artifactRoles: [],
    previewRoles: ['referenceImages', 'image', 'text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot references',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_video_artifact',
    label: 'Register Shot Video',
    requiredInputs: ['video'],
    producedOutputs: ['artifact', 'video', 'assetKey'],
    artifactRoles: ['sequence_animatic_shot_video'],
    previewRoles: ['artifact', 'video'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving shot video',
    providerBacked: false,
    manualOnly: true,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_input',
    label: 'Zone Camera Grid Input',
    requiredInputs: [],
    producedOutputs: ['text', 'board', 'zoneCoverageBoard', 'zone_coverage_board', 'shots', 'coverageCells', 'coverage_cells', 'asset_pack', 'previous_board'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing zone camera grid',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_brief',
    label: 'Zone Camera Grid Brief',
    requiredInputs: ['board', 'coverage_cells', 'asset_pack'],
    producedOutputs: ['text', 'coverageBrief', 'coverage_brief', 'cameraGridBrief', 'camera_grid_brief', 'cells', 'board', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning zone camera grid',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_prompt',
    label: 'Zone Camera Grid Prompt',
    requiredInputs: ['coverage_brief', 'coverage_cells', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'board', 'coverageBrief', 'coverage_brief', 'asset_pack', 'referenceManifest'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing zone camera grid prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_image',
    label: 'Zone Camera Grid Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_zone_coverage_board_image'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating zone camera grid',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_extract',
    label: 'Extract Zone Camera Cells',
    requiredInputs: ['image', 'coverage_cells'],
    producedOutputs: ['cells', 'coverageCells', 'coverage_cells', 'cellAssetKeysByShotId', 'coverageCellByShotId'],
    artifactRoles: ['sequence_animatic_coverage_anchor'],
    previewRoles: ['image', 'text'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Extracting zone camera cells',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_artifact',
    label: 'Register Zone Camera Grid',
    requiredInputs: ['image', 'cells'],
    producedOutputs: ['artifact', 'board', 'cells', 'coverageCellByShotId', 'assetKey'],
    artifactRoles: ['sequence_animatic_zone_coverage_board'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving zone camera grid',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_input',
    label: 'Coverage Anchor Input',
    requiredInputs: [],
    producedOutputs: ['text', 'coverageSetup', 'coverage_setup', 'shots', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing coverage anchor',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_prompt',
    label: 'Coverage Anchor Prompt',
    requiredInputs: ['coverage_setup', 'asset_pack', 'coverage_brief'],
    producedOutputs: ['text', 'prompt', 'coverageSetup', 'coverage_setup', 'coverageBrief', 'coverage_brief', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing coverage anchor prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_brief',
    label: 'Coverage Anchor Brief',
    requiredInputs: ['coverage_setup', 'shots', 'asset_pack'],
    producedOutputs: ['text', 'coverageBrief', 'coverage_brief', 'promptBrief', 'prompt_brief', 'coverageSetup', 'coverage_setup', 'shots', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning coverage anchor',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_image',
    label: 'Coverage Anchor Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_coverage_anchor_image'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating coverage anchor',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_artifact',
    label: 'Register Coverage Anchor',
    requiredInputs: ['coverage_setup'],
    producedOutputs: ['artifact', 'coverageAnchor', 'coverage_anchor', 'reference', 'image', 'keyframe', 'primaryReferenceImage'],
    artifactRoles: ['sequence_animatic_coverage_anchor'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving coverage anchor',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_planned_keyframe_input',
    label: 'Shot Keyframe Input',
    requiredInputs: [],
    producedOutputs: ['text', 'shot', 'coverageSetup', 'coverage_setup', 'coverageAnchor', 'coverage_anchor', 'previousKeyframe', 'previous_keyframe', 'storyboardPanel', 'storyboard_panel', 'assetPack', 'asset_pack', 'referenceManifest', 'reference_manifest', 'referenceManifestText', 'reference_manifest_text', 'shotId', 'shot_id'],
    artifactRoles: [],
    previewRoles: ['text', 'image'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot keyframe',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_planned_keyframe_prompt',
    label: 'Shot Keyframe Prompt',
    requiredInputs: ['shot', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'shot', 'coverageAnchor', 'coverage_anchor', 'asset_pack', 'referenceAssetKeys', 'reference_asset_keys'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot keyframe prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_planned_keyframe_image',
    label: 'Shot Keyframe Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_shot_keyframe'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating shot keyframe',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_planned_keyframe_artifact',
    label: 'Register Shot Keyframe',
    requiredInputs: ['shot'],
    producedOutputs: ['artifact', 'shotKeyframe', 'shot_keyframe', 'image'],
    artifactRoles: ['sequence_animatic_shot_keyframe'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving shot keyframe',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_revision_input',
    label: 'Shot Revision Input',
    requiredInputs: [],
    producedOutputs: ['text', 'shot', 'baseShot', 'base_shot', 'baseKeyframe', 'base_keyframe', 'image', 'keyframe', 'panel', 'assetPack', 'asset_pack', 'revisionPrompt', 'revision_prompt', 'revisionId', 'revision_id'],
    artifactRoles: [],
    previewRoles: ['text', 'image'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot revision input',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_revision_plan',
    label: 'Revise Shot',
    requiredInputs: ['shot', 'revision_prompt'],
    producedOutputs: ['text', 'revisedShot', 'revised_shot', 'revisionPlan', 'revision_plan', 'baseShot', 'base_shot', 'revisionPrompt', 'revision_prompt', 'changeSummary', 'change_summary', 'keyframeIntent', 'keyframe_intent', 'diagnostics', 'providerRequestId', 'plannerProvider', 'plannerModel'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Rewriting shot',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_keyframe_prompt',
    label: 'Shot Keyframe Prompt',
    requiredInputs: ['revised_shot', 'asset_pack', 'base_keyframe'],
    producedOutputs: ['text', 'prompt', 'revisedShot', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing keyframe prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_keyframe_image',
    label: 'Shot Keyframe Image',
    requiredInputs: ['prompt', 'references'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_shot_keyframe'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating keyframe',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_revision_artifact',
    label: 'Register Shot Revision',
    requiredInputs: ['revised_shot'],
    producedOutputs: ['artifact', 'revision', 'revisedShot', 'keyframe'],
    artifactRoles: ['sequence_animatic_shot_revision'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving shot revision',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_anchor_plan',
    label: 'Plan Continuity Anchors',
    requiredInputs: ['screenplay', 'shot_plan', 'asset_pack'],
    producedOutputs: ['text', 'continuityAnchorPlan', 'continuity_anchor_plan', 'characterAnchors', 'propAnchors', 'locationSpotAnchors', 'continuityGraphV2', 'continuity_graph_v2', 'locationSets', 'locationAngles', 'sceneGraph', 'shotContinuityMap', 'shotBindings', 'rejectedCandidates'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Finding reusable characters, props, and locations',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_seed_graph',
    label: 'Seed Continuity Scene Graph',
    requiredInputs: ['continuity_planner_context'],
    producedOutputs: ['text', 'continuityGraphV2', 'continuity_graph_v2'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Seeding continuity scene graph',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_block_plan',
    label: 'Plan Continuity Block',
    requiredInputs: ['continuity_graph_v2', 'continuity_planner_context'],
    producedOutputs: ['text', 'continuityBlockDelta', 'continuity_block_delta'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning block continuity',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_global_plan',
    label: 'Plan Continuity Structure',
    requiredInputs: ['continuity_graph_v2', 'continuity_planner_context'],
    producedOutputs: ['text', 'continuityBlockDelta', 'continuity_block_delta'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning global continuity structure',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_global_merge',
    label: 'Merge Continuity Structure',
    requiredInputs: ['continuity_graph_v2', 'continuity_block_delta'],
    producedOutputs: ['text', 'continuityGraphV2', 'continuity_graph_v2', 'continuityBlockDelta', 'continuity_block_delta', 'globalStructureState', 'coverage'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Merging global continuity structure',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_block_merge',
    label: 'Merge Continuity Block',
    requiredInputs: ['continuity_graph_v2', 'continuity_block_delta'],
    producedOutputs: ['text', 'continuityGraphV2', 'continuity_graph_v2'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Merging block continuity',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_graph_finalize',
    label: 'Finalize Continuity Scene Graph',
    requiredInputs: ['continuity_graph_v2'],
    producedOutputs: ['text', 'continuityGraphV2', 'continuity_graph_v2', 'locationSets', 'locationAngles', 'sceneGraph', 'shotContinuityMap', 'shotBindings', 'assetAnchors', 'rejectedCandidates'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Finalizing continuity scene graph',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_structure_artifact',
    label: 'Save Continuity Structure',
    requiredInputs: ['continuity_graph_v2'],
    producedOutputs: ['artifact', 'continuityPack', 'continuity_pack', 'continuityGraphV2', 'continuity_graph_v2', 'shotBindings', 'blockStates', 'pendingDeltas', 'globalStructureState', 'coverage', 'assetStateByNodeId', 'visualDependencyEdges', 'assetGenerationStatus'],
    artifactRoles: ['sequence_animatic_continuity_pack'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving continuity structure',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_asset_input',
    label: 'Continuity Asset Input',
    requiredInputs: [],
    producedOutputs: ['text', 'continuityPack', 'continuity_pack', 'targetNode', 'target_node', 'relevantShots', 'relevant_shots', 'shotBindings', 'shot_bindings', 'assetPack', 'asset_pack', 'referenceAssetKeys', 'reference_asset_keys'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Collecting continuity asset context',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_asset_prompt',
    label: 'Continuity Asset Prompt',
    requiredInputs: ['target_node'],
    producedOutputs: ['text', 'prompt', 'assetPack', 'asset_pack', 'referenceAssetKeys', 'reference_asset_keys', 'targetNode', 'target_node', 'relevantShots', 'relevant_shots'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing continuity asset prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_asset_image',
    label: 'Continuity Asset Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_continuity_asset_image'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating continuity asset',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_asset_artifact',
    label: 'Register Continuity Asset',
    requiredInputs: ['image', 'target_node'],
    producedOutputs: ['artifact', 'continuityAsset', 'continuity_asset', 'reference', 'assetState', 'asset_state', 'assetStateByNodeId', 'asset_state_by_node_id', 'image', 'keyframe', 'primaryReferenceImage'],
    artifactRoles: ['sequence_animatic_continuity_asset'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving continuity asset',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_character_anchor_atlas_prompt',
    label: 'Character Anchor Atlas Prompt',
    requiredInputs: ['continuity_anchor_plan'],
    producedOutputs: ['text', 'prompt', 'anchors', 'atlasLayout'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing temporary character atlas prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_character_anchor_atlas',
    label: 'Character Anchor Atlas',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_character_anchor_atlas'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating temporary character atlas',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_character_anchor_extract',
    label: 'Extract Character Anchors',
    requiredInputs: ['image', 'continuity_anchor_plan'],
    producedOutputs: ['anchors', 'artifacts'],
    artifactRoles: ['sequence_animatic_character_anchor'],
    previewRoles: ['anchors'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Splitting character refs',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_prop_anchor_atlas_prompt',
    label: 'Prop Anchor Atlas Prompt',
    requiredInputs: ['continuity_anchor_plan'],
    producedOutputs: ['text', 'prompt', 'anchors', 'atlasLayout'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing prop atlas prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_prop_anchor_atlas',
    label: 'Prop Anchor Atlas',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_prop_anchor_atlas'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating prop reference atlas',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_prop_anchor_extract',
    label: 'Extract Prop Anchors',
    requiredInputs: ['image', 'continuity_anchor_plan'],
    producedOutputs: ['anchors', 'artifacts'],
    artifactRoles: ['sequence_animatic_prop_anchor'],
    previewRoles: ['anchors'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Splitting prop refs',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_location_anchor_atlas_prompt',
    label: 'Location Anchor Atlas Prompt',
    requiredInputs: ['continuity_anchor_plan'],
    producedOutputs: ['text', 'prompt', 'anchors', 'atlasLayout'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing location spot atlas prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_location_anchor_atlas',
    label: 'Location Anchor Atlas',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_location_anchor_atlas'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating location spot atlas',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_location_anchor_extract',
    label: 'Extract Location Anchors',
    requiredInputs: ['image', 'continuity_anchor_plan'],
    producedOutputs: ['anchors', 'artifacts'],
    artifactRoles: ['sequence_animatic_location_anchor'],
    previewRoles: ['anchors'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Splitting location refs',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_artifact',
    label: 'Register Continuity Pack',
    requiredInputs: ['continuity_anchor_plan'],
    producedOutputs: ['artifact', 'continuityPack', 'characterAnchors', 'propAnchors', 'locationSpotAnchors'],
    artifactRoles: ['sequence_animatic_continuity_pack'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving continuity pack',
    providerBacked: false,
    manualOnly: false,
  },
] satisfies OutputWorkflowNodeContract[]

const legacyWorkflowCompatibilityPurposes = [
  'action',
  'bible_assembly',
  'bible_section',
  'bible_section_plan',
  'chapter_assembly',
  'chapter_plan',
  'chapter_prose',
  'cinematic_beat_sheet',
  'cinematic_beat_sheet_prompt',
  'cinematic_block_video',
  'cinematic_entity_selector',
  'cinematic_atlas_prompt',
  'cinematic_keyframe',
  'cinematic_keyframe_prompt_pack',
  'cinematic_sequence_compile',
  'cinematic_storyboard_prompt',
  'cinematic_v2_reference_select',
  'cinematic_v2_screenplay_author',
  'cinematic_v2_script_parse',
  'cinematic_v2_dynamic_shot_fanout',
  'cinematic_v2_keyframe_prompt',
  'cinematic_v2_keyframe_qa',
  'cinematic_v2_layout_plan',
  'cinematic_v2_panel_extract',
  'cinematic_v2_shot_asset_pack',
  'cinematic_v2_shot_keyframe',
  'cinematic_v2_shot_keyframe_passthrough',
  'cinematic_v2_shot_video',
  'cinematic_v2_scene_compile',
  'cinematic_v2_shot_plan',
  'cinematic_v2_storyboard_prompt',
  'cinematic_v2_storyboard_group_plan',
  'cinematic_v2_storyboard_sheet',
  'cinematic_v2_timeline_assemble',
  'cinematic_v2_video_prompt',
  'cinematic_dynamic_take_fanout',
  'cinematic_v3_dynamic_shot_parse_fanout',
  'cinematic_v3_dynamic_storyboard_fanout',
  'cinematic_v3_reference_select',
  'cinematic_v3_screenplay_author',
  'cinematic_v3_shot_break_plan',
  'cinematic_v3_shot_plan_merge',
  'cinematic_v3_shot_parse',
  'cinematic_v3_shot_parse_group',
  'cinematic_v3_storyboard_group_plan',
  'cinematic_v3_timeline_assemble',
  'cinematic_video_artifact',
  'cinematic_video_prompt',
  'comic_artifact',
  'comic_entity_selector',
  'comic_page',
  'comic_page_plan',
  'comic_page_prompt',
  'comic_pdf_render',
  'comic_scene_script',
  'comic_script',
  'concept_art_prompt',
  'concept_art_image',
  'dialogue',
  'ebook_cover_image',
  'ebook_cover_prompt',
  'editor_pass',
  'establishing',
  'front_back_matter',
  'image_reference_selector',
  'outline',
  'poster_prompt',
  'poster_image',
  'reaction',
  'story_bible_artifact',
  'story_bible_document_render',
  'video_stitch',
] as const

const legacyWorkflowCompatibilityContracts = legacyWorkflowCompatibilityPurposes.map((purpose): OutputWorkflowNodeContract => ({
  purpose,
  label: purpose.split('_').map((part) => part.slice(0, 1).toUpperCase() + part.slice(1)).join(' '),
  requiredInputs: [],
  producedOutputs: [],
  artifactRoles: purpose.endsWith('_artifact') ? [purpose] : [],
  previewRoles: [],
  recoveryStrategy: purpose.endsWith('_artifact') || purpose.endsWith('_image') || purpose.endsWith('_sheet') || purpose.endsWith('_video') ? 'node_step_artifact' : 'node_step',
  progressLabel: purpose.split('_').join(' '),
  providerBacked: purpose.includes('image') || purpose.includes('video') || purpose.includes('prose') || purpose.includes('screenplay') || purpose.includes('script'),
  manualOnly: false,
}))

export const outputWorkflowNodeManifests = [
  ...cinematicSequenceContracts,
  ...legacyWorkflowCompatibilityContracts,
].map((contract) => createWorkflowNodeManifest(contract))

export const outputWorkflowNodeManifestsByPurpose = createWorkflowNodeManifestRegistry(outputWorkflowNodeManifests)

export const outputWorkflowNodeContractsByPurpose = new Map<string, OutputWorkflowNodeContract>(
  outputWorkflowNodeManifests.map((manifest) => [manifest.purpose, workflowNodeManifestToContract(manifest)]),
)

export function registerWorkflowNodeManifest(manifest: WorkflowNodeManifest) {
  registerManifestInRegistry(outputWorkflowNodeManifestsByPurpose, manifest)
  outputWorkflowNodeContractsByPurpose.set(manifest.purpose, workflowNodeManifestToContract(manifest))
  return manifest
}

export function outputWorkflowNodePurpose(nodeOrConfig: Pick<OutputWorkflowNode, 'config'> | Record<string, unknown> | null | undefined) {
  const config = nodeOrConfig && 'config' in nodeOrConfig
    ? nodeOrConfig.config
    : nodeOrConfig
  if (!config || typeof config !== 'object' || Array.isArray(config)) return ''
  const record = config as Record<string, unknown>
  return typeof record.purpose === 'string' && record.purpose.trim()
    ? record.purpose.trim()
    : typeof record.role === 'string'
      ? record.role.trim()
      : ''
}

export function getOutputWorkflowNodeContract(nodeOrConfig: Pick<OutputWorkflowNode, 'config'> | Record<string, unknown> | null | undefined) {
  const purpose = outputWorkflowNodePurpose(nodeOrConfig)
  return purpose ? outputWorkflowNodeContractsByPurpose.get(purpose) ?? null : null
}

export function getWorkflowNodeManifest(nodeOrConfig: Pick<OutputWorkflowNode, 'config'> | Record<string, unknown> | null | undefined) {
  return getRegisteredWorkflowNodeManifest(outputWorkflowNodeManifestsByPurpose, outputWorkflowNodePurpose(nodeOrConfig))
}

export function validateWorkflowNodeManifestConfig(nodeOrConfig: Pick<OutputWorkflowNode, 'config'> | Record<string, unknown> | null | undefined) {
  const manifest = getWorkflowNodeManifest(nodeOrConfig)
  const config = nodeOrConfig && 'config' in nodeOrConfig ? nodeOrConfig.config : nodeOrConfig
  if (!manifest) return { ok: false as const, diagnostics: ['Workflow node purpose is not registered.'] }
  const parsed = manifest.configSchema.safeParse(config && typeof config === 'object' && !Array.isArray(config) ? config : {})
  return parsed.success
    ? { ok: true as const, diagnostics: [] as string[] }
    : { ok: false as const, diagnostics: parsed.error.issues.map((issue) => `${manifest.purpose}: invalid config at ${issue.path.join('.') || '<root>'}: ${issue.message}`) }
}

export type OutputWorkflowRunIntent =
  | 'generate_director_plan'
  | 'prepare_storyboard_block'
  | 'prepare_scene_board'
  | 'regenerate_scene_board_zone'
  | 'generate_continuity_pack'
  | 'derive_continuity_structure'
  | 'derive_continuity_block'
  | 'generate_continuity_asset'
  | 'generate_keyframes'
  | 'generate_block_video'
  | 'generate_shot_video'
  | 'revise_sequence_animatic_shot'
  | 'repair_upstream_cache'
  | 'rerun_node_and_dependents'

export type OutputWorkflowRunIntentDefaults = {
  runScope: OutputWorkflowRunScope
  debugSkipVideoGeneration?: boolean
  cinematicVideoApproved?: boolean
  allowStaleUpstreamOutputs?: boolean
}

export function outputWorkflowRunIntentDefaults(intent: string | null | undefined): OutputWorkflowRunIntentDefaults | null {
  switch (intent) {
    case 'generate_director_plan':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: false,
      }
    case 'prepare_storyboard_block':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: false,
      }
    case 'prepare_scene_board':
    case 'regenerate_scene_board_zone':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: false,
      }
    case 'generate_scene_shot_plan':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: false,
      }
    case 'generate_continuity_pack':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: false,
      }
    case 'derive_continuity_structure':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'derive_continuity_block':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'generate_continuity_asset':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'generate_keyframes':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'generate_block_video':
      return {
        runScope: 'node_only',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: true,
        allowStaleUpstreamOutputs: true,
      }
    case 'generate_shot_video':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: true,
        allowStaleUpstreamOutputs: true,
      }
    case 'revise_sequence_animatic_shot':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'repair_upstream_cache':
      return {
        runScope: 'upstream_to_node',
        allowStaleUpstreamOutputs: true,
      }
    case 'rerun_node_and_dependents':
      return {
        runScope: 'node_and_downstream',
        allowStaleUpstreamOutputs: false,
      }
    default:
      return null
  }
}
