import type { OutputWorkflowNode, OutputWorkflowRunScope } from './outputWorkflow.ts'

export type OutputWorkflowNodeContract = {
  purpose: string
  label: string
  requiredInputs: string[]
  producedOutputs: string[]
  artifactRoles: string[]
  previewRoles: string[]
  recoveryStrategy: 'node_step_artifact' | 'node_step' | 'none'
  progressLabel: string
  providerBacked: boolean
  manualOnly: boolean
}

const cinematicSequenceContracts = [
  {
    purpose: 'sequence_animatic_scene_graph_assignment',
    label: 'Scene Graph Assignment',
    requiredInputs: ['screenplay', 'asset_pack', 'context'],
    producedOutputs: ['text', 'scenePackage', 'scene_package', 'scenePackages', 'scene_packages', 'sceneGraphDraft', 'scene_graph_draft', 'dialogueRows', 'dialogue_rows'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Assigning scene graph',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_package',
    label: 'Build Scene Packages',
    requiredInputs: ['screenplay', 'asset_pack', 'context'],
    producedOutputs: ['text', 'scenePackage', 'scene_package', 'scenePackages', 'scene_packages', 'sceneGraphDraft', 'scene_graph_draft', 'dialogueRows', 'dialogue_rows'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Parsing tagged screenplay scenes',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_plan_fanout',
    label: 'Queue Scene Shot Plans',
    requiredInputs: ['scene_package'],
    producedOutputs: ['text', 'dynamicGraphExpanded', 'graphExpanded', 'sceneCount'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Queueing scene shot planners',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_register',
    label: 'Register Scenes',
    requiredInputs: ['scene_package'],
    producedOutputs: ['text', 'scenes', 'sceneCount', 'scene_count'],
    artifactRoles: ['sequence_animatic_scene_index'],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Registering scenes',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_shot_plan',
    label: 'Scene Shot Plan',
    requiredInputs: ['scene_package', 'screenplay', 'asset_pack', 'context'],
    producedOutputs: ['text', 'scenePlan', 'scene_plan', 'sceneShotPlan', 'scene_shot_plan', 'shotContinuityPlan', 'shot_continuity_plan', 'directorPlan', 'director_plan'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Building scene shots and continuity',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_scene_plan_merge',
    label: 'Merge Scene Shot Plans',
    requiredInputs: ['scene_plan'],
    producedOutputs: ['text', 'directorPlan', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan', 'shot_plan', 'continuityGraphV2', 'continuity_graph_v2', 'shotBindings', 'shot_bindings'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Merging scene shot plans',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_manifest',
    label: 'Build Animatic Manifest',
    requiredInputs: ['director_plan'],
    producedOutputs: ['text', 'manifest', 'sequenceAnimaticManifest', 'shot_plan', 'animaticReferenceCatalog', 'animatic_reference_catalog', 'selectedVisualReferenceKeys', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Building animatic manifest',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_manifest_artifact',
    label: 'Register Animatic Manifest',
    requiredInputs: ['input'],
    producedOutputs: ['artifact', 'manifest'],
    artifactRoles: ['sequence_animatic_manifest'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Registering animatic manifest',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_director_plan',
    label: 'Shot Continuity Plan',
    requiredInputs: ['screenplay', 'asset_pack', 'context'],
    producedOutputs: ['text', 'directorPlan', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan', 'shot_plan', 'continuityGraphV2', 'continuity_graph_v2', 'shotBindings', 'shot_bindings'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Building shots, refs, and continuity',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_director_plan_artifact',
    label: 'Register Shot Continuity Plan',
    requiredInputs: ['director_plan'],
    producedOutputs: ['artifact', 'directorPlan', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan'],
    artifactRoles: ['sequence_animatic_director_plan'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving shot continuity plan',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_plan',
    label: 'Coverage Plan',
    requiredInputs: ['director_plan'],
    producedOutputs: ['text', 'coveragePlan', 'coverage_plan', 'coverageSetups', 'coverage_setups', 'coverageSetupByShotId', 'coverage_setup_by_shot_id', 'directorPlan', 'director_plan', 'shotContinuityPlan', 'shot_continuity_plan'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning coverage',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_orchestrator',
    label: 'Queue Animatic Blocks',
    requiredInputs: ['director_plan'],
    producedOutputs: ['orchestration', 'childRequests', 'startedRunIds'],
    artifactRoles: [],
    previewRoles: ['orchestration'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Queueing storyboard blocks',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_input',
    label: 'Continuity Batch Input',
    requiredInputs: [],
    producedOutputs: ['text', 'batch', 'target_nodes', 'asset_pack', 'referenceAssetKeys'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing continuity reference batch',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_prompt',
    label: 'Continuity Batch Prompt',
    requiredInputs: ['batch', 'target_nodes', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'asset_pack', 'referenceAssetKeys'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Writing continuity reference prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_image',
    label: 'Continuity Batch Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey', 'storagePath'],
    artifactRoles: ['sequence_animatic_continuity_batch_image'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating continuity reference grid',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_extract',
    label: 'Extract Continuity Batch',
    requiredInputs: ['batch', 'target_nodes', 'image'],
    producedOutputs: ['assets', 'assetStateByNodeId', 'asset_state_by_node_id'],
    artifactRoles: ['sequence_animatic_continuity_asset'],
    previewRoles: ['assets'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Extracting continuity reference crops',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_batch_artifact',
    label: 'Register Continuity Batch',
    requiredInputs: ['batch'],
    producedOutputs: ['artifact', 'assets', 'assetStateByNodeId', 'asset_state_by_node_id'],
    artifactRoles: ['sequence_animatic_continuity_asset_batch'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving continuity reference batch',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_block_input',
    label: 'Block Input',
    requiredInputs: [],
    producedOutputs: ['text', 'shot_plan', 'asset_pack', 'block'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing storyboard block',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_block_artifact',
    label: 'Register Block',
    requiredInputs: ['input'],
    producedOutputs: ['artifact', 'block', 'panels', 'videoPrompt'],
    artifactRoles: ['sequence_animatic_block_manifest'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving storyboard block manifest',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_input',
    label: 'Shot Input',
    requiredInputs: [],
    producedOutputs: ['shot', 'image', 'asset_pack', 'shot_plan'],
    artifactRoles: [],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot video input',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_input',
    label: 'Continuity Input',
    requiredInputs: [],
    producedOutputs: ['text', 'master_manifest', 'screenplay', 'shot_plan', 'shot_break_plan', 'asset_pack', 'animaticReferenceCatalog', 'animatic_reference_catalog', 'continuityPlannerContext', 'continuity_planner_context'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing continuity pack input',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_storyboard_prompt',
    label: 'Storyboard Prompt',
    requiredInputs: ['shot_plan', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'providerPrompt'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing storyboard prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_storyboard_sheet',
    label: 'Storyboard Sheet',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['cinematic_v3_storyboard_sheet', 'cinematic_v2_storyboard_sheet'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating storyboard sheet',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_panel_extract',
    label: 'Extract Panels',
    requiredInputs: ['image', 'shot_plan'],
    producedOutputs: ['panels', 'artifacts'],
    artifactRoles: ['cinematic_v3_storyboard_panel', 'cinematic_v2_storyboard_panel', 'sequence_animatic_block_panel'],
    previewRoles: ['panels'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Extracting storyboard panels',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_storyboard_group_video_prompt',
    label: 'Video Prompt',
    requiredInputs: ['shot_plan', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'providerPrompt'],
    artifactRoles: ['sequence_animatic_block_manifest'],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Preparing video prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'cinematic_v3_storyboard_group_video',
    label: 'Video',
    requiredInputs: ['prompt', 'references'],
    producedOutputs: ['video', 'assetKey'],
    artifactRoles: ['cinematic_v3_storyboard_group_video', 'sequence_animatic_block_video'],
    previewRoles: ['video'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating video',
    providerBacked: true,
    manualOnly: true,
  },
  {
    purpose: 'sequence_animatic_shot_video_prompt',
    label: 'Shot Video Prompt',
    requiredInputs: ['shot', 'asset_pack', 'references'],
    producedOutputs: ['text', 'prompt', 'providerPrompt'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot video prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_video',
    label: 'Shot Video',
    requiredInputs: ['prompt', 'references'],
    producedOutputs: ['video', 'assetKey'],
    artifactRoles: ['sequence_animatic_shot_video'],
    previewRoles: ['video'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating shot video',
    providerBacked: true,
    manualOnly: true,
  },
  {
    purpose: 'sequence_animatic_shared_asset_ref',
    label: 'Shared Asset Reference',
    requiredInputs: [],
    producedOutputs: ['reference', 'image', 'assetKey', 'artifact', 'status'],
    artifactRoles: ['sequence_animatic_coverage_anchor', 'sequence_animatic_shot_keyframe', 'sequence_animatic_continuity_asset', 'sequence_animatic_continuity_asset_batch', 'sequence_animatic_block_panel'],
    previewRoles: ['image', 'artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Resolving shared reference',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_reference_pack',
    label: 'Shot Reference Pack',
    requiredInputs: ['shot', 'asset_pack'],
    producedOutputs: ['text', 'shot', 'asset_pack', 'coverageAnchor', 'coverage_anchor', 'previousKeyframe', 'previous_keyframe', 'storyboardPanel', 'storyboard_panel', 'references', 'image', 'keyframe'],
    artifactRoles: [],
    previewRoles: ['image', 'text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot references',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_video_artifact',
    label: 'Register Shot Video',
    requiredInputs: ['video'],
    producedOutputs: ['artifact', 'video', 'assetKey'],
    artifactRoles: ['sequence_animatic_shot_video'],
    previewRoles: ['artifact', 'video'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving shot video',
    providerBacked: false,
    manualOnly: true,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_input',
    label: 'Zone Camera Grid Input',
    requiredInputs: [],
    producedOutputs: ['text', 'board', 'zoneCoverageBoard', 'zone_coverage_board', 'shots', 'coverageCells', 'coverage_cells', 'asset_pack', 'previous_board'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing zone camera grid',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_brief',
    label: 'Zone Camera Grid Brief',
    requiredInputs: ['board', 'coverage_cells', 'asset_pack'],
    producedOutputs: ['text', 'coverageBrief', 'coverage_brief', 'cameraGridBrief', 'camera_grid_brief', 'cells', 'board', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning zone camera grid',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_prompt',
    label: 'Zone Camera Grid Prompt',
    requiredInputs: ['coverage_brief', 'coverage_cells', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'board', 'coverageBrief', 'coverage_brief', 'asset_pack', 'referenceManifest'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing zone camera grid prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_image',
    label: 'Zone Camera Grid Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_zone_coverage_board_image'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating zone camera grid',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_extract',
    label: 'Extract Zone Camera Cells',
    requiredInputs: ['image', 'coverage_cells'],
    producedOutputs: ['cells', 'coverageCells', 'coverage_cells', 'cellAssetKeysByShotId', 'coverageCellByShotId'],
    artifactRoles: ['sequence_animatic_coverage_anchor'],
    previewRoles: ['image', 'text'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Extracting zone camera cells',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_zone_coverage_board_artifact',
    label: 'Register Zone Camera Grid',
    requiredInputs: ['image', 'cells'],
    producedOutputs: ['artifact', 'board', 'cells', 'coverageCellByShotId', 'assetKey'],
    artifactRoles: ['sequence_animatic_zone_coverage_board'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving zone camera grid',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_input',
    label: 'Coverage Anchor Input',
    requiredInputs: [],
    producedOutputs: ['text', 'coverageSetup', 'coverage_setup', 'shots', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing coverage anchor',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_prompt',
    label: 'Coverage Anchor Prompt',
    requiredInputs: ['coverage_setup', 'asset_pack', 'coverage_brief'],
    producedOutputs: ['text', 'prompt', 'coverageSetup', 'coverage_setup', 'coverageBrief', 'coverage_brief', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing coverage anchor prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_brief',
    label: 'Coverage Anchor Brief',
    requiredInputs: ['coverage_setup', 'shots', 'asset_pack'],
    producedOutputs: ['text', 'coverageBrief', 'coverage_brief', 'promptBrief', 'prompt_brief', 'coverageSetup', 'coverage_setup', 'shots', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning coverage anchor',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_image',
    label: 'Coverage Anchor Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_coverage_anchor_image'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating coverage anchor',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_coverage_anchor_artifact',
    label: 'Register Coverage Anchor',
    requiredInputs: ['coverage_setup'],
    producedOutputs: ['artifact', 'coverageAnchor', 'coverage_anchor', 'reference', 'image', 'keyframe', 'primaryReferenceImage'],
    artifactRoles: ['sequence_animatic_coverage_anchor'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving coverage anchor',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_planned_keyframe_input',
    label: 'Shot Keyframe Input',
    requiredInputs: [],
    producedOutputs: ['text', 'shot', 'coverageAnchor', 'coverage_anchor', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text', 'image'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot keyframe',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_planned_keyframe_prompt',
    label: 'Shot Keyframe Prompt',
    requiredInputs: ['shot', 'asset_pack'],
    producedOutputs: ['text', 'prompt', 'shot', 'coverageAnchor', 'coverage_anchor', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot keyframe prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_planned_keyframe_image',
    label: 'Shot Keyframe Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_shot_keyframe'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating shot keyframe',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_planned_keyframe_artifact',
    label: 'Register Shot Keyframe',
    requiredInputs: ['shot'],
    producedOutputs: ['artifact', 'shotKeyframe', 'shot_keyframe', 'image'],
    artifactRoles: ['sequence_animatic_shot_keyframe'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving shot keyframe',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_revision_input',
    label: 'Shot Revision Input',
    requiredInputs: [],
    producedOutputs: ['text', 'shot', 'baseShot', 'baseKeyframe', 'asset_pack', 'revisionPrompt'],
    artifactRoles: [],
    previewRoles: ['text', 'image'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing shot revision input',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_revision_plan',
    label: 'Revise Shot',
    requiredInputs: ['shot', 'revision_prompt'],
    producedOutputs: ['text', 'revisedShot', 'revisionPlan', 'diagnostics'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Rewriting shot',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_keyframe_prompt',
    label: 'Shot Keyframe Prompt',
    requiredInputs: ['revised_shot', 'asset_pack', 'base_keyframe'],
    producedOutputs: ['text', 'prompt', 'revisedShot', 'asset_pack'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing keyframe prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_keyframe_image',
    label: 'Shot Keyframe Image',
    requiredInputs: ['prompt', 'references'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_shot_keyframe'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating keyframe',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_shot_revision_artifact',
    label: 'Register Shot Revision',
    requiredInputs: ['revised_shot'],
    producedOutputs: ['artifact', 'revision', 'revisedShot', 'keyframe'],
    artifactRoles: ['sequence_animatic_shot_revision'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving shot revision',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_anchor_plan',
    label: 'Plan Continuity Anchors',
    requiredInputs: ['screenplay', 'shot_plan', 'asset_pack'],
    producedOutputs: ['text', 'continuityAnchorPlan', 'continuity_anchor_plan', 'characterAnchors', 'propAnchors', 'locationSpotAnchors', 'continuityGraphV2', 'continuity_graph_v2', 'locationSets', 'locationAngles', 'sceneGraph', 'shotContinuityMap', 'shotBindings', 'rejectedCandidates'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Finding reusable characters, props, and locations',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_seed_graph',
    label: 'Seed Continuity Scene Graph',
    requiredInputs: ['continuity_planner_context'],
    producedOutputs: ['text', 'continuityGraphV2', 'continuity_graph_v2'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Seeding continuity scene graph',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_block_plan',
    label: 'Plan Continuity Block',
    requiredInputs: ['continuity_graph_v2', 'continuity_planner_context'],
    producedOutputs: ['text', 'continuityBlockDelta', 'continuity_block_delta'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning block continuity',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_global_plan',
    label: 'Plan Continuity Structure',
    requiredInputs: ['continuity_graph_v2', 'continuity_planner_context'],
    producedOutputs: ['text', 'continuityBlockDelta', 'continuity_block_delta'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Planning global continuity structure',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_global_merge',
    label: 'Merge Continuity Structure',
    requiredInputs: ['continuity_graph_v2', 'continuity_block_delta'],
    producedOutputs: ['text', 'continuityGraphV2', 'continuity_graph_v2', 'continuityBlockDelta', 'continuity_block_delta', 'globalStructureState', 'coverage'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Merging global continuity structure',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_block_merge',
    label: 'Merge Continuity Block',
    requiredInputs: ['continuity_graph_v2', 'continuity_block_delta'],
    producedOutputs: ['text', 'continuityGraphV2', 'continuity_graph_v2'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Merging block continuity',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_graph_finalize',
    label: 'Finalize Continuity Scene Graph',
    requiredInputs: ['continuity_graph_v2'],
    producedOutputs: ['text', 'continuityGraphV2', 'continuity_graph_v2', 'locationSets', 'locationAngles', 'sceneGraph', 'shotContinuityMap', 'shotBindings', 'assetAnchors', 'rejectedCandidates'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Finalizing continuity scene graph',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_structure_artifact',
    label: 'Save Continuity Structure',
    requiredInputs: ['continuity_graph_v2'],
    producedOutputs: ['artifact', 'continuityPack', 'continuity_pack', 'continuityGraphV2', 'continuity_graph_v2', 'shotBindings', 'blockStates', 'pendingDeltas', 'globalStructureState', 'coverage', 'assetStateByNodeId', 'visualDependencyEdges', 'assetGenerationStatus'],
    artifactRoles: ['sequence_animatic_continuity_pack'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving continuity structure',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_asset_input',
    label: 'Continuity Asset Input',
    requiredInputs: [],
    producedOutputs: ['text', 'continuityPack', 'continuity_pack', 'targetNode', 'target_node', 'relevantShots', 'relevant_shots', 'shotBindings', 'shot_bindings', 'assetPack', 'asset_pack', 'referenceAssetKeys', 'reference_asset_keys'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Collecting continuity asset context',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_asset_prompt',
    label: 'Continuity Asset Prompt',
    requiredInputs: ['target_node'],
    producedOutputs: ['text', 'prompt', 'assetPack', 'asset_pack', 'referenceAssetKeys', 'reference_asset_keys', 'targetNode', 'target_node', 'relevantShots', 'relevant_shots'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing continuity asset prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_asset_image',
    label: 'Continuity Asset Image',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_continuity_asset_image'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating continuity asset',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_asset_artifact',
    label: 'Register Continuity Asset',
    requiredInputs: ['image', 'target_node'],
    producedOutputs: ['artifact', 'continuityAsset', 'continuity_asset', 'reference', 'assetState', 'asset_state', 'assetStateByNodeId', 'asset_state_by_node_id', 'image', 'keyframe', 'primaryReferenceImage'],
    artifactRoles: ['sequence_animatic_continuity_asset'],
    previewRoles: ['artifact', 'image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving continuity asset',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_character_anchor_atlas_prompt',
    label: 'Character Anchor Atlas Prompt',
    requiredInputs: ['continuity_anchor_plan'],
    producedOutputs: ['text', 'prompt', 'anchors', 'atlasLayout'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing temporary character atlas prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_character_anchor_atlas',
    label: 'Character Anchor Atlas',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_character_anchor_atlas'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating temporary character atlas',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_character_anchor_extract',
    label: 'Extract Character Anchors',
    requiredInputs: ['image', 'continuity_anchor_plan'],
    producedOutputs: ['anchors', 'artifacts'],
    artifactRoles: ['sequence_animatic_character_anchor'],
    previewRoles: ['anchors'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Splitting character refs',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_prop_anchor_atlas_prompt',
    label: 'Prop Anchor Atlas Prompt',
    requiredInputs: ['continuity_anchor_plan'],
    producedOutputs: ['text', 'prompt', 'anchors', 'atlasLayout'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing prop atlas prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_prop_anchor_atlas',
    label: 'Prop Anchor Atlas',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_prop_anchor_atlas'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating prop reference atlas',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_prop_anchor_extract',
    label: 'Extract Prop Anchors',
    requiredInputs: ['image', 'continuity_anchor_plan'],
    producedOutputs: ['anchors', 'artifacts'],
    artifactRoles: ['sequence_animatic_prop_anchor'],
    previewRoles: ['anchors'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Splitting prop refs',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_location_anchor_atlas_prompt',
    label: 'Location Anchor Atlas Prompt',
    requiredInputs: ['continuity_anchor_plan'],
    producedOutputs: ['text', 'prompt', 'anchors', 'atlasLayout'],
    artifactRoles: [],
    previewRoles: ['text'],
    recoveryStrategy: 'node_step',
    progressLabel: 'Preparing location spot atlas prompt',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_location_anchor_atlas',
    label: 'Location Anchor Atlas',
    requiredInputs: ['prompt'],
    producedOutputs: ['image', 'assetKey'],
    artifactRoles: ['sequence_animatic_location_anchor_atlas'],
    previewRoles: ['image'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Generating location spot atlas',
    providerBacked: true,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_location_anchor_extract',
    label: 'Extract Location Anchors',
    requiredInputs: ['image', 'continuity_anchor_plan'],
    producedOutputs: ['anchors', 'artifacts'],
    artifactRoles: ['sequence_animatic_location_anchor'],
    previewRoles: ['anchors'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Splitting location refs',
    providerBacked: false,
    manualOnly: false,
  },
  {
    purpose: 'sequence_animatic_continuity_artifact',
    label: 'Register Continuity Pack',
    requiredInputs: ['continuity_anchor_plan'],
    producedOutputs: ['artifact', 'continuityPack', 'characterAnchors', 'propAnchors', 'locationSpotAnchors'],
    artifactRoles: ['sequence_animatic_continuity_pack'],
    previewRoles: ['artifact'],
    recoveryStrategy: 'node_step_artifact',
    progressLabel: 'Saving continuity pack',
    providerBacked: false,
    manualOnly: false,
  },
] satisfies OutputWorkflowNodeContract[]

export const outputWorkflowNodeContractsByPurpose = new Map<string, OutputWorkflowNodeContract>(
  cinematicSequenceContracts.map((contract) => [contract.purpose, contract]),
)

export function outputWorkflowNodePurpose(nodeOrConfig: Pick<OutputWorkflowNode, 'config'> | Record<string, unknown> | null | undefined) {
  const config = nodeOrConfig && 'config' in nodeOrConfig
    ? nodeOrConfig.config
    : nodeOrConfig
  if (!config || typeof config !== 'object' || Array.isArray(config)) return ''
  const record = config as Record<string, unknown>
  return typeof record.purpose === 'string' && record.purpose.trim()
    ? record.purpose.trim()
    : typeof record.role === 'string'
      ? record.role.trim()
      : ''
}

export function getOutputWorkflowNodeContract(nodeOrConfig: Pick<OutputWorkflowNode, 'config'> | Record<string, unknown> | null | undefined) {
  const purpose = outputWorkflowNodePurpose(nodeOrConfig)
  return purpose ? outputWorkflowNodeContractsByPurpose.get(purpose) ?? null : null
}

export type OutputWorkflowRunIntent =
  | 'generate_director_plan'
  | 'prepare_storyboard_block'
  | 'generate_continuity_pack'
  | 'derive_continuity_structure'
  | 'derive_continuity_block'
  | 'generate_continuity_asset'
  | 'generate_keyframes'
  | 'generate_block_video'
  | 'generate_shot_video'
  | 'revise_sequence_animatic_shot'
  | 'repair_upstream_cache'
  | 'rerun_node_and_dependents'

export type OutputWorkflowRunIntentDefaults = {
  runScope: OutputWorkflowRunScope
  debugSkipVideoGeneration?: boolean
  cinematicVideoApproved?: boolean
  allowStaleUpstreamOutputs?: boolean
}

export function outputWorkflowRunIntentDefaults(intent: string | null | undefined): OutputWorkflowRunIntentDefaults | null {
  switch (intent) {
    case 'generate_director_plan':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: false,
      }
    case 'prepare_storyboard_block':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: false,
      }
    case 'generate_scene_shot_plan':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: false,
      }
    case 'generate_continuity_pack':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: false,
      }
    case 'derive_continuity_structure':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'derive_continuity_block':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: true,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'generate_continuity_asset':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'generate_keyframes':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'generate_block_video':
      return {
        runScope: 'node_only',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: true,
        allowStaleUpstreamOutputs: true,
      }
    case 'generate_shot_video':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: true,
        allowStaleUpstreamOutputs: true,
      }
    case 'revise_sequence_animatic_shot':
      return {
        runScope: 'upstream_to_node',
        debugSkipVideoGeneration: false,
        cinematicVideoApproved: false,
        allowStaleUpstreamOutputs: true,
      }
    case 'repair_upstream_cache':
      return {
        runScope: 'upstream_to_node',
        allowStaleUpstreamOutputs: true,
      }
    case 'rerun_node_and_dependents':
      return {
        runScope: 'node_and_downstream',
        allowStaleUpstreamOutputs: false,
      }
    default:
      return null
  }
}
