// Live drag ghosts for interior walls and outline sculpting (moved from CityStudio.tsx).
import {Html} from '@react-three/drei';
import {DoubleSide} from 'three';
import {sculptFloorBottom,sculptFloorTop,type SculptVolume} from '../../../domain/citySculpt';
import {editableOutline} from '../../../domain/cityStudioOutlineEdit';
import type {StudioOutlineGhost,StudioWallGhost} from '../useStudioInteraction';

export function WallDragGhost({ghost}:{ghost:StudioWallGhost}){const dx=ghost.b[0]-ghost.a[0],dz=ghost.b[1]-ghost.a[1],length=Math.hypot(dx,dz),angle=Math.atan2(-dz,dx),count=Math.max(1,Math.round(length/2)),colour=ghost.valid?'#83bd97':'#d7986d';return <group name="interior-wall-drag-preview" position={[(ghost.a[0]+ghost.b[0])/2,ghost.bottom+ghost.height/2,(ghost.a[1]+ghost.b[1])/2]} rotation={[0,angle,0]} raycast={()=>null}>{length>.01&&<><mesh><boxGeometry args={[length,ghost.height,.16]}/><meshBasicMaterial color={colour} transparent opacity={.43} depthWrite={false}/></mesh>{Array.from({length:count-1},(_,i)=><mesh key={i} position={[-length/2+(i+1)*length/count,0,.086]}><boxGeometry args={[.025,ghost.height,.012]}/><meshBasicMaterial color="#fff8e8" transparent opacity={.72} depthWrite={false}/></mesh>)}</>}<mesh position={[length/2,0,0]}><sphereGeometry args={[.13,10,8]}/><meshBasicMaterial color={colour} depthTest={false}/></mesh><Html center position={[length/2,ghost.height/2+.38,0]} style={{pointerEvents:'none'}}><span className="studio-drag-label">{ghost.reason||`${length.toFixed(1)} m · ~${count} ${count===1?'bay':'bays'}`}</span></Html></group>;}
const GUIDE_COLOURS={align:'#8fd0ff',angle:'#f3c45b',plot:'#ff9a7a'} as const;
/** A thin bar between two building-local points at height y (outline loops and snap guides). */
function EdgeBar({a,b,y,color,width=.06,opacity=1}:{a:[number,number];b:[number,number];y:number;color:string;width?:number;opacity?:number}){const dx=b[0]-a[0],dz=b[1]-a[1],l=Math.hypot(dx,dz);if(l<.02)return null;return <mesh position={[(a[0]+b[0])/2,y,(a[1]+b[1])/2]} rotation={[0,Math.atan2(-dz,dx),0]} raycast={()=>null} renderOrder={6}><boxGeometry args={[l,width,width]}/><meshBasicMaterial color={color} transparent opacity={opacity} depthTest={false} depthWrite={false}/></mesh>;}
/** The selected part outline at its top while the outline tool is active. */
export function OutlineLoop({volume,groundHeight,upperHeight=3,color='#fff4d6'}:{volume:SculptVolume;groundHeight:number;upperHeight?:number;color?:string}){const o=editableOutline(volume);if(!o)return null;const y=sculptFloorTop(volume.startFloor+volume.spanFloors-1,groundHeight,upperHeight)+.3,n=o.points.length;return <group name="outline-loop">{o.points.map((p,i)=><EdgeBar key={i} a={p} b={o.points[(i+1)%n]} y={y} color={color} opacity={.85}/>)}</group>;}
export function OutlineDragGhost({ghost,groundHeight,upperHeight=3}:{ghost:StudioOutlineGhost;groundHeight:number;upperHeight?:number}){const volume=ghost.volume,bottom=sculptFloorBottom(volume.startFloor,groundHeight,upperHeight),top=sculptFloorTop(volume.startFloor+volume.spanFloors-1,groundHeight,upperHeight),colour=ghost.valid?'#82ba91':'#e0584a',o=editableOutline(volume),n=o?.points.length??0;
 return <group name="outline-drag-preview" raycast={()=>null}>{o?.points.map((p,i)=>{const q=o.points[(i+1)%n],length=Math.hypot(q[0]-p[0],q[1]-p[1]),angle=Math.atan2(-(q[1]-p[1]),q[0]-p[0]),count=Math.max(1,Math.round(length/2));return <group key={`${o.ids[i]}/${i}`} position={[(p[0]+q[0])/2,(bottom+top)/2,(p[1]+q[1])/2]} rotation={[0,angle,0]}><mesh><boxGeometry args={[length,top-bottom,.08]}/><meshBasicMaterial color={colour} transparent opacity={ghost.valid?.27:.4} depthWrite={false} depthTest={false} side={DoubleSide}/></mesh>{Array.from({length:count-1},(_,k)=><mesh key={k} position={[-length/2+(k+1)*length/count,0,.05]}><boxGeometry args={[.025,top-bottom,.025]}/><meshBasicMaterial color="#fff8e8" transparent opacity={.65} depthWrite={false}/></mesh>)}</group>;})}
  {o?.points.map((p,i)=><EdgeBar key={`top/${i}`} a={p} b={o.points[(i+1)%n]} y={top+.3} color={colour} width={.08}/>)}
  {ghost.guides?.map((g,i)=><EdgeBar key={`guide/${i}`} a={g.a} b={g.b} y={top+.32} color={GUIDE_COLOURS[g.kind]} width={.045} opacity={.9}/>)}
  {ghost.labels?.map((l,i)=><Html key={`label/${i}`} center position={[l.x,top+.75,l.z]} style={{pointerEvents:'none'}} zIndexRange={[44,24]}><span className={`studio-drag-label${l.tone==='warn'?' is-warn':''}`}>{l.text}</span></Html>)}
  {ghost.reason&&<Html center position={[volume.x,top+1.3,volume.z]} style={{pointerEvents:'none'}}><span className="studio-drag-label is-refused" role="status">{ghost.reason}</span></Html>}</group>;}
