// Live drag ghosts for interior walls and outline sculpting (moved from CityStudio.tsx).
import {Html} from '@react-three/drei';
import {DoubleSide} from 'three';
import {sculptFloorBottom,sculptFloorTop} from '../../../domain/citySculpt';
import {outlineEdges} from '../../../domain/cityStudioOutline';
import type {StudioOutlineGhost,StudioWallGhost} from '../useStudioInteraction';

export function WallDragGhost({ghost}:{ghost:StudioWallGhost}){const dx=ghost.b[0]-ghost.a[0],dz=ghost.b[1]-ghost.a[1],length=Math.hypot(dx,dz),angle=Math.atan2(-dz,dx),count=Math.max(1,Math.round(length/2)),colour=ghost.valid?'#83bd97':'#d7986d';return <group name="interior-wall-drag-preview" position={[(ghost.a[0]+ghost.b[0])/2,ghost.bottom+ghost.height/2,(ghost.a[1]+ghost.b[1])/2]} rotation={[0,angle,0]} raycast={()=>null}>{length>.01&&<><mesh><boxGeometry args={[length,ghost.height,.16]}/><meshBasicMaterial color={colour} transparent opacity={.43} depthWrite={false}/></mesh>{Array.from({length:count-1},(_,i)=><mesh key={i} position={[-length/2+(i+1)*length/count,0,.086]}><boxGeometry args={[.025,ghost.height,.012]}/><meshBasicMaterial color="#fff8e8" transparent opacity={.72} depthWrite={false}/></mesh>)}</>}<mesh position={[length/2,0,0]}><sphereGeometry args={[.13,10,8]}/><meshBasicMaterial color={colour} depthTest={false}/></mesh><Html center position={[length/2,ghost.height/2+.38,0]} style={{pointerEvents:'none'}}><span className="studio-drag-label">{ghost.reason||`${length.toFixed(1)} m · ~${count} ${count===1?'bay':'bays'}`}</span></Html></group>;}
export function OutlineDragGhost({ghost,groundHeight,upperHeight=3}:{ghost:StudioOutlineGhost;groundHeight:number;upperHeight?:number}){const volume=ghost.volume,bottom=sculptFloorBottom(volume.startFloor,groundHeight,upperHeight),top=sculptFloorTop(volume.startFloor+volume.spanFloors-1,groundHeight,upperHeight),colour=ghost.valid?'#82ba91':'#d7986d';return <group name="outline-drag-preview" raycast={()=>null}>{outlineEdges(volume).map(edge=>{const angle=Math.atan2(-(edge.b[1]-edge.a[1]),edge.b[0]-edge.a[0]),count=Math.max(1,Math.round(edge.length/2));return <group key={edge.side} position={[(edge.a[0]+edge.b[0])/2,(bottom+top)/2,(edge.a[1]+edge.b[1])/2]} rotation={[0,angle,0]}><mesh><boxGeometry args={[edge.length,top-bottom,.08]}/><meshBasicMaterial color={colour} transparent opacity={.27} depthWrite={false} depthTest={false} side={DoubleSide}/></mesh>{Array.from({length:count-1},(_,i)=><mesh key={i} position={[-edge.length/2+(i+1)*edge.length/count,0,.05]}><boxGeometry args={[.025,top-bottom,.025]}/><meshBasicMaterial color="#fff8e8" transparent opacity={.65} depthWrite={false}/></mesh>)}</group>;})}{ghost.reason&&<Html center position={[volume.x,top+1,volume.z]} style={{pointerEvents:'none'}}><span className="studio-drag-label">{ghost.reason}</span></Html>}</group>;}
