export const aiGenerationSettings = {
  outputWorkflow: {
    imageQualityDefaults: {
      default: 'medium',
      characterConceptArt: 'low',
      conceptArt: 'medium',
      poster: 'medium',
      comic: 'medium',
      ebookCover: 'medium',
    },
    imageOutputFormatDefault: 'webp',
    entityReferenceSheetQuality: 'medium',
    entityReferenceSheetOutputFormat: 'webp',
    entityReferenceSheetImageSizes: {
      character: { width: 2048, height: 1536 },
      location: { width: 2048, height: 2048 },
      group: { width: 2048, height: 2048 },
      item: { width: 2048, height: 2048 },
    },
    cinematicStoryboardImageQuality: 'medium',
    cinematicReferenceModeDefault: 'shot_reference_sheet',
    debugCinematicStoryboardStyleSafeModeDefault: false,
    debugCinematicStoryboardStylePrompt: 'painterly comic-book cinematic production art, expressive ink-and-paint rendering, premium graphic novel storyboard look, not photorealistic',
    debugSkipVideoGenerationDefault: true,
    videoProviderDefault: 'muapi',
    videoMuapiModel: 'seedance-2.0-omni-reference',
    videoFalModel: 'bytedance/seedance-2.0/fast/reference-to-video',
    videoFalHighResolutionModel: 'bytedance/seedance-2.0/reference-to-video',
  },
} as const
