import { FlexibleStudio } from './FlexibleStudio'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowLeftIcon, PlayIcon, FloppyDiskIcon, GraphIcon } from '@phosphor-icons/react'
import type { ProjectSnapshot } from '../../domain/graphcore'
import { freezeGraph, graphDiff, validateGraph, type StudioGraph as Graph } from '../../domain/game/animation-studio/graph'
import { studioTemplate } from '../../domain/game/animation-studio/templates'
import { readStudio, sendStudio, recoverStudio, type StudioData } from '../../data/animationStudioRepository'
import { StudioGraph } from './StudioGraph'
import { StudioPreview } from './StudioPreview'
import { AnimationPreview } from '../game-builder/AnimationPreview'
import { sendMechanic } from '../../data/mechanicRepository'
import type { StudioCommand } from '../../domain/game/animation-studio/protocol'
import '../../styles/features/animation-studio.css'

const empty:StudioData={library:[],workspace:null,jobs:[],candidates:[],reviews:[],sources:[],game:null}
export function LegacyAnimationStudio({snapshot,canRun,onBack}:{snapshot:ProjectSnapshot;canRun:boolean;onBack:()=>void}){
 const [graph,setGraph]=useState<Graph>(()=>studioTemplate()),[data,setData]=useState<StudioData>(empty),[workspaceId,setWorkspaceId]=useState<string>(()=>crypto.randomUUID())
 const [selected,setSelected]=useState<string|null>('sword.strike_1'),[active,setActive]=useState('upright.idle'),[prompt,setPrompt]=useState('Create an alert swordsman with neutral walking, sword combat footwork and a forehand → backhand → advancing finisher combo.')
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[proposal,setProposal]=useState<Graph|null>(null),[dependencyView,setDependencyView]=useState(false)
 const [selectedIds,setSelectedIds]=useState<string[]>([]),[maximum,setMaximum]=useState(0),[actorId,setActorId]=useState(''),[targetRevision,setTargetRevision]=useState(0)
 const node=graph.nodes.find(n=>n.id===selected),stance=graph.stances.find(s=>s.id===node?.group)
 const draftId=data.workspace?.draft_id??snapshot.draft.id,revision=data.workspace?.revision??0
 useEffect(()=>{if(data.game){setTargetRevision(data.game.revision);setActorId(id=>data.game!.actors.some(a=>a.id===id)?id:data.game!.actors[0]?.id??'')}},[data.game])
 const dirty=JSON.stringify(graph)!==JSON.stringify(data.workspace?.graph)
 const reload=useCallback(async(id?:string,replace=false)=>{
  if(!canRun)return
  const next=await readStudio(snapshot.project.id,snapshot.draft.id,id);setData(next)
  if(replace&&next.workspace)setGraph(next.workspace.graph)
 },[canRun,snapshot.project.id,snapshot.draft.id])
 useEffect(()=>{let alive=true;if(canRun)readStudio(snapshot.project.id,snapshot.draft.id).then(d=>{if(alive)setData(d)}).catch(e=>{if(alive)setError(String(e))});return()=>{alive=false}},[canRun,snapshot.project.id,snapshot.draft.id])
 useEffect(()=>{
  if(!data.workspace||!data.jobs.some(j=>['queued','running'].includes(j.status)))return
  const timer=setTimeout(()=>{void reload(workspaceId).catch(e=>setError(String(e)))},3500)
  return()=>clearTimeout(timer)
 },[data,reload,workspaceId])
 const run=async(label:string,task:()=>Promise<void>)=>{if(busy)return;setBusy(label);setError('');setNotice('');try{await task()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 function base(){return{projectId:snapshot.project.id,draftId,workspaceId,expectedRevision:revision,idempotencyKey:crypto.randomUUID()}}
 async function command(command:StudioCommand,replace=false){await sendStudio(command);await reload(workspaceId,replace)}
 const clips=useMemo(()=>data.candidates.flatMap(c=>c.clip&&c.url&&graph.nodes.some(n=>n.clipId===c.id)?[{clip:c.clip,url:c.url}]:[]),[data.candidates,graph])
 const statuses=useMemo(()=>Object.fromEntries(graph.nodes.map(n=>[n.id,data.jobs.find(j=>j.nodeId===n.id)?.status??(n.clipId?'Reviewed':'Planned')])),[graph,data.jobs])
 const errors=validateGraph(graph),selectedCandidates=data.candidates.filter(c=>c.nodeId===selected)
 const editNode=(patch:Partial<NonNullable<typeof node>>)=>setGraph(g=>({...g,nodes:g.nodes.map(n=>n.id===selected?{...n,...patch}:n)}))
 return <main className="animation-studio">
  <header className="studio-heading"><div><button className="studio-back" onClick={onBack}><ArrowLeftIcon size={16}/>Game workspace</button><p className="studio-eyebrow">SYNARC / MOTION</p><h1>Animation studio</h1><p>Describe a character’s movement. Shape the transitions. Play the result.</p></div><span className="studio-revision">{data.workspace?`Revision ${revision}${dirty?' · Unsaved changes':''}`:'New animation graph'}</span></header>
  <div className="studio-toolbar"><label>Animation library<select value={data.workspace?.id??''} onChange={e=>{const id=e.target.value;if(id)void run('Loading',async()=>{setWorkspaceId(id);await reload(id,true)})}}><option value="">New graph</option>{data.library.filter(w=>w.graph.version===2).map(w=><option key={w.id} value={w.id}>{w.graph.name}</option>)}</select></label>
   <button onClick={()=>{setWorkspaceId(crypto.randomUUID());setData(d=>({...empty,library:d.library}));setGraph(studioTemplate());setNotice('New graph ready')}} disabled={!!busy}>New graph</button>
   <label>Starting template<select defaultValue="sword" onChange={e=>setProposal(studioTemplate(e.target.value==='sword'))}><option value="sword">Locomotion + sword</option><option value="neutral">Neutral locomotion</option></select></label>
   <button disabled={!canRun||!!busy||!!errors.length} onClick={()=>void run('Saving',async()=>{await command({...base(),action:'save',graph:await freezeGraph(graph)},true);setNotice('Saved immutable graph revision')})}><FloppyDiskIcon size={17}/>Save revision</button>
  </div>
  <section className="studio-prompt"><label htmlFor="motion-prompt">Describe the movement system</label><div><textarea id="motion-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={4000}/><button disabled={!canRun||!data.workspace||dirty||!!busy||prompt.length<10} onClick={()=>void run('Planning',async()=>{await command({...base(),action:'plan',prompt,nodeIds:selectedIds});setNotice('Planning queued. The proposal will appear below for review.')})}><GraphIcon size={18}/>Plan graph</button></div><small>{selectedIds.length?`Refine ${selectedIds.length} selected nodes`:'Plan the complete graph'} · Planning uses the existing design-credit reservation.</small></section>
  {error&&<div role="alert" className="studio-error">{error}<button onClick={()=>void run('Recovering',async()=>{await recoverStudio(workspaceId);await reload(workspaceId,true)})}>Recover pending command</button></div>}
  {notice&&<p role="status">{notice}</p>}{busy&&<p role="status">{busy}…</p>}
  {data.jobs.filter(j=>j.graph).map(j=><div key={j.id} className="studio-proposal">Graph proposal from revision {j.sourceRevision}<button disabled={j.sourceRevision!==revision} onClick={()=>setProposal(j.graph)}>Review proposal</button></div>)}
  {proposal&&<section className="studio-proposal"><strong>Review graph changes</strong><p>{graphDiff(graph,proposal).join(', ')||'No node changes'}</p><button onClick={()=>{setGraph(proposal);setProposal(null)}}>Use proposal</button><button onClick={()=>setProposal(null)}>Discard</button></section>}
  <div className="studio-workbench"><section className="studio-canvas-panel"><div className="studio-panel-heading"><strong>{graph.name}</strong><label><input type="checkbox" checked={dependencyView} onChange={e=>setDependencyView(e.target.checked)}/>Generation dependencies</label></div><StudioGraph graph={graph} selected={selected} active={active} onSelect={setSelected} statuses={statuses} dependencies={dependencyView}/></section>
   <aside className="studio-inspector">{node&&<><p className="studio-eyebrow">{node.kind} / {node.id}</p><h2>{node.label}</h2><label><input type="checkbox" checked={selectedIds.includes(node.id)} onChange={e=>setSelectedIds(ids=>e.target.checked?[...ids,node.id]:ids.filter(id=>id!==node.id))}/>Select for generation / refinement</label><label>Label<input value={node.label} onChange={e=>editNode({label:e.target.value})}/></label><label>Motion description<textarea aria-label="Motion description" value={node.description} onChange={e=>editNode({description:e.target.value})}/></label><label>Duration (seconds)<input type="number" min={.5} max={8} step={.05} value={node.duration} onChange={e=>editNode({duration:Number(e.target.value)})}/></label>
    <p className="studio-hint">Entry: {node.entry}<br/>Exit: {node.exit}</p>
    {stance&&<><h3>Shared stance</h3><label>Style description<textarea aria-label="Style description" value={stance.description} onChange={e=>setGraph(g=>({...g,stances:g.stances.map(s=>s.id===stance.id?{...s,description:e.target.value}:s)}))}/></label><label>Guard height<input type="range" min={-.15} max={.15} step={.01} value={stance.guardHeight} onChange={e=>setGraph(g=>({...g,stances:g.stances.map(s=>s.id===stance.id?{...s,guardHeight:Number(e.target.value)}:s)}))}/></label></>}
    <label>Entry pose source<select value={graph.dependencies.find(d=>d.node===node.id)?.candidateId??''} onChange={e=>{const c=data.candidates.find(c=>c.id===e.target.value);setGraph(g=>({...g,dependencies:[...g.dependencies.filter(d=>d.node!==node.id),...(c?[{node:node.id,predecessor:c.nodeId,candidateId:c.id}]:[])]}))}}><option value="">Shared boundary pose</option>{data.candidates.filter(c=>c.clip&&graph.transitions.some(t=>t.from===c.nodeId&&t.to===node.id)).map(c=><option key={c.id} value={c.id}>{c.nodeId} · {c.id.slice(0,8)}</option>)}</select></label><h3>Transitions</h3>{graph.transitions.filter(t=>t.from===node.id).map(t=><div className="studio-transition" key={t.id}><strong>{t.event} → {t.to}</strong><label>Blend seconds<input type="number" min={0} max={.3} step={.01} value={t.blendSeconds} onChange={e=>setGraph(g=>({...g,transitions:g.transitions.map(x=>x.id===t.id?{...x,blendSeconds:Number(e.target.value)}:x)}))}/></label><label>Earliest phase<input type="number" min={0} max={1} step={.05} value={t.earliest} onChange={e=>setGraph(g=>({...g,transitions:g.transitions.map(x=>x.id===t.id?{...x,earliest:Number(e.target.value)}:x)}))}/></label></div>)}
   </>}</aside>
  </div>
  <div className="studio-bottom"><StudioPreview graph={graph} clips={clips} onActive={setActive}/><section className="studio-generation"><h2>Generate & review</h2><p>Generate missing motions in the selected nodes. Every result remains a candidate until reviewed.</p><button onClick={()=>setSelectedIds(graph.nodes.filter(n=>!n.clipId).map(n=>n.id))}>Select missing motions</button><label>Maximum reservation (cents)<input type="number" min={0} max={2500} value={maximum} onChange={e=>setMaximum(Number(e.target.value))}/></label><button disabled={!canRun||dirty||!selectedIds.length||maximum<=0||!!busy} onClick={()=>void run('Queuing motions',()=>command({...base(),action:'generate',nodeIds:selectedIds,maxReservationCents:maximum}))}><PlayIcon size={17}/>Generate {selectedIds.length||'selected'} motions</button>
    <div className="studio-jobs">{data.jobs.map(j=><div key={j.id}><strong>{j.nodeId??'Graph plan'}</strong><span>{j.status} · {j.phase}</span>{j.error&&<p>{j.error}</p>}{['queued','running','attention'].includes(j.status)&&<button disabled={!!busy} onClick={()=>void run('Cancelling',()=>command({...base(),action:'cancel',jobId:j.id}))}>Cancel</button>}{j.status==='failed'&&j.nodeId&&<button disabled={!!busy} onClick={()=>void run('Retrying processing',()=>command({...base(),action:'retry',jobId:j.id}))}>Retry saved source</button>}</div>)}</div>
    {node?.kind==='locomotion'&&node.group==='upright'&&<label>Reuse saved Kimodo source<select value="" disabled={dirty||!!busy} onChange={e=>{const candidateId=e.target.value;if(candidateId)void run('Re-baking source',()=>command({...base(),action:'import_source',nodeId:node.id,candidateId}))}}><option value="">Choose a compatible source (no inference)</option>{data.sources.filter(c=>c.clip.state===node.role&&!c.clip.provenance).map(c=><option key={c.id} value={c.id}>{c.clip.state} · {c.id.slice(0,8)}</option>)}</select></label>}<h3>{node?.label} candidates</h3>{!selectedCandidates.length&&<p className="studio-hint">No candidates for this node yet. Its procedural preview is available now.</p>}{selectedCandidates.map(c=><div className="studio-candidate" key={c.id}>{c.clip&&c.url&&<AnimationPreview url={c.url} clip={c.clip} equipment={stance?.equipment==='one_handed_sword'?'one_handed_sword':undefined}/>}<p>{c.diagnostics.failures?.join('; ')||'Technical validation passed. Review the motion and connected transitions.'}</p><button disabled={!c.clip||!!busy||dirty} onClick={()=>void run('Accepting candidate',()=>command({...base(),action:'review_clip',nodeId:c.nodeId,candidateId:c.id,decision:'accepted'},true))}>Accept candidate</button><button disabled={!!busy} onClick={()=>void run('Rejecting candidate',()=>command({...base(),action:'review_clip',nodeId:c.nodeId,candidateId:c.id,decision:'rejected'}))}>Reject</button></div>)}
   </section></div>
  <section className="studio-publish"><h2>Use in a game</h2><p>Review the complete graph, then bind its immutable revision to a compatible Fabric actor. Missing combat mechanics need a separate reviewed proposal.</p><button disabled={dirty||!!busy||graph.nodes.some(n=>!n.clipId)} onClick={()=>void run('Reviewing graph',()=>command({...base(),action:'review_graph'}))}>Accept graph & transitions</button><label>Target actor<select value={actorId} onChange={e=>setActorId(e.target.value)}><option value="">Select a game actor</option>{data.game?.actors.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><span>Game revision {targetRevision}</span><button disabled={!actorId||!!busy||!canRun} onClick={()=>void run('Proposing mechanics',async()=>{await sendMechanic({projectId:snapshot.project.id,draftId:snapshot.draft.id,expectedRevision:targetRevision,idempotencyKey:crypto.randomUUID(),action:'plan_mechanic',actorDefinition:actorId,surfaces:[],prompt:'Propose a three-strike one-handed sword combo for this actor. Preserve sibling systems. Match these animation timings exactly: '+graph.nodes.filter(n=>n.kind==='action').map(n=>n.label+': duration '+n.duration+' seconds; impact/windup '+(n.impact*n.duration)+' seconds, active 0.1 seconds, recovery '+(n.duration-n.impact*n.duration-.1)+' seconds.').join(' ')});setNotice('Mechanic proposal queued. Open the game Mechanics workspace to review and materialize it.')})}>Propose matching combo mechanics</button><button disabled={dirty||!actorId||!!busy||!data.reviews.some(r=>r.revision===revision)} onClick={()=>void run('Attaching graph',async()=>{await command({...base(),action:'attach',targetDraftId:snapshot.draft.id,targetRevision,actorId});setNotice('Graph attached. Build and review the game before publication.')})}>Attach to actor</button></section>
  <details><summary>Input bindings</summary>{(['attack','toggle_combat']as const).map(key=><label key={key}>{key.replaceAll('_',' ')}<select value={graph.inputs[key]} onChange={e=>setGraph(g=>({...g,inputs:{...g.inputs,[key]:e.target.value}}))}>{'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').filter(c=>!'WASD'.includes(c)).map(c=><option key={c} value={`Key${c}`}>{c}</option>)}</select></label>)}</details>
  {errors.length>0&&<div role="alert">{errors.map(e=><p key={e}>{e}</p>)}</div>}{graph.gaps.length>0&&<section><h3>Requested capabilities</h3>{graph.gaps.map(g=><p key={g}>{g}</p>)}</section>}
 </main>
}




export function AnimationStudio(props:Parameters<typeof LegacyAnimationStudio>[0]){const [legacy,setLegacy]=useState(false);return legacy?<><button onClick={()=>setLegacy(false)}>Flexible animation studio</button><LegacyAnimationStudio {...props}/></>:<FlexibleStudio {...props} onLegacy={()=>setLegacy(true)}/> }
