import { locomotionSlots } from '../../domain/game/animation-studio/gameMapping'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { Background,Controls,ReactFlow,MarkerType,type Node,type NodeProps,type Edge } from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import type { ProjectSnapshot } from '../../domain/graphcore'
import { blankGraph,clipNode,convertLegacy,freezeFlexible,flexibleProblems,generationReadiness,type FlexibleGraph,type FlexNode } from '../../domain/game/animation-studio/flexible'
import type { StudioGraph } from '../../domain/game/animation-studio/graph'
import { readStudio,sendStudio,recoverStudio,type StudioData } from '../../data/animationStudioRepository'
import type { StudioCommand } from '../../domain/game/animation-studio/protocol'
import { WorkflowNodeFrame } from '../graph/WorkflowNodeFrame'
import { FlexiblePreview } from './FlexiblePreview'
import { AnimationPreview } from '../game-builder/AnimationPreview'
import '../../styles/features/animation-studio.css'

type Workspace={id:string;draft_id:string;revision:number;graph:FlexibleGraph|StudioGraph}
type Data=Omit<StudioData,'workspace'|'library'|'jobs'>&{workspace:Workspace|null;library:Workspace[];revisions:Array<{revision:number;created_at:string}>;jobs:Array<StudioData['jobs'][number]&{prompt?:string;edit?:{summary:string;scopeExpansion:string[];edits:{nodes?:{upsert:Array<{id:string}>;remove:string[]}}};appliedRevision?:number}>}
const empty:Data={workspace:null,library:[],jobs:[],candidates:[],reviews:[],sources:[],game:null,revisions:[]}
type Card=Node<{motion:FlexNode;active:boolean;status:string;select:()=>void},'motion'>
function MotionCard({data,selected}:NodeProps<Card>){return <WorkflowNodeFrame className={`studio-node outputs-graph-node ${selected?'is-selected':''} ${data.active?'is-active':''}`} onSelect={data.select} inputs={[{id:'in',valueType:'motion'}]} outputs={[{id:'out',valueType:'motion'}]}><div className="studio-node-meta"><span>{data.motion.parent??data.motion.kind}</span><span>{data.status}</span></div><strong>{data.motion.label}</strong><p>{data.motion.description||data.motion.kind}</p><small>{data.motion.kind==='clip'?`${data.motion.loop?'Loop':'Clip'} · ${data.motion.duration}s`:data.motion.kind}</small></WorkflowNodeFrame>}
const types={motion:MotionCard}
export function FlexibleStudio({snapshot,canRun,onBack,onLegacy}:{snapshot:ProjectSnapshot;canRun:boolean;onBack:()=>void;onLegacy:()=>void}){
 const [graph,setGraph]=useState(blankGraph),[data,setData]=useState<Data>(empty),[workspaceId,setWorkspaceId]=useState<string>(()=>crypto.randomUUID()),[selected,setSelected]=useState<string|null>(null),[active,setActive]=useState<string|null>(null)
 const [prompt,setPrompt]=useState('Create a relaxed idle, a friendly wave, and a bow. Add a greet event that plays the wave then bow and returns to idle.'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[scoped,setScoped]=useState(false),[dependencyView,setDependencyView]=useState(false),[maximum,setMaximum]=useState(0),[selectedIds,setSelectedIds]=useState<string[]>([]),[redo,setRedo]=useState<number[]>([]),[historyCursor,setHistoryCursor]=useState<number|null>(null)
 const [mapping,setMapping]=useState<Record<string,string>>({}),[actorId,setActorId]=useState('')
 const dirty=JSON.stringify(graph)!==JSON.stringify(data.workspace?.graph),node=graph.nodes.find(n=>n.id===selected),revision=data.workspace?.revision??0
 const refresh=useCallback(async(id?:string,replace=false)=>{const d=await readStudio(snapshot.project.id,snapshot.draft.id,id) as unknown as Data;setData({...d,revisions:d.revisions??[]});if(replace&&d.workspace?.graph.version===3)setGraph(d.workspace.graph);return d},[snapshot.project.id,snapshot.draft.id])
 useEffect(()=>{if(canRun)void refresh().catch(e=>setError(String(e)))},[canRun,refresh])
 useEffect(()=>{if(!data.workspace||!data.jobs.some(j=>['queued','running'].includes(j.status)))return;const timer=setTimeout(()=>void refresh(workspaceId,!dirty).catch(e=>setError(String(e))),2500);return()=>clearTimeout(timer)},[data,dirty,refresh,workspaceId])
 const run=async(label:string,fn:()=>Promise<void>)=>{if(busy)return;setBusy(label);setError('');setNotice('');try{await fn()}catch(e){setError(String(e))}finally{setBusy('')}}
 const base=(rev=revision)=>({projectId:snapshot.project.id,draftId:data.workspace?.draft_id??snapshot.draft.id,workspaceId,expectedRevision:rev,idempotencyKey:crypto.randomUUID()})
 async function command(c:StudioCommand,replace=false){await sendStudio(c);return refresh(workspaceId,replace)}
 const save=async()=>{const d=await command({...base(),action:'save',graph:await freezeFlexible(graph)},true);setRedo([]);setHistoryCursor(null);return d.workspace!.revision}
 const problems=flexibleProblems(graph),jobs=data.jobs,planning=jobs.some(j=>j.prompt&&['queued','running'].includes(j.status))
 const clips=useMemo(()=>data.candidates.flatMap(c=>c.clip&&c.url?[{clip:c.clip,url:c.url}]:[]),[data.candidates])
 const flowNodes=useMemo<Card[]>(()=>graph.nodes.map((n,i)=>({id:n.id,type:'motion',selected:n.id===selected,position:{x:(i%3)*310,y:Math.floor(i/3)*190},data:{motion:n,active:n.id===active,status:jobs[0]?.edit?.edits.nodes?.upsert.some(x=>x.id===n.id)?'Edited':jobs.find(j=>j.nodeId===n.id)?.status??generationReadiness(graph,n),select:()=>setSelected(n.id)}})),[graph,selected,active,jobs])
 const edges:Edge[]=dependencyView?graph.dependencies.map(d=>({id:`dep.${d.node}`,source:d.predecessor,target:d.node,label:d.candidateId?'Pinned source':'Awaiting source',style:{strokeDasharray:'5 4'}})):graph.transitions.map(t=>({id:t.id,source:t.from,target:t.to,label:t.event??(t.completion?'finished':'condition'),markerEnd:{type:MarkerType.ArrowClosed}}))
 if(!dependencyView)for(const n of graph.nodes){if(n.parent)edges.push({id:`parent.${n.id}`,source:n.parent,target:n.id,label:'contains',style:{strokeDasharray:'2 5'}});for(const s of n.samples)edges.push({id:`sample.${n.id}.${s.node}`,source:n.id,target:s.node,label:`${s.x}, ${s.y}`,style:{strokeDasharray:'4 5'}})}
 const editNode=(patch:Partial<FlexNode>)=>setGraph(g=>({...g,nodes:g.nodes.map(n=>n.id===selected?{...n,...patch}:n)}))
 return <main className="animation-studio"><header className="studio-heading"><div><button className="studio-back" onClick={onBack}>Back to workspace</button><p className="studio-eyebrow">SYNARC / MOTION</p><h1>Animation studio</h1><p>A living animation graph. Describe it, extend it, and play it.</p></div><button onClick={onLegacy}>Legacy graphs & game bindings</button></header>
  <div className="studio-toolbar"><label>Animation library<select value={data.workspace?.id??''} disabled={!!busy} onChange={e=>{const id=e.target.value;if(id)void run('Loading',async()=>{const d=await refresh(id,true);setWorkspaceId(id);setSelected(null);setRedo([]);setHistoryCursor(null);if(d.workspace?.graph.version===2){setGraph(convertLegacy(d.workspace.graph));setNotice('Legacy conversion preview. Save a new revision to convert; original revision remains available.')}})}}><option value="">New graph</option>{data.library.map(w=><option key={w.id} value={w.id}>{w.graph.name}{w.graph.version===2?' · legacy':''}</option>)}</select></label><button disabled={!!busy} onClick={()=>{setData(d=>({...empty,library:d.library}));setWorkspaceId(crypto.randomUUID());setGraph(blankGraph());setSelected(null);setRedo([]);setHistoryCursor(null)}}>New empty graph</button><button disabled={!canRun||!!busy||problems.length>0} onClick={()=>void run('Saving',async()=>{await save();setNotice('Saved graph revision')})}>Save revision</button><span>Revision {revision}{dirty?' · Unsaved changes':''}</span>
  <button disabled={dirty||!!busy||!data.revisions.some(r=>r.revision<(historyCursor??revision))} onClick={()=>void run('Undoing',async()=>{const previous=data.revisions.find(r=>r.revision<(historyCursor??revision))!;setRedo(values=>[historyCursor??revision,...values]);setHistoryCursor(previous.revision);await command({...base(),action:'restore',revision:previous.revision},true)})}>Undo</button><button disabled={dirty||!!busy||!redo.length} onClick={()=>void run('Redoing',async()=>{await command({...base(),action:'restore',revision:redo[0]},true);setHistoryCursor(redo[0]);setRedo(values=>values.slice(1))})}>Redo</button></div>
  <section className="studio-prompt"><label htmlFor="flex-prompt">Create or change your graph</label><div><textarea id="flex-prompt" value={prompt} maxLength={4000} onChange={e=>setPrompt(e.target.value)} placeholder="Add a seated conversation mode, then branch into a celebration…"/><button disabled={!canRun||!!busy||planning||prompt.length<10||problems.length>0} onClick={()=>void run('Planning graph edits',async()=>{const rev=dirty?await save():revision;await command({...base(rev),action:'plan',prompt,nodeIds:scoped&&selected?[selected]:[]},true);setHistoryCursor(null);setRedo([]);setNotice('Prompt queued. Valid edits apply automatically; you can undo them.')})}>Apply prompt</button></div><label><input type="checkbox" checked={scoped} disabled={!selected} onChange={e=>setScoped(e.target.checked)}/>Only selected state and its children</label><small>Graph edits use design credits. Motion generation is a separate action.</small></section>
  {error&&<div role="alert" className="studio-error">{error}<button onClick={()=>void run('Recovering',async()=>{await recoverStudio(workspaceId);await refresh(workspaceId,true)})}>Recover pending command</button></div>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">{busy}…</p>}
  {jobs.filter(j=>j.prompt).map(j=><section className="studio-proposal" key={j.id}><p><strong>You:</strong> {j.prompt}</p><p>{j.edit?.summary??j.error??j.phase} · {j.status}{j.appliedRevision?` · Applied revision ${j.appliedRevision}`:''}</p>{j.edit?.edits.nodes&&<p>Added or updated: {j.edit.edits.nodes.upsert.map(n=>n.id).join(', ')||'none'} · Removed: {j.edit.edits.nodes.remove.join(', ')||'none'}</p>}{j.edit&&<details><summary>Inspect graph edits</summary><pre>{JSON.stringify(j.edit.edits,null,2)}</pre></details>}{j.phase==='edit.scope_review'&&<><p>Requires expanded scope: {j.edit?.scopeExpansion.join(', ')}</p><button disabled={dirty||j.sourceRevision!==revision||!!busy} onClick={()=>void run('Applying expanded edit',async()=>{await command({...base(),action:'apply_edit',jobId:j.id},true)})}>Apply expanded edit</button></>}{j.phase==='edit.conflict'&&<p>The graph changed while planning. Send the prompt again to use the current revision.</p>}</section>)}
  <div className="studio-workbench"><section className="studio-canvas-panel"><div className="studio-panel-heading"><strong>{graph.name}</strong><label><input type="checkbox" checked={dependencyView} onChange={e=>setDependencyView(e.target.checked)}/>Generation dependencies</label></div>{graph.nodes.length?<div className="studio-graph"><ReactFlow nodes={flowNodes} edges={edges} nodeTypes={types} fitView minZoom={.1} nodesConnectable={false}><Background/><Controls/></ReactFlow></div>:<div className="flex-empty"><h2>Start with any movement idea</h2><p>“Idle, wave, then bow.” “A branching dance sequence.” “Seated gestures with a chair.”</p><button onClick={()=>{const n=clipNode('idle','Idle');n.loop=true;setGraph(g=>({...g,entry:n.id,nodes:[n]}));setSelected(n.id)}}>Add first clip manually</button></div>}</section>
  <aside className="studio-inspector">{node?<><p className="studio-eyebrow">{node.kind} / {node.id}</p><h2>{node.label}</h2><label>Label<input value={node.label} onChange={e=>editNode({label:e.target.value})}/></label><label>Motion description<textarea value={node.description} onChange={e=>editNode({description:e.target.value})}/></label>{node.kind==='clip'&&<><label>Duration<input type="number" min={.5} max={8} step={.1} value={node.duration} onChange={e=>editNode({duration:Number(e.target.value)})}/></label><label><input type="checkbox" checked={node.loop} onChange={e=>editNode({loop:e.target.checked})}/>Loop</label><label>Entry context<textarea value={node.entryDescription} onChange={e=>editNode({entryDescription:e.target.value})}/></label><label>Exit context<textarea value={node.exitDescription} onChange={e=>editNode({exitDescription:e.target.value})}/></label><label><input type="checkbox" checked={selectedIds.includes(node.id)} onChange={e=>setSelectedIds(ids=>e.target.checked?[...ids,node.id]:ids.filter(id=>id!==node.id))}/>Select for generation</label></>}<label>Shared style<select value={node.style??''} onChange={e=>editNode({style:e.target.value||null})}><option value="">No shared style</option>{graph.styles.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>{graph.styles.filter(s=>s.id===node.style).map(s=><label key={s.id}>Style description<textarea value={s.description} onChange={e=>setGraph(g=>({...g,styles:g.styles.map(x=>x.id===s.id?{...x,description:e.target.value}:x)}))}/></label>)}{graph.dependencies.filter(d=>d.node===node.id).map(d=><label key={d.node}>Predecessor: {d.predecessor}<select value={d.candidateId??''} onChange={e=>setGraph(g=>({...g,dependencies:g.dependencies.map(x=>x.node===node.id?{...x,candidateId:e.target.value||null}:x)}))}><option value="">Generate and select source first</option>{data.candidates.filter(c=>c.nodeId===d.predecessor&&c.clip).map(c=><option key={c.id} value={c.id}>{c.id.slice(0,8)}</option>)}</select></label>)}</>:<p>Select a state to inspect it, or describe a change above.</p>}</aside></div>
  <div className="studio-bottom"><FlexiblePreview graph={graph} clips={clips} selected={selected} onActive={setActive}/><section className="studio-generation"><h2>Generate & review motions</h2><button onClick={()=>setSelectedIds(graph.nodes.filter(n=>generationReadiness(graph,n)==='ready to generate').map(n=>n.id))}>Select ready motions</button><label>Maximum reservation (cents)<input type="number" min={0} max={2500} value={maximum} onChange={e=>setMaximum(Number(e.target.value))}/></label><button disabled={dirty||!!busy||!selectedIds.length||maximum<=0} onClick={()=>void run('Generating',async()=>{await command({...base(),action:'generate',nodeIds:selectedIds,maxReservationCents:maximum})})}>Generate {selectedIds.length} clips</button><p className="studio-hint">Independent clips run in parallel. Dependent clips wait for a selected source candidate. Provider availability and reservations are checked before submission.</p>{jobs.filter(j=>j.nodeId).map(j=><div className="studio-candidate" key={j.id}><strong>{j.nodeId}</strong> · {j.status} · {j.phase}{j.error&&<p>{j.error}</p>}{['queued','running','attention'].includes(j.status)&&<button onClick={()=>void run('Cancelling',async()=>{await command({...base(),action:'cancel',jobId:j.id})})}>Cancel</button>}{j.status==='failed'&&<button onClick={()=>void run('Retrying saved source',async()=>{await command({...base(),action:'retry',jobId:j.id})})}>Retry processing</button>}</div>)}{data.candidates.filter(c=>c.nodeId===selected).map(c=><div className="studio-candidate" key={c.id}>{c.clip&&c.url&&<AnimationPreview clip={c.clip} url={c.url}/>}<p>{c.diagnostics.failures?.join('; ')||'Candidate ready for visual review'}</p><button disabled={dirty||!c.clip||!!busy} onClick={()=>void run('Accepting',async()=>{await command({...base(),action:'review_clip',candidateId:c.id,nodeId:c.nodeId,decision:'accepted'},true)})}>Accept candidate</button><button disabled={!!busy} onClick={()=>void run('Rejecting',async()=>{await command({...base(),action:'review_clip',candidateId:c.id,nodeId:c.nodeId,decision:'rejected'})})}>Reject candidate</button></div>)}</section></div>
  <section className="studio-publish"><button disabled={dirty||!!busy||!graph.nodes.some(n=>n.kind==='clip')||graph.nodes.some(n=>n.kind==='clip'&&!n.clipId)} onClick={()=>void run('Reviewing graph',async()=>{await command({...base(),action:'review_graph'});setNotice('Graph and transition visual review recorded')})}>Accept graph & transitions after visual review</button></section><details><summary>Event key bindings</summary>{graph.events.map(event=><label key={event.id}>{event.label}<select value={event.key??''} onChange={e=>setGraph(g=>({...g,events:g.events.map(x=>x.id===event.id?{...x,key:e.target.value||null}:x)}))}><option value="">Button only</option>{[...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'].map(k=><option key={k} value={`Key${k}`}>{k}</option>)}<option value="Space">Space</option></select></label>)}</details>
  <details><summary>Revision history</summary>{data.revisions.map(r=><p key={r.revision}>Revision {r.revision} · {r.created_at}<button disabled={dirty||!!busy} onClick={()=>void run('Restoring revision',async()=>{await command({...base(),action:'restore',revision:r.revision},true)})}>Restore</button></p>)}</details>
  <details><summary>Optional game integration</summary><p>Map a reviewed looping clip to each supported locomotion slot. Other states stay in this standalone graph. Gameplay actions retain their existing bindings.</p>{locomotionSlots.map(slot=><label key={slot}>{slot}<select value={mapping[slot]??''} onChange={e=>setMapping(m=>({...m,[slot]:e.target.value}))}><option value="">Choose clip</option>{graph.nodes.filter(n=>n.kind==='clip'&&n.loop).map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label>)}<label>Target actor<select value={actorId} onChange={e=>setActorId(e.target.value)}><option value="">Select actor</option>{data.game?.actors.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><button disabled={dirty||!!busy||!actorId||!data.reviews.some(r=>r.revision===revision)||locomotionSlots.some(s=>!mapping[s])} onClick={()=>void run('Attaching mapped locomotion',async()=>{await command({...base(),action:'attach',targetDraftId:snapshot.draft.id,targetRevision:data.game!.revision,actorId,mapping});setNotice('Mapped locomotion attached. Build and review the game before publication.')})}>Attach mapped locomotion</button><button onClick={onLegacy}>Legacy game bindings</button></details>
  {problems.length>0&&<div role="alert">{problems.map(p=><p key={p}>{p}</p>)}</div>}{graph.gaps.map((gap,i)=><p key={i}>{gap}</p>)}
 </main>
}
