import {
  applyPatchProposal,
  bootstrapLiveWorkspace,
  compileSnapshot,
  createGame,
  deleteGeneratedMesh,
  deleteWorldBuildPlaceholder,
  ensureLiveProjectSnapshot,
  listGames,
  loadProjectSnapshot,
  persistDefinitionPreviewImageBinding,
  persistGlobalProjectContext,
  pollMeshGeneration,
  planWorldBuild,
  pollWorldBuild,
  proposePatch,
  startMeshGeneration,
  startWorldBuild,
  setActiveGame,
} from '../../data/graphcoreRepository'

export const graphcoreWorkspaceAdapter = {
  applyPatchProposal,
  bootstrapLiveWorkspace,
  compileSnapshot,
  createGame,
  deleteGeneratedMesh,
  deleteWorldBuildPlaceholder,
  ensureLiveProjectSnapshot,
  listGames,
  loadProjectSnapshot,
  persistDefinitionPreviewImageBinding,
  persistGlobalProjectContext,
  pollMeshGeneration,
  planWorldBuild,
  pollWorldBuild,
  proposePatch,
  startMeshGeneration,
  startWorldBuild,
  setActiveGame,
}
