import {
  applyPatchProposal,
  bootstrapLiveWorkspace,
  compileSnapshot,
  createGame,
  deleteWorldBuildPlaceholder,
  ensureLiveProjectSnapshot,
  listGames,
  loadProjectSnapshot,
  planWorldBuild,
  pollWorldBuild,
  proposePatch,
  startWorldBuild,
  setActiveGame,
} from '../../data/graphcoreRepository'

export const graphcoreWorkspaceAdapter = {
  applyPatchProposal,
  bootstrapLiveWorkspace,
  compileSnapshot,
  createGame,
  deleteWorldBuildPlaceholder,
  ensureLiveProjectSnapshot,
  listGames,
  loadProjectSnapshot,
  planWorldBuild,
  pollWorldBuild,
  proposePatch,
  startWorldBuild,
  setActiveGame,
}
