import {validateVariationRecipe} from '../../domain/cityVariationValidation';
import {useEffect,useMemo,useState} from 'react';
import {enableBuildingVariation,expandBuildingVariation,previewStorefront,shuffleVariation,variationChoices} from '../../domain/cityBuildingVariation';
import {VARIATION_LAYERS,type VariationLayer,type VariationLayerRule,type VariationRule} from '../../domain/cityVariationTypes';
import type {StudioRecipe,StudioBay} from '../../domain/cityStudioTypes';
import type {CityBuildingDesignV3} from '../../domain/cityBuildingV3';
import {studioBays,studioFloorCount,validateStudio} from '../../domain/cityStudio';
import {validateSculpt} from '../../domain/citySculpt';
import {STOREFRONT_STAMPS,STAMP_MAP,unpackStorefront} from '../../domain/cityStorefrontStamps';
import './cityVariation.css';

const labels:Record<VariationLayer,string>={ground:'Ground floor',windows:'Upper windows',corners:'Corners',balconies:'Balconies',accents:'Facade accents',roof:'Roof details',props:'Props'};
/** Shared authoring controls. Only authored intent is committed; generated placements are ephemeral. */
export function CityVariationPanel({recipe,design,onChange,selectedPart}:{recipe:StudioRecipe;design:CityBuildingDesignV3;onChange:(r:StudioRecipe,heights?:Pick<CityBuildingDesignV3,'groundHeight'|'upperHeight'>)=>void;selectedPart?:string}){
 const [layer,setLayer]=useState<VariationLayer>('ground'),[scope,setScope]=useState('building'),[advanced,setAdvanced]=useState(false),[floor,setFloor]=useState(0),[lastFloor,setLastFloor]=useState(0),[selection,setSelection]=useState<StudioBay[]>([]),[error,setError]=useState(''),[stamp,setStamp]=useState('stamp-cafe-2'),[name,setName]=useState('My building'),[saved,setSaved]=useState<string[]>(()=>{try{return Object.keys(JSON.parse(localStorage.getItem('city-variation-presets-1')??'{}'));}catch{return [];}});
 const [targetPart,setTargetPart]=useState(selectedPart??recipe.volumes.find(v=>v.operation==='add')?.id??'');
 const [pendingStamp,setPendingStamp]=useState<StudioBay|null>(null);
 const v=recipe.studio.variation;
 const stampPreview=useMemo(()=>pendingStamp?previewStorefront(recipe,design,stamp,pendingStamp.anchor):null,[recipe,design,stamp,pendingStamp]);
 useEffect(()=>{if(scope!=='building'&&!v?.rules.some(r=>r.id===scope))setScope('building');},[scope,v]);
 const chosenPart=selectedPart??(recipe.volumes.some(v=>v.operation==='add'&&v.id===targetPart)?targetPart:recipe.volumes.find(v=>v.operation==='add')?.id);
 const expanded=useMemo(()=>expandBuildingVariation(recipe,design),[recipe,design]);
 const bays=useMemo(()=>studioBays(expanded.recipe,design),[expanded,design]);
 const rawBays=useMemo(()=>studioBays({...recipe,studio:{...recipe.studio,openings:[]}},design),[recipe,design]);
 const active=v?.rules.find(r=>r.id===scope),settings=v?{...v.layers[layer],...active?.layers[layer]}:null;
 const commit=(r:StudioRecipe,heights?:Pick<CityBuildingDesignV3,'groundHeight'|'upperHeight'>)=>{const problem=validateStudio(r)||validateSculpt(r,studioFloorCount(r),r.plotSize??24);if(problem){setError(problem);return;}setError('');onChange(r,heights);};
 const change=(patch:Partial<VariationLayerRule>)=>{const r=structuredClone(recipe),rules=r.studio.variation!;if(scope==='building')Object.assign(rules.layers[layer],patch);else {const rule=rules.rules.find(r=>r.id===scope);if(rule)rule.layers[layer]={...rule.layers[layer],...patch};}commit(r);};
 const addRule=(kind:VariationRule['scope']['kind'])=>{if(!v||v.rules.length>=32)return;const id=crypto.randomUUID(),rule:VariationRule={id,name:kind==='region'?'Painted section':kind==='part'?'Selected part':`Floors ${floor+1}–${lastFloor+1}`,scope:{kind,...(kind==='part'?{partId:chosenPart}:{}),...(kind==='floor'||kind==='region'?{fromFloor:floor,toFloor:Math.max(floor,lastFloor)}:{}),...(kind==='region'?{faces:selection.map(b=>({partId:b.anchor.shapeId,side:b.anchor.side,from:Math.max(0,b.anchor.u-b.anchorSpan/2),to:Math.min(1,b.anchor.u+b.anchorSpan/2)}))}:{})},layers:{}};commit({...recipe,studio:{...recipe.studio,variation:{...v,rules:[...v.rules,rule]}}});setScope(id);};
 const importRecipe=(text:string)=>{try{if(text.length>65536)throw Error('Preset exceeds 64 KB.');const value=JSON.parse(text);if(value.version!==1||Object.keys(value).some(k=>!['version','recipe','groundHeight','upperHeight'].includes(k))||!value.recipe||![5,6].includes(value.recipe.version))throw Error('Choose a variation preset JSON file.');const r=value.recipe as StudioRecipe;const problem=validateVariationRecipe(r,Math.max(1,...r.volumes.map(v=>v.startFloor+v.spanFloors)),recipe.plotSize??24,!design.modular);if(problem)throw Error(problem);const heights={groundHeight:value.groundHeight??design.groundHeight,upperHeight:value.upperHeight??design.upperHeight??3};if(Object.values(heights).some(n=>typeof n!=='number'||!Number.isFinite(n)||n<3||n>4.5))throw Error('Invalid storey heights.');commit(r,heights);setScope('building');}catch(e){setError(e instanceof Error?e.message:'Invalid preset.');}};
 const bundle=()=>{const content=JSON.stringify({version:1,recipe,groundHeight:design.groundHeight,upperHeight:design.upperHeight??3}),problem=validateVariationRecipe(recipe,studioFloorCount(recipe),recipe.plotSize??24,!design.modular);if(problem||content.length>65536){setError(problem??'Preset exceeds 64 KB.');return null;}return content;};
 const place=(b:StudioBay)=>{setPendingStamp(b);setError('');};
 if(!v||!settings)return <section className="city-variation"><h3>Building variations</h3><p>Use weighted Blender tile pools around this building’s existing shape. Painted tiles and details stay protected.</p><button type="button" onClick={()=>commit(enableBuildingVariation(recipe))}>Enable variation rules</button></section>;
 return <section className="city-variation" aria-label="Building variations">
  <header><h3>Building variations</h3><button type="button" onClick={()=>commit({...recipe,studio:{...recipe.studio,variation:shuffleVariation(v,undefined,scope==='building'?undefined:scope)}})}>Shuffle unlocked layers</button></header>
  <p>Manual edits stay fixed. Changes use your existing undo history.</p>
  <label>Target<select aria-label="Variation target" value={active?scope:'building'} onChange={e=>setScope(e.target.value)}><option value="building">Whole building</option>{v.rules.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
  <nav aria-label="Variation layers">{VARIATION_LAYERS.map(k=><button type="button" key={k} aria-pressed={layer===k} onClick={()=>setLayer(k)}>{labels[k]}</button>)}</nav>
  <label>Coverage <output>{Math.round(settings.coverage*100)}%</output><input aria-label="Tile coverage" type="range" min="0" max="1" step=".05" value={settings.coverage} onChange={e=>change({coverage:Number(e.target.value)})}/></label>
  <label>Uniformity <output>{Math.round(settings.uniformity*100)}%</output><input aria-label="Tile uniformity" type="range" min="0" max="1" step=".05" value={settings.uniformity} onChange={e=>change({uniformity:Number(e.target.value)})}/></label>
  <div className="variation-actions"><button type="button" onClick={()=>commit({...recipe,studio:{...recipe.studio,variation:shuffleVariation(v,layer,scope==='building'?undefined:scope)}})}>Shuffle {labels[layer].toLowerCase()}</button><label><input type="checkbox" checked={settings.locked} onChange={e=>change({locked:e.target.checked})}/>Lock this layer</label></div>
  <button type="button" aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}>Advanced rules</button>
  {advanced&&<>
   <label>Pattern<select aria-label="Variation pattern" value={settings.pattern} onChange={e=>change({pattern:e.target.value as VariationLayerRule['pattern']})}>{['aligned','groups','alternating','independent'].map(v=><option key={v}>{v}</option>)}</select></label>
   <label>Minimum gap (bays)<input aria-label="Tile spacing" type="number" min="0" max="8" value={settings.spacing} onChange={e=>change({spacing:Number(e.target.value)})}/></label>
   <label>Placement zone<select value={settings.zone} onChange={e=>change({zone:e.target.value as VariationLayerRule['zone']})}>{(layer==='roof'||layer==='props'?['all','centre','perimeter','corners']:['all','front','back']).map(z=><option key={z}>{z}</option>)}</select></label>
   <fieldset><legend>Weighted tile pool · {settings.pool.length}/24</legend><div className="variation-pool">{variationChoices(layer).map(p=>{const item=settings.pool.find(x=>x.id===p.id);return <div key={p.id}><label><input type="checkbox" checked={!!item} disabled={!item&&settings.pool.length>=24} onChange={e=>change({pool:e.target.checked?[...settings.pool,{id:p.id,weight:1}]:settings.pool.filter(x=>x.id!==p.id)})}/>{p.label}</label>{item&&<input aria-label={`${p.label} weight`} type="number" min=".01" max="100" step=".25" value={item.weight} onChange={e=>change({pool:settings.pool.map(x=>x.id===p.id?{...x,weight:Number(e.target.value)}:x)})}/>}</div>;})}</div><small>Wider modules require adjacent free bays. Unfilled bays become walls.</small></fieldset>
   {active&&<><label>Rule name<input value={active.name} maxLength={80} onChange={e=>commit({...recipe,studio:{...recipe.studio,variation:{...v,rules:v.rules.map(r=>r.id===scope?{...r,name:e.target.value}:r)}}})}/></label><button type="button" onClick={()=>{commit({...recipe,studio:{...recipe.studio,variation:{...v,rules:v.rules.filter(r=>r.id!==scope)}}});setScope('building');}}>Remove override</button><button type="button" onClick={()=>{const r=structuredClone(recipe),target=r.studio.variation!.rules.find(r=>r.id===scope)!;delete target.layers[layer];commit(r);}}>Inherit this layer</button></>}
   <fieldset><legend>Scope a new rule</legend><label>From floor<select value={floor} onChange={e=>{setFloor(Number(e.target.value));setLastFloor(Number(e.target.value));setSelection([]);}}>{Array.from({length:design.floors},(_,i)=><option key={i} value={i}>{i===0?'Ground':i+1}</option>)}</select></label><label>Through floor<select value={Math.max(floor,lastFloor)} onChange={e=>setLastFloor(Number(e.target.value))}>{Array.from({length:design.floors-floor},(_,i)=><option key={i+floor} value={i+floor}>{i+floor+1}</option>)}</select></label><button type="button" onClick={()=>addRule('floor')}>Add floor rule</button><label>Building part<select aria-label="Rule building part" value={chosenPart??''} onChange={e=>setTargetPart(e.target.value)} disabled={!!selectedPart}>{recipe.volumes.filter(v=>v.operation==='add').map(v=><option key={v.id} value={v.id}>{v.id}</option>)}</select></label><button type="button" disabled={!chosenPart} onClick={()=>addRule('part')}>Add part rule</button><p>Select exposed bays below, then create a painted section. Regions retain their original hosts after resizing.</p><div className="variation-faces" aria-label="Paint rule region">{rawBays.filter(b=>b.anchor.floor===floor).map(b=><button type="button" key={b.id} title={`${b.anchor.shapeId} ${b.anchor.side} ${b.anchor.u.toFixed(2)}`} aria-label={`Select bay ${b.id}`} aria-pressed={selection.some(x=>x.id===b.id)} onClick={()=>setSelection(s=>s.some(x=>x.id===b.id)?s.filter(x=>x.id!==b.id):s.length<64?[...s,b]:s)}>{b.anchor.side} · {Math.round(b.anchor.u*100)}%</button>)}</div><button type="button" disabled={!selection.length} onClick={()=>addRule('region')}>Create rule from {selection.length} bays</button></fieldset>
  </>}
  <details><summary>Paint storefronts</summary><label>Storefront<select aria-label="Storefront stamp" value={stamp} onChange={e=>setStamp(e.target.value)}>{STOREFRONT_STAMPS.map(s=><option value={s.id} key={s.id}>{s.label}</option>)}</select></label><p>Select the first bay for a {STAMP_MAP.get(stamp)?.span}-bay storefront. Main entrances and manual tiles are protected.</p><div className="variation-faces">{rawBays.filter(b=>b.anchor.floor===0).map(b=><button type="button" key={b.id} aria-label={`Place storefront at ${b.id}`} aria-pressed={!!stampPreview?.run.some(x=>x.id===b.id)} disabled={b.entrance} onClick={()=>place(b)}>{b.anchor.side} · {Math.round(b.anchor.u*100)}%</button>)}</div>{stampPreview&&<div className="variation-actions"><span>{stampPreview.reason??`${stampPreview.run.length} bays · ${stampPreview.replaced} storefronts replaced`}</span><button type="button" disabled={!!stampPreview.reason} onClick={()=>{commit(stampPreview.recipe);setPendingStamp(null);}}>Apply storefront</button><button type="button" onClick={()=>setPendingStamp(null)}>Cancel placement</button></div>}{recipe.studio.stamps?.map(s=><div className="variation-actions" key={s.id}><span>{STAMP_MAP.get(s.stamp)?.label} · locked</span><button type="button" onClick={()=>commit(unpackStorefront(recipe,s.id,expanded.recipe))}>Unpack</button><button type="button" onClick={()=>commit({...recipe,studio:{...recipe.studio,stamps:recipe.studio.stamps?.filter(p=>p.id!==s.id)}})}>Remove</button></div>)}</details>
  {!!expanded.diagnostics.length&&<ul>{expanded.diagnostics.map(d=><li key={d.id}>{d.reason}</li>)}</ul>}
  <details><summary>My presets · import / export</summary><label>Preset name<input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><button type="button" onClick={()=>{try{const all=JSON.parse(localStorage.getItem('city-variation-presets-1')??'{}');if(!name.trim()||['__proto__','constructor','prototype'].includes(name))return;const payload=bundle();if(!payload)return;all[name]=payload;localStorage.setItem('city-variation-presets-1',JSON.stringify(all));setSaved(Object.keys(all));}catch{setError('Local preset storage is full or unavailable. Export JSON instead.');}}}>Save preset locally</button>{saved.map(n=><button type="button" key={n} onClick={()=>{try{importRecipe(JSON.parse(localStorage.getItem('city-variation-presets-1')??'{}')[n]);}catch{setError('Preset unavailable.');}}}>{n}</button>)}<button type="button" onClick={()=>{const payload=bundle();if(!payload)return;const url=URL.createObjectURL(new Blob([payload],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='building-variation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export JSON</button><label>Import JSON<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>65536)setError('Preset exceeds 64 KB.');else importRecipe(await f.text());}e.target.value='';}}/></label></details>
  <small>{bays.length} exposed bays · precedence: building → part → floor → painted region → manual</small>{error&&<p role="alert">{error}</p>}
 </section>;
}
