import {CityRoofTray} from './CityRoofTray';
import {setSculptPreview,clearSculptPreview} from './citySculptPreview';
import {STUDIO_EXAMPLES,studioExample} from '../../domain/cityStudioExamples';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Html,OrbitControls} from '@react-three/drei';
import {useFrame,useThree} from '@react-three/fiber';
import {MOUSE,Vector3,type PerspectiveCamera} from 'three';
import type {OrbitControls as OrbitControlsImpl} from 'three-stdlib';
import {ArrowUUpLeft,ArrowUUpRight,Check,Copy,Cube,Cylinder,Door,Eraser,Eye,Hand,House,PaintBrush,Plant,Plus,Question,Stairs,Trash,X,Cursor,ArrowsOut,ArrowUp,ArrowClockwise,Compass} from '@phosphor-icons/react';
import type {CityLandController} from './useCityLand';
import type {ExplorationSession} from '../../domain/cityExploration';
import {createFootState} from '../../domain/cityExploration';
import {landEntrance,landPosition} from '../../domain/cityLand';
import {applyComposition,COMPOSITIONS} from '../../domain/cityBuildingV3';
import {checkStudioDraft,liftStudioAnchors,freshStudio,studioDraft,studioStyle,upgradeStudio} from '../../domain/cityStudio';
import type {StudioRecipe,StudioRoof,StudioChannel,StudioFamily,StudioBay} from '../../domain/cityStudioTypes';
import {STUDIO_COLORS,STUDIO_FAMILIES,STUDIO_MODULES} from '../../domain/cityStudioCatalog';
import {sculptFloorBottom,sculptFloorTop,type SculptVolume} from '../../domain/citySculpt';
import {studioHandles,studioRoofHandles,useStudioInteraction,type StudioTool} from './useStudioInteraction';
import {preparedStudioPlot} from './cityStudioRegistry';
import './cityStudio.css';

type Category='Shape'|'Roofs'|'Openings'|'Surfaces'|'Details'|'Garden';
const categories=[['Shape',Cube],['Roofs',House],['Openings',Door],['Surfaces',PaintBrush],['Details',House],['Garden',Plant]] as const;
const details=[['balcony','Balcony','balcony-centre'],['cornice','Cornice','cornice'],['canopy','Canopy','canopy-glass'],['stair','Stair','stair-flight'],['pilaster','Pilaster','pilaster'],['ornament','Ornament','floral-relief'],['planter','Planter','window-box'],['light','Light','wall-lamp']] as const;

export function CityStudio({land,session,camera,reduced}:{land:CityLandController;session:ExplorationSession;camera:PerspectiveCamera;reduced:boolean}){
 const plot=land.selected!,draft=land.draft!,recipe=draft.sculpt?.version===5?draft.sculpt:null,walking=land.phase==='walkthrough';
 const [category,setCategory]=useState<Category>('Shape'),[tool,setTool]=useState<StudioTool>('select'),[floor,setFloor]=useState(0),[opening,setOpening]=useState('window-sash'),[scope,setScope]=useState<'spot'|'wall'|'part'>('spot'),[channel,setChannel]=useState<StudioChannel>('wall'),[color,setColor]=useState('#bdc8ad'),[texture,setTexture]=useState(''),[erase,setErase]=useState(false),[eyedropper,setEyedropper]=useState(false),[destination,setDestination]=useState(1),[flip,setFlip]=useState(false),[look,setLook]=useState<'simple'|'ornate'>('simple');
 const [roofScope,setRoofScope]=useState<'part'|'connected'>('part');
 const [help,setHelp]=useState(false),[precision,setPrecision]=useState(false),[styles,setStyles]=useState(false),[parts,setParts]=useState(false),[starters,setStarters]=useState(false),[replace,setReplace]=useState<number|null>(null);
 const controls=useRef<OrbitControlsImpl>(null),{gl,invalidate}=useThree(),cameraSaved=useRef<{position:Vector3;target:Vector3}|null>(null);
 const center=landPosition(plot),scale=plot.size/24,target=useMemo(()=>new Vector3(center.x,6*scale,center.z),[plot.id]);
 const sample=(bay:StudioBay)=>{setColor(bay.finishes[channel]?.color??STUDIO_FAMILIES[bay.family][channel]);setTexture(bay.finishes[channel]?.texture??'');setEyedropper(false);};
 const interaction=useStudioInteraction({land,plot,draft,recipe,camera,tool,setTool,floor,opening,scope,channel,color,texture,erase,eyedropper,onSample:sample,destination,flip,look,walking,roofConnected:roofScope==='connected',onRoofSelect:()=>{setCategory('Roofs');setTool('roof');}});
 const ghost=interaction.transient?.volumes.find(v=>!recipe?.volumes.some(old=>old.id===v.id));
 const shown=interaction.transient??recipe,selected=shown?.volumes.find(v=>v.id===land.selectedVolume),style=recipe&&selected?studioStyle(recipe,selected.id):recipe?.studio.defaults;
 const selectCategory=(next:Category)=>{interaction.cancel();setCategory(next);setErase(false);setEyedropper(false);setStarters(false);setTool(next==='Roofs'?'roof':next==='Openings'?'opening':next==='Surfaces'?'surface':'select');};
 const commit=(next:StudioRecipe)=>{const problem=checkStudioDraft(draft,next);if(problem){interaction.setIssue(problem);return;}land.edit(studioDraft(draft,next));interaction.setIssue('');};
 const editPart=(patch:Partial<SculptVolume>)=>{if(!recipe||!selected)return;commit(liftStudioAnchors({...recipe,volumes:recipe.volumes.map(v=>v.id===selected.id?{...v,...patch}:v)},selected.id,(patch.startFloor??selected.startFloor)-selected.startFloor));};
 const editStyle=(patch:NonNullable<typeof style>)=>{if(!recipe)return;commit({...recipe,studio:{...recipe.studio,...(selected?{parts:{...recipe.studio.parts,[selected.id]:{...recipe.studio.parts[selected.id],...patch}}}:{defaults:{...recipe.studio.defaults,...patch}})}});};
 const followWall=()=>{const b=interaction.hover;if(!recipe||!b)return;const nx=Math.sin(b.rotation),nz=Math.cos(b.rotation);const anchors=interaction.bays.filter(other=>other.anchor.floor===b.anchor.floor&&Math.abs(Math.cos(other.rotation-b.rotation)-1)<.001&&Math.abs((other.x-b.x)*nx+(other.z-b.z)*nz)<.03).map(other=>other.anchor);commit({...recipe,studio:{...recipe.studio,assemblies:[...recipe.studio.assemblies,{id:crypto.randomUUID(),kind:'cornice',anchors,look}]}});};
 const duplicate=()=>{if(!recipe||!selected)return;const id=crypto.randomUUID();commit({...recipe,volumes:[...recipe.volumes,{...selected,id,x:selected.x+.5,z:selected.z+.5}],studio:{...recipe.studio,parts:{...recipe.studio.parts,[id]:structuredClone(style??{})}}});land.setSelectedVolume(id);};
 const remove=()=>{if(!recipe||!selected)return;commit({...recipe,volumes:recipe.volumes.filter(v=>v.id!==selected.id)});land.setSelectedVolume(null);};
 const empty=()=>{if(!recipe)return;commit({...recipe,volumes:[],attachments:[],studio:freshStudio()});land.setSelectedVolume(null);setStarters(false);setTool('block');};
 const starter=(index:number)=>{if(index<=-2){land.edit(studioExample(draft,-index-2,plot.size));setStarters(false);setReplace(null);return;}const design=applyComposition(draft.design,index),next=upgradeStudio({...draft,sculpt:undefined,design},plot.size);if(next){land.edit(next);land.setSelectedVolume(null);setStarters(false);setReplace(null);}};
 const view=(kind:'top'|'front'|'orbit'|'focus')=>{const aim=kind==='focus'&&selected?new Vector3(selected.x*scale+center.x,sculptFloorTop(selected.startFloor+selected.spanFloors-1,draft.design.groundHeight)*scale*.5,selected.z*scale+center.z):target.clone();controls.current?.target.copy(aim);camera.position.copy(aim).add(kind==='top'?new Vector3(0,plot.size*1.6,.01):kind==='front'?new Vector3(0,6,plot.size*1.25):new Vector3(plot.size*.85,plot.size*.7,plot.size*.85));controls.current?.update();invalidate();};
 const walk=()=>{if(land.previewStatus.pending||land.previewStatus.error)return;const prepared=preparedStudioPlot(plot.id);if(!prepared){interaction.setIssue('Your building is still preparing.');return;}cameraSaved.current={position:camera.position.clone(),target:controls.current?.target.clone()??target.clone()};const entry=landEntrance(plot);Object.assign(session.foot,createFootState(entry.x,entry.z,entry.heading));session.mode='on-foot';land.setPhase('walkthrough');};
 useEffect(()=>{if(!walking&&cameraSaved.current){camera.position.copy(cameraSaved.current.position);controls.current?.target.copy(cameraSaved.current.target);controls.current?.update();cameraSaved.current=null;invalidate();}},[walking,camera,invalidate]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(walking||(e.target as HTMLElement)?.closest('input,textarea,select'))return;if(e.key==='Delete'){e.preventDefault();remove();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 const telemetry=useRef(0);
 useFrame(()=>{if(!import.meta.env.DEV||performance.now()-telemetry.current<150)return;telemetry.current=performance.now();const rect=gl.domElement.getBoundingClientRect(),a=plot.rotation*Math.PI/2;
  const screen=(p:Vector3)=>{p.applyAxisAngle(new Vector3(0,1,0),a).multiplyScalar(scale).add(new Vector3(center.x,0,center.z)).project(camera);return {x:rect.left+(p.x+1)*rect.width/2,y:rect.top+(1-p.y)*rect.height/2};};
  gl.domElement.dataset.cityStudio=JSON.stringify({tool,category,selected:selected?.id,floor,walking,parts:recipe?.volumes.length,handles:selected?Object.fromEntries((tool==='roof'&&recipe?studioRoofHandles(selected,draft.design.groundHeight,recipe):studioHandles(selected,draft.design.groundHeight)).map(h=>[h.id,screen(h.point)])):null,bays:interaction.bays.map(b=>({id:b.id,part:b.anchor.shapeId,floor:b.anchor.floor,side:b.anchor.side,module:b.module,...screen(new Vector3(b.x,b.y+b.height/2,b.z))}))});
  gl.domElement.dataset.cityConstructionCamera=JSON.stringify({position:camera.position.toArray(),target:controls.current?.target.toArray()});
 });
 const roofOptions:StudioRoof[]=['flat','terrace','pitched','mansard'];
 const prepared=preparedStudioPlot(plot.id)?.result;const inactive=prepared?.inactive??[];
 if(walking)return <primitive object={camera}><Html fullscreen position={[0,0,-1]} style={{pointerEvents:'none'}}><div className="studio-walk" role="region" aria-label="Building walk-through"><span><Eye size={19}/> Walk around your draft</span><button onClick={()=>land.setPhase('construction')}>Return to building <kbd>E</kbd></button></div></Html></primitive>;
 return <>
  <OrbitControls ref={controls} camera={camera} target={target} enabled={!interaction.active&&!interaction.touchPending} mouseButtons={{LEFT:undefined,MIDDLE:MOUSE.PAN,RIGHT:MOUSE.ROTATE}} minDistance={plot.size*.3} maxDistance={plot.size*3} minPolarAngle={.01} maxPolarAngle={1.48} enableDamping={!reduced}/>
  <group position={[center.x,0,center.z]} rotation={[0,plot.rotation*Math.PI/2,0]} scale={scale}>
   {['block','round','oval','cut'].includes(tool)&&<gridHelper args={[21,42,'#829c88','#a6b6a0']} position={[0,sculptFloorBottom(floor,draft.design.groundHeight),0]} raycast={()=>null}><lineBasicMaterial transparent opacity={.18} depthWrite={false}/></gridHelper>}
   {ghost&&<mesh position={[ghost.x,(sculptFloorBottom(ghost.startFloor,draft.design.groundHeight)+sculptFloorTop(ghost.startFloor+ghost.spanFloors-1,draft.design.groundHeight))/2,ghost.z]} scale={[ghost.width,sculptFloorTop(ghost.startFloor+ghost.spanFloors-1,draft.design.groundHeight)-sculptFloorBottom(ghost.startFloor,draft.design.groundHeight),ghost.depth]} raycast={()=>null}>{ghost.kind==='ellipse'?<cylinderGeometry args={[.5,.5,1,24]}/>:<boxGeometry/>}<meshBasicMaterial wireframe={ghost.operation==='subtract'} color={interaction.issue?'#bd765f':'#e6be79'} transparent opacity={ghost.operation==='subtract'?.8:.35} depthWrite={false}/></mesh>}
   {selected&&(tool==='select'||tool==='roof')&&<group>
    <mesh position={[selected.x,(sculptFloorBottom(selected.startFloor,draft.design.groundHeight)+sculptFloorTop(selected.startFloor+selected.spanFloors-1,draft.design.groundHeight))/2,selected.z]} scale={[selected.width,sculptFloorTop(selected.startFloor+selected.spanFloors-1,draft.design.groundHeight)-sculptFloorBottom(selected.startFloor,draft.design.groundHeight),selected.depth]} raycast={()=>null}>{selected.kind==='ellipse'?<cylinderGeometry args={[.5,.5,1,24]}/>:<boxGeometry/>}<meshBasicMaterial color={interaction.issue?'#b97761':'#9fc3a8'} wireframe transparent opacity={.55}/></mesh>
    {(tool==='roof'&&recipe?studioRoofHandles(selected,draft.design.groundHeight,shown!):studioHandles(selected,draft.design.groundHeight)).map(handle=><group key={handle.id} position={handle.point}><mesh raycast={()=>null}><sphereGeometry args={[.18,12,8]}/><meshBasicMaterial color={handle.id==='lift'?'#d6b47b':'#e9f1dd'} depthTest={false}/></mesh>{['move','height','lift','roof-rise','roof-eave','roof-crown'].includes(handle.id)&&<Html center style={{pointerEvents:'none'}}><span className="studio-handle">{handle.id==='move'?<Hand size={16}/>:handle.id==='height'?<ArrowsOut size={16}/>:<ArrowUp size={16}/>}<small>{handle.id==='roof-rise'?'Roof height':handle.id==='roof-eave'?'Eave':handle.id==='roof-crown'?'Crown':handle.id==='height'?'Height':handle.id==='lift'?'Lift':'Move'}</small></span></Html>}</group>)}
   </group>}
   {interaction.hover&&tool!=='select'&&tool!=='roof'&&<mesh position={[interaction.hover.x+Math.sin(interaction.hover.rotation)*.24,interaction.hover.y+interaction.hover.height/2,interaction.hover.z+Math.cos(interaction.hover.rotation)*.24]} rotation={[0,interaction.hover.rotation,0]} raycast={()=>null}><planeGeometry args={[interaction.hover.width-.05,interaction.hover.height-.05]}/><meshBasicMaterial color="#e6be79" transparent opacity={.2} depthWrite={false}/></mesh>}
  </group>
  <primitive object={camera}><Html fullscreen position={[0,0,-1]} style={{pointerEvents:'none'}}><section className="city-studio" aria-label="Construction studio" onPointerDown={e=>e.stopPropagation()}>
   <header className="studio-header"><div className="studio-title"><House size={23} weight="duotone"/><div><input aria-label="Building name" maxLength={60} value={draft.name} onChange={e=>land.edit({...draft,name:e.target.value})}/><small>{land.saving?'Saving…':land.dirty?'Saving your changes':'Saved on this device'} <span>· Local test world</span></small></div></div><div className="studio-history"><button title="Undo · Ctrl Z" aria-label="Undo" disabled={!land.history.length||interaction.active} onClick={land.undo}><ArrowUUpLeft/></button><button title="Redo · Ctrl Shift Z" aria-label="Redo" disabled={!land.future.length||interaction.active} onClick={land.redo}><ArrowUUpRight/></button><button aria-label="Building help" aria-pressed={help} onClick={()=>setHelp(!help)}><Question/></button></div><div className="studio-complete"><button disabled={!recipe||land.previewStatus.pending||!!land.previewStatus.error} onClick={walk}><Eye/> <span>Walk around</span></button><button className="studio-primary" disabled={interaction.active||land.previewStatus.pending||!!land.previewStatus.error||land.saving} onClick={()=>void land.finish()}><Check/> Done</button><button aria-label="Exit construction" onClick={()=>void land.close()}><X/></button></div></header>
   {!recipe&&<aside className="studio-convert"><h2>Make this building your own</h2><p>Convert this saved design into editable parts. Your original stays in undo history.</p><button className="studio-primary" disabled={!upgradeStudio(draft,plot.size)} onClick={()=>{const next=upgradeStudio(draft,plot.size);if(next)land.edit(next);}}>Edit building parts</button>{!upgradeStudio(draft,plot.size)&&<p>This specialised building remains available in the original builder with cityStudio=0.</p>}</aside>}
   {help&&<aside className="studio-help"><button aria-label="Close help" onClick={()=>setHelp(false)}><X/></button><h2>A little building, all yours</h2><p><b>Draw a shape.</b> Pull its sides and top to make it fit.</p><p><b>Dress it.</b> Choose windows or a finish, then brush over the wall.</p><p><b>Add the details.</b> Drag a balcony across neighbouring upper windows.</p><p>Right-drag to orbit · Middle-drag to pan · Scroll to zoom.</p><small>Shift for fine movement. Escape cancels. Each gesture is one undo.</small></aside>}
   {recipe&&<>
    {selected&&<aside className="studio-selection"><div className="studio-selection-heading"><span>{selected.operation==='subtract'?'Cutout':selected.kind==='ellipse'?'Round part':'Building part'}<small>{selected.spanFloors} {selected.spanFloors===1?'storey':'storeys'}</small></span><button aria-label="Choose overlapping part" aria-pressed={parts} onClick={()=>setParts(!parts)}><Cube/></button></div><div className="studio-selection-actions"><button aria-label="Move selected part" title="Move" onClick={()=>{setTool('select');setCategory('Shape');}}><Hand/></button><button aria-label="Style selected part" title="Style" aria-pressed={styles} onClick={()=>setStyles(!styles)}><PaintBrush/></button><button aria-label="Duplicate part" title="Duplicate · Ctrl D" onClick={duplicate}><Copy/></button><button aria-label="Rotate part" title="Quarter turn" onClick={()=>editPart({width:selected.depth,depth:selected.width})}><ArrowClockwise/></button><button aria-label="Remove part" title="Remove" onClick={remove}><Trash/></button></div>
     {styles&&<div className="studio-style"><span className="studio-caption">Architectural look</span><div className="studio-family">{Object.entries(STUDIO_FAMILIES).map(([id,f])=><button key={id} title={f.label} aria-label={f.label} aria-pressed={style?.family===id} onClick={()=>editStyle({family:id as StudioFamily})}><i style={{background:f.wall,borderColor:f.trim}}/><small>{f.label}</small></button>)}</div><span className="studio-caption">Windows</span><div className="studio-segment">{(['sparse','regular','glazing'] as const).map(r=><button key={r} aria-pressed={style?.rhythm===r} onClick={()=>editStyle({rhythm:r})}>{r==='glazing'?'Glass':r}</button>)}</div><button onClick={()=>{setCategory('Roofs');setTool('roof');}}>Shape roof</button><span className="studio-caption">Quick roof</span><div className="studio-roofs">{roofOptions.map(roof=><button key={roof} aria-pressed={style?.roof===roof} onClick={()=>editStyle({roof})}><span className={`studio-roof-icon is-${roof}`}/>{roof}</button>)}</div><button className="studio-text" onClick={()=>{commit({...recipe,studio:{...recipe.studio,surfaces:recipe.studio.surfaces.filter(s=>s.anchor.shapeId!==selected.id),openings:recipe.studio.openings.filter(s=>s.anchor.shapeId!==selected.id)}});}}>Reset local paint and openings</button></div>}
     <button className="studio-text" aria-expanded={precision} onClick={()=>setPrecision(!precision)}>Precision {precision?'−':'+'}</button>{precision&&<div className="studio-precision">{([['width','Width',.25],['depth','Depth',.25],['spanFloors','Storeys',1],['startFloor','Base storey',1]] as const).map(([key,label,step])=><label key={key}>{label}<input aria-label={label} type="number" step={step} value={selected[key]} onChange={e=>editPart({[key]:Number(e.target.value)})}/></label>)}</div>}
    </aside>}
    {parts&&<aside className="studio-parts"><header><strong>Choose a part</strong><button aria-label="Close parts" onClick={()=>setParts(false)}><X/></button></header>{recipe.volumes.map((v,i)=><button key={v.id} aria-pressed={selected?.id===v.id} onClick={()=>{land.setSelectedVolume(v.id);setParts(false);setTool('select');}}>{v.kind==='ellipse'?<Cylinder/>:<Cube/>}<span>{v.operation==='subtract'?'Cutout':'Part'} {i+1}<small>Storeys {v.startFloor+1}–{v.startFloor+v.spanFloors}</small></span></button>)}</aside>}
    <nav className="studio-views" aria-label="Building camera"><button title="Orbit view" aria-label="Orbit view" onClick={()=>view('orbit')}><Compass/></button><button title="Top view" aria-label="Top view" onClick={()=>view('top')}>Top</button><button title="Front view" aria-label="Front view" onClick={()=>view('front')}>Front</button><button title="Focus selection" aria-label="Focus selection" onClick={()=>view('focus')}><ArrowsOut/></button><hr/><button aria-label="Next storey" disabled={floor===7} onClick={()=>setFloor(f=>Math.min(7,f+1))}><Plus/></button><span>Storey<br/><b>{floor+1}</b></span><button aria-label="Previous storey" disabled={!floor} onClick={()=>setFloor(f=>Math.max(0,f-1))}>−</button></nav>
    <footer className="studio-dock">
     {starters?<div className="studio-tray studio-starters">{STUDIO_EXAMPLES.map((example,i)=><button className="studio-tile" key={example.name} onClick={()=>recipe.volumes.length?setReplace(-i-2):starter(-i-2)}><img src={`/city/synarc-kit/v2/thumbnails/${example.thumbnail}.png`} alt=""/><span>{example.name}</span></button>)}<button className="studio-tile" onClick={()=>recipe.volumes.length?setReplace(-1):empty()}><Plus size={30}/><span>Empty plot</span></button>{COMPOSITIONS.filter(p=>!['twin-tower','atrium-campus'].includes(p.patch.archetype??'')).map(p=>{const index=COMPOSITIONS.indexOf(p);return <button key={p.name} className="studio-tile" onClick={()=>recipe.volumes.length?setReplace(index):starter(index)}><img src={`/city/presets/${p.name.toLowerCase().replaceAll(' ','-')}.webp`} alt=""/><span>{p.name}</span></button>;})}</div>:
     category==='Shape'?<div className="studio-tray"><button className="studio-tile" aria-pressed={tool==='select'} onClick={()=>setTool('select')}><Cursor size={29}/><span>Select</span></button>{([['block','Block',Cube],['round','Round',Cylinder],['oval','Oval',Cylinder],['cut','Cut',Eraser]] as const).map(([id,label,Icon])=><button className={`studio-tile tool-${id}`} aria-pressed={tool===id} key={id} onClick={()=>setTool(id)}><Icon size={34} weight="duotone"/><span>{label}</span></button>)}<span className="studio-divider"/><button className="studio-tile" onClick={()=>setStarters(true)}><House size={31} weight="duotone"/><span>Starting ideas</span></button><button className="studio-tile" onClick={()=>setParts(!parts)}><Cube size={29}/><span>My parts</span></button></div>:
     category==='Roofs'?<CityRoofTray abutment={prepared?.roofEdges?.find(e=>e.partId===selected?.id&&e.kind==='abutment')} scope={roofScope} setScope={setRoofScope} key={selected?.id??'none'} recipe={recipe} part={selected?.operation==='add'?selected:undefined} commit={commit} preview={r=>{if(r)setSculptPreview(plot.id,r,draft.design);else clearSculptPreview(plot.id);}}/>:
     category==='Openings'?<div className="studio-tray">{STUDIO_MODULES.filter(p=>p.category==='window'||p.category==='door'||p.id==='wall-full').map(p=><button className="studio-tile" key={p.id} aria-label={p.label} aria-pressed={opening===p.id&&!erase} onClick={()=>{setOpening(p.id);setErase(false);setTool('opening');}}><img src={`/city/synarc-kit/v2/thumbnails/${p.id}.png`} alt=""/><span>{p.label}</span></button>)}<button className="studio-tile" aria-pressed={erase} onClick={()=>setErase(!erase)}><Eraser size={28}/><span>Erase</span></button></div>:
     category==='Surfaces'?<div className="studio-surfaces"><div className="studio-paint-options"><div className="studio-segment">{(['spot','wall','part'] as const).map(s=><button aria-pressed={scope===s} key={s} onClick={()=>setScope(s)}>{s}</button>)}</div><label>Paint<select aria-label="Paint channel" value={channel} onChange={e=>setChannel(e.target.value as StudioChannel)}>{(['wall','trim','frame','door'] as const).map(c=><option key={c}>{c}</option>)}</select></label><label>Finish<select aria-label="Surface finish" value={texture} onChange={e=>setTexture(e.target.value)}><option value="">Smooth</option><option value="brick">Brick</option><option value="plaster">Plaster</option><option value="concrete">Stone</option><option value="timber">Timber</option></select></label></div><div className="studio-swatches">{STUDIO_COLORS.map(c=><button key={c} aria-label={`Paint ${c}`} aria-pressed={color===c&&!erase} style={{background:c}} onClick={()=>{setColor(c);setErase(false);setTool('surface');}}/>)}<input type="color" aria-label="Custom paint colour" value={color} onChange={e=>{setColor(e.target.value);setErase(false);}}/><button title="Copy finish" aria-label="Eyedropper" aria-pressed={eyedropper} onClick={()=>setEyedropper(!eyedropper)}><PaintBrush/></button><button title="Restore inherited finish" aria-label="Erase paint" aria-pressed={erase} onClick={()=>setErase(!erase)}><Eraser/></button></div></div>:
     category==='Details'?<><div className="studio-detail-options"><div className="studio-segment"><button aria-pressed={look==='simple'} onClick={()=>setLook('simple')}>Simple</button><button aria-pressed={look==='ornate'} onClick={()=>setLook('ornate')}>Ornate</button></div>{tool==='cornice'&&<button disabled={!interaction.hover} onClick={followWall}>Follow this wall</button>}{tool==='stair'&&<><label>To storey<select aria-label="Stair destination" value={destination} onChange={e=>setDestination(Number(e.target.value))}>{Array.from({length:8},(_,i)=><option key={i} value={i+1}>{i+2}</option>)}</select></label><button aria-pressed={flip} onClick={()=>setFlip(!flip)}>Flip direction</button></>}</div><div className="studio-tray">{details.map(([id,label,module])=><button className="studio-tile" key={id} aria-pressed={tool===id} onClick={()=>setTool(id)}><img src={`/city/synarc-kit/v2/thumbnails/${module}.png`} alt=""/><span>{label}</span></button>)}</div></>:
     <div className="studio-garden"><span className="studio-caption">Planting</span><div className="studio-segment">{(['minimal','garden','wooded'] as const).map(style=><button key={style} aria-pressed={draft.nature.style===style} onClick={()=>land.edit({...draft,nature:{...draft.nature,style}})}>{style==='minimal'?'Clear':style==='garden'?'Garden':'Wooded'}</button>)}</div><button onClick={()=>land.edit({...draft,nature:{...draft.nature,seed:(draft.nature.seed+7919)%1000000}})}>New arrangement</button><label>Ground<select aria-label="Ground finish" value={draft.design.textures?.ground??'grass-lawn'} onChange={e=>land.edit({...draft,design:{...draft.design,textures:{...draft.design.textures,ground:e.target.value as 'grass-lawn'}}})}><option value="grass-lawn">Lawn</option><option value="grass-meadow">Meadow</option><option value="pavers">Pavers</option></select></label><label>Boundary<select aria-label="Plot boundary" value={draft.design.enclosure??'garden-wall'} onChange={e=>land.edit({...draft,design:{...draft.design,enclosure:e.target.value as 'garden-wall'}})}><option value="garden-wall">Garden wall</option><option value="open-rail">Rail</option><option value="none">Open</option></select></label></div>}
     <nav aria-label="Construction tools">{categories.map(([name,Icon])=><button key={name} aria-pressed={category===name} onClick={()=>selectCategory(name)}><Icon size={20} weight={category===name?'fill':'regular'}/>{name}</button>)}</nav>
    </footer>
   </>}
   {replace!==null&&<div className="studio-confirm" role="dialog" aria-label="Replace building"><h2>Start a new shape?</h2><p>You can undo this and return to your current building.</p><button onClick={()=>setReplace(null)}>Keep building</button><button className="studio-primary" onClick={()=>{if(replace===-1){empty();setReplace(null);}else starter(replace);}}>Replace building</button></div>}
   {interaction.touchPending&&<div className="studio-touch-confirm"><button onClick={interaction.cancel}>Cancel</button><button className="studio-primary" onClick={interaction.confirm}><Check/> Place</button></div>}
   <div className="studio-feedback" role="status" aria-live="polite">{land.error?<><span>{land.error}</span><button onClick={()=>void land.retry()}>Retry save</button></>:land.previewStatus.error?<><span>{land.previewStatus.error}</span><button onClick={land.retryPreview}>Retry building</button></>:interaction.issue?<span>{interaction.issue}</span>:land.previewStatus.pending?<span className="studio-preparing">Shaping your building…</span>:!recipe?null:!recipe.volumes.length?<span>Draw your first block inside the plot</span>:tool==='balcony'?<span>Brush across neighbouring upper windows</span>:tool==='stair'?<span><Stairs size={16}/> Choose a side wall · Stairs fit the floor heights</span>:tool==='select'?<span>Choose a part · Pull a face to reshape it</span>:tool==='surface'?<span>{eyedropper?'Choose a finish to copy':`Paint ${scope==='spot'?'a spot':scope==='wall'?'this wall':'this part'} · ${channel}`}</span>:<span>Click to place · Drag to extend · Escape to cancel</span>}</div>
   {!!prepared?.roofNotes.length&&<div className="studio-roof-note" role="status">{prepared.roofNotes.join(" ")}</div>}
   {!!inactive.length&&<details className="studio-inactive"><summary>{inactive.length} details need a little space</summary>{inactive.map(item=><div key={item.id}><span>{item.reason}</span><button aria-label="Remove inactive detail" onClick={()=>recipe&&commit({...recipe,studio:{...recipe.studio,assemblies:recipe.studio.assemblies.filter(a=>a.id!==item.id)}})}><Trash size={14}/></button></div>)}</details>}
  </section></Html></primitive>
 </>;
}
