import {useRef,useState} from 'react';
import {ROOF_TYPES,connectedRoofParts,editStudioRoof,roofChoice} from '../../domain/cityStudioRoofEnvelope';
import type {StudioRecipe,StudioRoofSettings,StudioRoofEdge} from '../../domain/cityStudioTypes';
import type {SculptVolume} from '../../domain/citySculpt';

type Props={abutment?:StudioRoofEdge;scope:'part'|'connected';setScope:(s:'part'|'connected')=>void;recipe:StudioRecipe;part:SculptVolume|undefined;commit:(r:StudioRecipe)=>void;preview:(r:StudioRecipe|null)=>void};
export function CityRoofTray({recipe,part,commit,preview,scope,setScope,abutment}:Props){
 const [precision,setPrecision]=useState(false),[drag,setDrag]=useState<StudioRoofSettings|null>(null),pending=useRef<StudioRecipe|null>(null);
 if(!part)return <div className="studio-roof-empty">Select a roof or building part to shape its roof.</div>;
 const ids=scope==='connected'?connectedRoofParts(recipe,part.id):[part.id],choice=roofChoice(recipe,part.id),s={...choice.settings,...drag},flat=choice.type==='flat'||choice.type==='terrace';
 const change=(settings:StudioRoofSettings)=>commit(editStudioRoof(recipe,ids,{settings}));
 const finish=()=>{if(pending.current){commit(pending.current);pending.current=null;}setDrag(null);preview(null);};
 const cancel=()=>{pending.current=null;setDrag(null);preview(null);};
 const slider=(key:'rise'|'overhang'|'shoulder'|'crown',label:string,min:number,max:number,step:number)=><label className="studio-roof-slider" key={key}><span>{label}<output>{key==='rise'||key==='overhang'?`${s[key].toFixed(2)} m`:`${Math.round(s[key]*100)}%`}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={s[key]} onChange={e=>{const patch={[key]:Number(e.target.value)};setDrag(patch);pending.current=editStudioRoof(recipe,ids,{settings:patch});preview(pending.current);}} onPointerUp={finish} onPointerCancel={cancel} onBlur={finish} onKeyUp={e=>{if(e.key==='Escape')cancel();else finish();}}/></label>;
 if(!recipe.studio.roofRevision)return <div className="studio-roof-upgrade"><strong>Connected roof editing</strong><span>Updates this building’s roof connections. Your original stays in Undo.</span><button onClick={()=>commit({...recipe,studio:{...recipe.studio,roofRevision:'roof-envelope-2'}})}>Enable roof editing</button></div>;
 return <div className="studio-roof-workspace">
 <div className="studio-roof-toolbar"><div className="studio-segment"><button aria-pressed={scope==='part'} onClick={()=>setScope('part')}>This part</button><button aria-pressed={scope==='connected'} onClick={()=>setScope('connected')}>Connected roofs{scope==='connected'?` · ${ids.length}`:''}</button></div><span>Pull the ridge to change height · Drag an eave to extend it</span></div>
 <div className="studio-tray">{ROOF_TYPES.map(t=><button className="studio-tile" key={t.id} aria-label={`${t.label} roof`} aria-pressed={choice.type===t.id} onPointerEnter={e=>{if(e.pointerType==='mouse'&&!pending.current)preview(editStudioRoof(recipe,ids,{type:t.id}));}} onPointerLeave={()=>{if(!pending.current)preview(null);}} onFocus={()=>preview(editStudioRoof(recipe,ids,{type:t.id}))} onBlur={()=>preview(null)} onClick={()=>{preview(null);commit(editStudioRoof(recipe,ids,{type:t.id}));}}><img src={`/city/roofs/${t.id}.svg`} alt=""/><span>{t.label}</span></button>)}</div>
 <div className="studio-roof-controls">{abutment&&choice.type!=='shed'&&<button onClick={()=>commit(editStudioRoof(recipe,ids,{type:'shed',settings:Math.abs(abutment.b[0]-abutment.a[0])>Math.abs(abutment.b[2]-abutment.a[2])?{ridge:'x',flip:(abutment.a[2]+abutment.b[2])/2<part.z}:{ridge:'z',flip:(abutment.a[0]+abutment.b[0])/2<part.x}}))}>Try a lean-to here</button>}{!flat&&<><div><small>Roof height</small><div className="studio-segment">{[['Low',1],['Balanced',2],['Steep',3.5]].map(([name,rise])=><button key={name} aria-pressed={s.rise===rise} onClick={()=>change({rise:Number(rise)})}>{name}</button>)}</div></div>{!['cone','pyramid','mansard'].includes(choice.type)&&<button onClick={()=>change({ridge:s.ridge==='x'?'z':'x'})}>Turn ridge</button>}{choice.type==='shed'&&<button aria-pressed={s.flip} onClick={()=>change({flip:!s.flip})}>Flip slope</button>}<div><small>Eaves</small><div className="studio-segment">{[['Flush',0],['Small',.2],['Deep',.65]].map(([name,overhang])=><button key={name} aria-pressed={s.overhang===overhang} onClick={()=>change({overhang:Number(overhang)})}>{name}</button>)}</div></div></>}
 {flat&&<label>Edge<select aria-label="Roof edge" value={s.boundary} onChange={e=>change({boundary:e.target.value as StudioRoofSettings['boundary']})}><option value="none">Open edge</option><option value="parapet">Parapet</option><option value="rail">Railing</option></select></label>}<label>Join<select aria-label="Roof connection" value={s.connection} onChange={e=>change({connection:e.target.value as StudioRoofSettings['connection']})}><option value="auto">Auto connect</option><option value="abut">End against wall</option><option value="separate">Keep separate</option></select></label>
 <label>Finish<select aria-label="Roof finish" value={s.finish} onChange={e=>change({finish:e.target.value as StudioRoofSettings['finish']})}><option value="slate">Slate</option><option value="terracotta">Terracotta</option><option value="metal">Metal</option></select></label><input type="color" aria-label="Roof colour" value={s.color??(s.finish==='terracotta'?'#a9694e':s.finish==='metal'?'#7c9189':'#64727b')} onChange={e=>{const patch={color:e.target.value};setDrag(patch);pending.current=editStudioRoof(recipe,ids,{settings:patch});preview(pending.current);}} onBlur={finish}/>
 <button aria-expanded={precision} onClick={()=>setPrecision(!precision)}>Adjust</button></div>
 {precision&&<div className="studio-roof-dimensions">{!flat&&slider('rise','Roof rise',.2,8,.05)}{!flat&&slider('overhang','Eave depth',0,1.2,.05)}{['mansard','gambrel','hip'].includes(choice.type)&&slider('crown',choice.type==='mansard'?'Crown width':choice.type==='hip'?'Ridge length':'Shoulder position',.15,.75,.025)}{['gambrel','half-hip'].includes(choice.type)&&slider('shoulder',choice.type==='half-hip'?'End height':'Shoulder height',.35,.85,.025)}</div>}
 </div>;
}
