create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  is_complete boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.todos enable row level security;

drop policy if exists "Public todos are readable" on public.todos;
create policy "Public todos are readable"
on public.todos
for select
to anon, authenticated
using (true);
